게시글 조기 마감 기능 구현
woowacourse-teams/2023-votogether pull request #115
Opened 2023-07-21 01:38 UTC by tjdtls690

## 🔥 연관 이슈

close: #95 

## 📝 작업 요약

지정한 게시글을 조기마감 시키는 기능

## 🔎 작업 상세 설명

- 해당 id에 해당하는 게시글의 마감 시간을 현재 시간으로 변경한다.

## 🌟 논의 사항

2023-07-21 08:00 UTC, woo-chang reviewed
수고하셨습니다 아벨 🙇🏻‍♂️👏🏻
깔끔하게 잘 작성해주셨네요 :)
작은 코멘트와 질문 남겨두었으니 확인해주시면 감사합니다!

2023-07-24 12:51 UTC, jeomxon requested changes
조기 마감 기능도 잘 구현해주셨네요!!
고생 많으셨습니다 :) 사소한 코멘트 남겨두었어요~

2023-07-24 12:51 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +    }
`P2`
id라는 네이밍보다 PathVariable자체를 postId라는 네이밍으로 받아오면 어떨까?하는 생각입니다.
조금 더 직관적이기도 하고, 위에 있는 함수들에서도 postId, optionId를 사용하셨기에 일관성 유지 측면에서도 좋을 것 같다는 생각이 드네요 ㅎㅎ

2023-07-24 12:51 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
동의합니다 특히나 3번 검증 과정은 정책상 필수적이라는 생각이 드네요!
1번은 멤버를 받으면서 자연스럽게 작성하실 것이라는 생각이 듭니다 ㅎㅎ

2023-07-24 12:51 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +                .when().patch("/posts/" + postId + "/close")
`P2`
path parameter를 사용하여 가독성을 높이고 직관적이게 만들 수 있을 것 같아요!

2023-07-24 12:51 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
> +        Category category2 = Category.builder().build();
리팩터링과 함께 테스트 코드 작성👍🏻

2023-07-24 12:51 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +                () -> assertThat(findedPost.getDeadline()).isBefore(oldDeadline)
`P2`
finded -> found가 더 자연스러워 보입니다 :)

2023-07-24 14:15 UTC, aiaiaiai1 reviewed
기능구현 고생하셨어요~!
메서드 네이밍과 관련해서 간단하게 코멘트 남겼씁니당

2023-07-24 14:15 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +    public ResponseEntity<Void> postClosedEarly(@PathVariable final Long id) {
`P2`
동사로 메서드명을 시작하는건 어떤가요
`closePostEarly`

2023-07-24 14:15 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    public void closedEarly() {
`P3`
`closeEarly` 가 더 적합한거같습니다!

2023-07-28 05:41 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +    public ResponseEntity<Void> postClosedEarly(@PathVariable final Long id) {
그러게요. 수정하겠습니다.

2023-07-28 06:08 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
지금까지 예외 처리에 대한 부분은 고민하지 않고 구현을 했었는데, 이제 Exception 구조가 자리 잡혔으니 바로 적용해보도록 하겠습니다.

2023-07-31 04:12 UTC, woo-chang approved these changes
수고하셨습니다 아벨 🙇🏻‍♂️
꼼꼼하게 잘 작성해주셨네요 :)
approve 하도록 하겠습니다 👍

2023-07-31 04:12 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +        final LocalDateTime midpoint = getCreatedAt().plus(betweenDuration.dividedBy(2));
`P3`
```suggestion
        final LocalDateTime earlyClosingTime = getCreatedAt().plus(betweenDuration.dividedBy(2));
```
변수명을 조금 더 명확하게 해도 좋을 것 같아요 :)

2023-07-31 04:12 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +        post.closeEarly();
`P3`
꼼꼼한 검증 좋습니다 👍

2023-07-31 05:52 UTC, jeomxon approved these changes
수정하시느라 고생하셨습니다 :)
이만 approve하겠습니다!
사소한 코멘트만 남겨두었어요~

2023-07-31 05:52 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +            throw new BadRequestException(PostExceptionType.POST_OPTION_NOT_FOUND);
`P3`
크게 중요하진 않지만 BadRequestException인데 NotFound를 던지고 있으니 개인적으로는 어색하다는 생각이 듭니다.
NonExistPostOption등의 네이밍으로 변경해보는 것은 어떨까요?

2023-07-31 05:52 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +        final Duration betweenDuration = Duration.between(getCreatedAt(), this.deadline);
Duration...처음 봤습니다 이런 기능이 있었군요!

2023-07-31 05:52 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
> +    POST_NOT_HALF_DEADLINE(1005, "게시글이 마감 시간까지 절반의 시간 이상이 지나지 않으면 조기마감을 할 수 없습니다."),
`P3`
`CloseEarlyNotAllowed`등의 네이밍을 사용해보는 것은 어떨까요?
개인적으로 한번만에 해석이 잘 되지 않는 것 같아서요..!

2023-07-31 05:52 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +                .when().patch("/posts/{postId}/close", postId)
👍🏻

2023-07-31 05:52 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
> +                    Thread.sleep(50);
`Q`
Thread.sleep을 사용하신 이유가 궁금합니다!

2023-08-02 02:22 UTC, merged