게시글 삭제 기능 구현
woowacourse-teams/2023-votogether pull request #118
Opened 2023-07-21 03:55 UTC by tjdtls690

## 🔥 연관 이슈

close: #111 

## 📝 작업 요약

게시글을 삭제하는 기능을 구현한다

## 🔎 작업 상세 설명

- 해당 post id에 해당하는 게시글을 삭제한다.
- 마감 안된 게시글이면 예외처리 한다.

## 🌟 논의 사항

2023-07-22 07:18 UTC, woo-chang reviewed
정말 정말 많은 기능 개발하시느라 수고하셨네요 아벨 👍🏻👍👍🏻
소소한 리뷰와 질문 남겨두었으니 확인 부탁드릴께요 :)

2023-07-22 07:18 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +            @ApiResponse(responseCode = "500", description = "인터넷 서버 오류입니다.")
`P3`
동일합니다 `ditto`~

2023-07-22 07:18 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +    public ResponseEntity<Void> delete(@PathVariable final Long id) {
`P2`
여기도 `Member`가 추가되면 좋겠네요 :)

2023-07-22 07:18 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +        postService.deleteById(id);
```suggestion
        postService.deletePostById(id);
```
`P3`
삭제되는 대상을 알려주는 메서드명이면 더욱 직관적일 것 같은데 아벨은 어떻게 생각하시나요?!

2023-07-22 07:18 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +            throw new IllegalArgumentException("마감 안된 게시글은 삭제할 수 없습니다.");
`P2`
마감되지 않더라도 삭제는 가능한 것으로 기획 수정이 발생한 것으로 알고 있는데 한번 더 얘기해봐요 :)

2023-07-22 07:18 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +        postRepository.deleteById(id);
`Q`
`id`가 테이블에 존재하지 않더라도 예외는 발생하지 않습니다! 따라서 `deleteById`만 해도 괜찮은 상황인데 이전에 확인을 한번 더 해주신 아벨의 이유가 궁금합니다!

없는 id에 대한 삭제 요청을 유효하지 않은 요청으로 판단한 것인가요?! 🤔

2023-07-24 13:54 UTC, jeomxon requested changes
게시글에 대한 기능들을 전부 작성하시느라 고생하셨습니다!!
사소한 코멘트 남겨두었어요 :)

2023-07-24 13:54 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +    public ResponseEntity<Void> delete(@PathVariable final Long id) {
`P2`
여기도 마찬기지로 postId!!가 좋아보입니다~

2023-07-24 13:54 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +        postService.deleteById(id);
다즐의 코멘트에 추가적인 의견 남겨봅니다!
저는 개인적으로 postService라는 것에서 Post를 삭제함을 쉽게 알 수 있다는 생각이 듭니다.
하지만 PostService에서 post뿐만 아니라 다른 객체들에 대한 CRUD, 그 이상을 진행하게 된다면 혼동의 여지가 있으므로 그 때 추가하는 방법도 좋다고 생각합니다.
이에 대해 아벨은 어떻게 생각하시나요?

2023-07-24 13:54 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +    }
`P1`
개행이 필요해보입니다~

2023-07-24 13:54 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
> +                .build();
`Q`
개행을 주신 이유가 있을까요? 저였다면 개행을 넣지 않을 것 같다는 생각이 들어서요!

2023-08-10 07:59 UTC, closed without merging