댓글 작성 기능 구현
woowacourse-teams/2023-votogether pull request #151
Opened 2023-07-27 03:46 UTC by woo-chang

## 🔥 연관 이슈

close: #128

## 📝 작업 요약

댓글 작성 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 댓글 도메인을 구현하였습니다.
- 댓글 작성 기능을 구현하였습니다.
- Swagger Auth 관련 설정을 추가하였습니다.
- MVC 관련 예외 처리를 구현하였습니다.

## 🌟 논의 사항

없습니다 :)

2023-07-27 09:00 UTC, tjdtls690 approved these changes
지금 제 눈엔 이 외에 개선점이 잘 보이지가 않네요. 나중에 혹시라도 더 보이면 추가하겠습니다.

역시 
                                 ㅡ 즐 ㅡ

\(￣︶￣*\))

2023-07-27 09:02 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/exception/BaseException.java
> +    private final int code;
```Q```
혹시 다즐은 어디서든 필드를 정의할 때, 원시타입과 래퍼 클래스 타입 중 어떤 것을 더 선호하는지, 그 이유는 무엇인지 궁금합니다.

2023-07-27 12:48 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    private List<Comment> comments = new ArrayList<>();
좋은 의견 감사합니다 👍
해당 속성은 댓글의 `post` 값이 `null`이 되었을 때 삭제 쿼리가 날라가는 것으로 알고 있습니다 ㅎㅎ 보통 댓글을 삭제하는 경우를 생각해 보았을 때 `ID`를 이미 알고 있는 상황이라고 생각이 들어요!

`ID`를 알고 있다면 해당 `ID`로 삭제 쿼리를 날리는 것이 일반적인 삭제 로직이 될 것 같은데 어떤 상황에서 해당 기능을 활용할 수 있는지 궁금합니다 :)

2023-07-27 12:49 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        );
빼고 확인해보았을 때 변수로 빼는 것이 더 가독성이 좋은 것 같아서 수정했습니다 👍

2023-07-27 12:55 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/jwt/Auth.java
> +@Hidden
해당 어노테이션은 스웨거에서 사용되는 어노테이션으로 `@Hidden`이 붙은 어노테이션은 Swagger에서 보이지 않게 됩니다!

<img width="1435" alt="스크린샷 2023-07-27 오후 9 52 04" src="https://github.com/woowacourse-teams/2023-votogether/assets/78212016/f8fe17ff-0857-41e5-9af2-df23a2120e5e">

붙이지 않고 사용하면 일반적인 요청에도 해당 멤버의 값들이 입력받아야 하는 값으로 인식해 `Request`에 그대로 노출되게 됩니다. 저희 프로젝트에서 `Auth`가 붙은 매개변수는 `ArgumentResolver`가 처리해서 넘겨주는 값이기에 요청 시 보여주지 않아도 된다고 판단하였습니다. 따라서 보이지 않도록 설정하였습니다 :)

어노테이션을 붙이면 아래와 같이 보이게 됩니다.

<img width="1434" alt="스크린샷 2023-07-27 오후 9 55 03" src="https://github.com/woowacourse-teams/2023-votogether/assets/78212016/e24b9ba3-c3b0-459d-bff6-50488ad44600">

2023-07-27 12:56 UTC, woo-chang commented on backend/src/main/java/com/votogether/exception/BaseException.java
> +    private final int code;
상황에 따라 다른 것 같아요! 값을 입력하지 않았을 때 기본값(ex) int인 경우 0, boolean인 경우 false)이 들어가도 괜찮은 경우라면 원시타입을 사용하고, 그렇지 않다면 래퍼클래스를 사용하는 것 같아요 :)

2023-07-27 13:19 UTC, jeomxon requested changes
코드 작성하시느라 고생하셨습니다 다즐 :)
역시나 신의 코드는 다르네요
사소한 코멘트 몇개 남겨두었습니다~!

2023-07-27 13:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/config/OpenAPIConfig.java
> +                .addList("bearerAuth");
`Q`
신기한 기능이네요!
swagger에 토큰을 적용해볼 수 있는 코드라고 생각하면 될까요?

2023-07-27 13:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
> +    public ResponseEntity<Void> registerComment(
`Q`
Controller, Service는 `PostComment`, Repository, Entity는 `Comment`라는 네이밍을 가져간 이유가 있을까요?

2023-07-27 13:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
> +    }
`P3`
register보다는 create등의 다른 네이밍이 조금 더 자연스럽지 않을까요?

2023-07-27 13:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +                .orElseThrow(() -> new BadRequestException(PostExceptionType.POST_NOT_FOUND));
`P2`
NotFoundException을 사용해도 되지 않을까요?

2023-07-27 13:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        post.addComment(comment);
저는 이전 방식보다 이렇게 작성하는 것이 더 좋아보인다고 생각했는데, 변경해주셨군요👍🏻

2023-07-27 13:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
> +                    String.format("댓글 길이는 최대 %d자까지 가능합니다.", MAXIMUM_LENGTH)
`Q`
메시지를 따로 작성해주신 이유가 있을까요?
Enum에서 가지고 있는 메시지로도 충분히 예외를 표시해줄 수 있을 것 같은데
최대 길이가 꼭 포함되어야 하는 이유가 있을까요?

2023-07-28 02:01 UTC, woo-chang commented on backend/src/test/resources/application.yml
> +
테스트에서는 사용할 일이 없어 크게 차이가 없을 것 같네요! 제거하도록 하겠습니다 ㅎㅎ

2023-07-28 02:04 UTC, woo-chang commented on backend/src/main/java/com/votogether/config/OpenAPIConfig.java
> +                .addList("bearerAuth");
맞습니다 :) 해당 기능을 사용하면 Swagger 전역적으로 토큰을 적용할 수 있습니다. 현재는 `Bearer` 토큰을 설정해두었는데, 설정을 수정하면 `Basic` 토큰도 사용이 가능합니다!

2023-07-28 02:06 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
> +    public ResponseEntity<Void> registerComment(
비즈니스 로직과 연관이 있는 Controller, Service에서는 게시글과 연관관계를 표현하기 위해 `PostComment`를 사용했고 영속 책임이 있는 Repository, Entity는 대상이 댓글이라 `Comment`를 사용했습니다!

테이블 상의 명칭을 따랐던 것 같아요 😄

2023-07-28 02:06 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
> +    }
좋습니다 👏🏻

2023-07-28 02:09 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +                .orElseThrow(() -> new BadRequestException(PostExceptionType.POST_NOT_FOUND));
놓쳤던 부분입니다 .. 체고 👍🔥

2023-07-28 02:14 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
> +                    String.format("댓글 길이는 최대 %d자까지 가능합니다.", MAXIMUM_LENGTH)
프론트에서 백엔드의 예외 메시지를 그대로 사용한다고 해서 클라이언트에게 자세한 메시지를 전달하려고 했습니다 :)

2023-07-28 02:14 UTC, aiaiaiai1 reviewed
다즐 기능 구현 고생하셨습니다~
간단한 질문 남겨드렸어요!

2023-07-28 02:14 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
> +        RestAssuredMockMvc.webAppContextSetup(webApplicationContext);
'Q'
요 메서드는 어떤 역할을 하는건가요?

2023-07-28 02:19 UTC, woo-chang commented on backend/src/main/java/com/votogether/config/OpenAPIConfig.java
> +
<img width="1456" alt="스크린샷 2023-07-28 오전 11 17 32" src="https://github.com/woowacourse-teams/2023-votogether/assets/78212016/900f5084-4170-424d-9da9-9130f9b86394">

2023-07-28 02:31 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        );
연관관계 편의 메서드 내부에서 관계를 맺어주는게 더 안전하다고 생각합니다!

연관관계를 맺어주는 코드가 분리되어 있으면, 다시 말해서 외부에서 `Post`를 지정하고 내부에서는 `Comment`를 목록에 추가하는 상태인 경우 `addComment`에는 게시글이 지정되어 있지 않은 댓글, 해당 게시글이 아닌 다른 게시글로 지정된 댓글 등 올바르지 않은 댓글이 다 들어올 수 있는 상태가 되어버립니다! 내부적으로도 해당 댓글의 게시글을 수정하지 않으니 의도하지 않은 동작을 할 가능성이 매우 높아지게 됩니다.

따라서 연관관계 편의 메서드에서 댓글의 게시글을 지정하여 의도한 동작을 보장하도록 하였습니다. 연관관계 편의 메서드에서 댓글의 게시글을 지정하게 되면 게시글이 없는 댓글, 다른 게시글이 들어있는 댓글이어도 해당 게시글의 댓글로 지정되어 연관관계 맺을 때 양방향 안정성을 가져갈 수 있게 됩니다 😄

그리고 양방향으로 연관관계가 되어있는 경우 항상 양쪽의 연관관계를 연결시켜줘야 하기 때문에 `addComment` 안에서 수행하는 것이 안전한 동작을 보장할 수 있을 것 같아요 :)

2023-07-28 03:28 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
> +            );
사용자에게 조금 더 자세한 예외 메시지를 전달하려고 하다보니 코드 속에 에러 메시지가 들어가게 된 것 같아요!

루쿠는 `올바르지 않은 댓글 길이입니다!` 정도면 충분히 예외 상황을 인지할 수 있다고 생각하시나요?

2023-07-28 03:32 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
> +        RestAssuredMockMvc.webAppContextSetup(webApplicationContext);
애플리케이션 컨텍스트를 가져와서 `MockMvc`에 적용하는 역할을 수행합니다!

컨텍스트를 적용하지 않으면 `ArgumentResolver`나 `ExceptionHandler`가 제대로 동작하지 않아서 컨텍스트를 등록하였습니다 :)

2023-07-28 03:42 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/config/OpenAPIConfig.java
> +
오호 직접 실험까지! 감사합니다

2023-07-28 03:57 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
> +        RestAssuredMockMvc.webAppContextSetup(webApplicationContext);
한수 배워갑니다~

2023-07-28 04:02 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        );
> 연관관계 편의 메서드에서 댓글의 게시글을 지정하게 되면 게시글이 없는 댓글, 다른 게시글이 들어있는 댓글이어도 해당 게시글의 댓글로 지정되어 연관관계 맺을 때 양방향 안정성을 가져갈 수 있게 됩니다 😄

그렇다면 다른 게시글에 들어있는 댓글을 addCommnet를 통해 실수로 해당 게시글의 댓글로 지정되어버리면 다른 게시글에 있는 댓글이 해당 게시글로 잘못 들어가는 경우가 생길수도 있지 않을까요?! 
post.addComment를 할때 comment필드의 post와 this가 같은지를 검증하는 로직을 추가하는거에 대해서는 어떻게 생각하시나요??

2023-07-28 04:03 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
> +                    String.format("댓글 길이는 최대 %d자까지 가능합니다.", MAXIMUM_LENGTH)
사용자에게 어느정도 정보까지 알려줄지가 중요할 것 같은데요.
닉네임 정책이 클라이언트의 페이지 상에 표시가 된다면 `올바르지 않은 글자 수`라는 예외 메시지로도 충분할 것 같다는 생각이고,
지금의 형태도 유지보수성을 고려하여 작성해주신 것 같아서 좋아보여요.
다즐 편하신대로 적용해서 반영해주세요~

2023-07-28 04:06 UTC, jeomxon approved these changes
코멘트 반영해주신 부분 잘 확인했습니다 :)
고생하셨습니다!

2023-07-28 04:10 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/comment/Content.java
> +            );
저는 구체적일수록 좋다는 입장이지만 
만약 최대 가능한 댓글 길이를 적어준다고 해도 사용자는 현재 자신이 쓰고있는 댓글의 길이가 어느정도 되는지 확인을 못할거 같다는 생각입니다. 그래서 나중에 댓글을 작성할때 옆에 화면에 15/500 처럼 댓글길이를 보여준다면 
`댓글길이를 확인해주세요!` 와 같은 에러메시지로 충분할것 같다는 생각입니다.

2023-07-28 04:54 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        );
`addComment`에서 댓글의 게시글을 지정하지 않을 경우
- 댓글의 ID가 없는 경우
  - 게시글이 지정되지 않은 경우 : 게시글 ID가 없어서 예외 발생
  - 게시글이 다른 게시글로 지정된 경우 : 다른 게시글에 댓글 등록
  - 게시글이 해당 게시글로 지정된 경우 : 해당 게시글에 댓글 등록
- 댓글의 ID가 있는 경우
  - 게시글이 다른 게시글로 지정된 경우 : 아무런 쿼리 X
  - 게시글이 해당 게시글로 지정된 경우 : 아무런 쿼리 X

`addComment`에서 댓글의 게시글을 지정하는 경우
- 댓글의 ID가 없는 경우
  - 게시글이 지정되지 않은 경우 : 해당 게시글에 댓글 등록
  - 게시글이 다른 게시글로 지정된 경우 : 해당 게시글에 댓글 등록
  - 게시글이 해당 게시글로 지정된 경우 : 해당 게시글에 댓글 등록
- 댓글의 ID가 있는 경우
  - 게시글이 다른 게시글로 지정된 경우 : 해당 게시글로 댓글 업데이트
  - 게시글이 해당 게시글로 지정된 경우 : 아무런 쿼리 X

위와 같은 결과를 확인할 수 있습니다. 가장 안전한 방법을 선택한다면 `addComment`에서 댓글 게시글을 지정하고, ID가 없는지까지 확인하는 방법일텐데 ID가 있는지 없는지는 서비스에서 검증해야할 것 같습니다.

따라서 지금과 같은 방법을 사용하려고 하는데 괜찮으신가요?! ☺️

2023-07-28 05:04 UTC, merged