게시글 작성 기능 API 명세의 변경에 따른 코드 수정
woowacourse-teams/2023-votogether pull request #173
Opened 2023-07-30 16:53 UTC by tjdtls690

## 🔥 연관 이슈

close: #172 

## 📝 작업 요약

게시글 작성 시, 클라이언트로부터 받는 데이터 형식의 변경

## 🔎 작업 상세 설명

- 게시글 작성 시 클라이언트로부터 받는 데이터 중, 이미지 URL 문자열을 추가로 받는 것으로 변경
- 각 값들에 대한 유효성 검증

## 🌟 논의 사항

2023-07-31 05:32 UTC, woo-chang requested changes
수고하셨습니다 아벨 🙇🏻‍♂️
어려운 작업이었을텐데 잘 작성해주셨어요 :)
몇 가지 질문과 커멘트 남겨두었으니 확인 부탁드릴께요 ㅎㅎ

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostRequest.java
> +        String imageUrl,
`P2`
게시글 생성 요청에는 이미지 URL 정보가 항상 없을 것 같은데 해당 컬럼을 어디서 사용하는지 궁금합니다 🤔

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +            @RequestPart @Valid final PostRequest request,
`P2`
`PostCreateRequest` -> `PostRequest`로 수정한 이유가 무엇인가요?!

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionRequest.java
> +}
`P2`
요청과 응답 정보에 대한 Swagger 설정이 빠져있는 것 같아요 :)

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionRequest.java
> +        String content,
`P3`
사소한 궁금증이지만, 공백으로 50자 이상으로 구성된 문자열이 온 경우 어떤 검증에 걸리게 될까요? 🤔

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionRequest.java
> +        String imageUrl
`P2`
게시글 작성할 때는 옵션에 대한 이미지가 아직 저장되지 않은 상태이기에 해당 필드도 항상 `null`일 것 같다는 생각이 들었어요.

그렇기에 사용하지 않는 필드인 것 같은데 해당 필드가 있는 이유가 궁금합니다!

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostRequest.java
> +        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
`Q`
`@JsonFormat` 어노테이션도 있는 것으로 알고 있는데 둘은 어떤 차이가 있나요?!

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    }
`P3`
이해하기 쉬운 메서드 체고 👍

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostContentImages.java
> +        final String contentImageUrl = ImageUploader.upload(contentImage);
`P1`
이미지 저장은 외부 서비스라고 생각합니다! 고수준 정책인 도메인에서 저수준 정책인 외부 서비스를 알게 되어, 고수준에서 저수준 방향으로 의존성이 역전되었다는 생각이 들어요 😀

이미지 저장은 서비스에서 진행하고, 경로만 도메인으로 전달하는 방법으로 수정해보는건 어떨까요?

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
> +            final String imageUrl = ImageUploader.upload(optionImage);
`P1`
여기도 동일하게 이미지 저장은 도메인 외부에서 이루어지도록 바꿔보는건 어떨까요?!

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
> +        final String imageUrl = absolutePath + "/images/" + image.getOriginalFilename();
`Q`
1. 이렇게 하면 빌드된 jar 파일을 실행시켰을 때 실행된 컨텍스트의 `images` 디렉토리에 파일이 저장되는건가요?!
2. 만약 `images` 디렉토리가 존재하지 않으면 예외가 발생하나요?

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
> +        }
`P2`
이미지 저장이 실패했을 때 무시해도 괜찮을까요? 🤔

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +@RestControllerAdvice(basePackageClasses = PostController.class)
`Q`
`basePackageClasses`를 `PostController`로 잡으면 나머지 컨트롤러에서 동작안하지 않나요?!

2023-07-31 05:32 UTC, woo-chang commented on backend/src/main/resources/application.yml
> +      enabled: true
`P3`
콘솔 확인 좋아용 👍

2023-07-31 07:30 UTC, jeomxon requested changes
정말 고생 많으셨습니다 :)
테스트 작성하실때도 많은 시간이 걸리셨으리라 예상이 되네요..ㅠㅠ
질문거리들 몇개 남겨두었습니다~

2023-07-31 07:30 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    }
`P2`
이 메서드는 마김일에 대한 기준이 변경되었을 경우 확장성에 불리하다는 생각이 들어요.
저는 개인적으로 validateDeadlinNotExceedByDay와 같은 네이밍을 가져가면서 해당 일수를 파라미터로 받으면 어떨까? 라는 생각이 들네요.
아벨은 어떻게 생각하시나요?

2023-07-31 07:30 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/PostContentImages.java
> +        final String contentImageUrl = ImageUploader.upload(contentImage);
@woo-chang
`이미지 저장은 외부 서비스라고 생각합니다! 고수준 정책인 도메인에서 저수준 정책인 외부 서비스를 알게 되어, 고수준에서 저수준 방향으로 의존성이 역전되었다는 생각이 들어요 😀`
저는 이게 무슨 말인지 잘 이해가 안됩니다.
혹시 조금 더 자세하게 설명해주실 수 있나요?

2023-07-31 07:30 UTC, jeomxon commented on backend/src/main/resources/application.yml
> +      enabled: true
`P3`
h2관련 path를 filter에서 처리하고 있는데 설정파일에도 path를 지정해주면 어떨까요?

2023-07-31 08:06 UTC, aiaiaiai1 reviewed
고생하셨습니다 아벨
두분께서 제가 궁금했던 내용과 피드백을 다 해주셔서 두분꺼 피드백 반영하시면 될거같아요!
게시글 작성기능이 정말 어렵군요,,,, 마지막까지 화이팅입니다!

2023-07-31 14:31 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +            @RequestPart @Valid final PostRequest request,
지금 생각해보면 지금 구현하고 있는 게시글 상세 조회 기능의 dto와도 형태가 거의 비슷해서 이름을 명확히 해주지 않으면 헷갈릴 수 있겠네요. 원복 하겠습니다.

2023-07-31 15:01 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostOptionRequest.java
> +        String imageUrl
위의 맨 처음 피드백에 대한 답변으로 대신하겠습니다.

2023-07-31 15:01 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostRequest.java
> +        @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
@JsonFormat 가 있는지도 몰랐네요. 혹시나 하고 DB를 살펴보니 현재 분까지만 적용되는 것이 작동 안되는 것으로 확인 되었어요. @DateTimeFormat도 날짜 시간 형식으로 변환되긴 하지만 @JsonFormat를 사용하니까 분 뒤엔 0으로 제대로 처리되는 모습을 볼 수 있었네요.

조금 알아보고 결론부터 말하자면,

Post 요청과 ResponseBody 같이 Json 형식으로 주고받을 땐 @JsonFormat을, 
@ModelAttribute와 @RequestParam 과 같은 Get 요청시엔 @DateTimeFormat을 사용하라고 합니다.

이유는 @JsonFormat은 Jackson이 관리하고 @DateTimeFormat은 스프링이 관리하는데, Jackson은 스프링의 어노테이션인 @DateTimeFormat을 전혀 알지 못합니다. 문제는 Json 변환은 Jackson이 관리하는데, 이렇게 되면 Json 데이터를 주고 받을 땐 @JasonFormat이 우선순위를 가질 수밖에 없다고 하네요.

그리고 @JsonFormat은 Jackson에 의해 돌아가기 때문에 Json 데이터 변환이 아니면 동작하지 않습니다.

정확하고 자세한 원리는 좀 더 파헤쳐봐야 겠지만, 우선 이 정도의 특성을 들 수 있을 것 같습니다.

2023-07-31 15:01 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/entity/PostContentImages.java
> +        final String contentImageUrl = ImageUploader.upload(contentImage);
동의합니다. 수정해보겠습니다.

2023-07-31 15:02 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
> +        final String imageUrl = absolutePath + "/images/" + image.getOriginalFilename();
1.  확인해본 결과 OS에 따라 절대경로를 가져와주기 때문에 서버에서 지정된 워크 스페이스를 통해 저장해주는 것 같습니다.
2.  실험을 해봐야 알 것 같습니다. 일단 폴더를 생성해주지 않고 해보기 위해, 폴더를 자동으로 만들어주는 코드는 구현하지 않겠습니다. 실험 끝난 뒤에 혹시나 에러가 나는 것을 발견하면 그때 바로 구현해서 다시 배포하도록 하겠습니다.

2023-07-31 15:03 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/util/ImageUploader.java
> +        }
이미지 저장이 실패했다는 건 결국 전달값이 잘못되었다는 소리니까 BadRequestException 예외를 던지는 것으로 수정해볼게요.

2023-07-31 15:03 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +@RestControllerAdvice(basePackageClasses = PostController.class)
아니 이거 되돌려 놓는다는게...ㅋ

2023-07-31 15:10 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/entity/PostContentImage.java
> +public class PostContentImage {
그러게요. 왜 놓쳤을까요... (´。＿。｀)

2023-07-31 15:25 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +                .map(DefaultMessageSourceResolvable::getDefaultMessage)
이건 다즐이 구현한 코드를 메서드 참조로 개선한 거긴 한데, 

공식 문서에 따르면,

일단 DefaultMessageSourceResolvable 클래스가 구현하고 있는 인터페이스인 MessageSourceResolvable부터 공식문서를 찾아보면,
MessageSourceResolvable 인터페이스는 MessageSource에서 메시지 확인에 적합한 개체에 대한 인터페이스입니다. 즉, Spring의 자체 유효성 검사 오류 클래스들은 이 인터페이스를 구현합니다. (ObjectError, FieldError 등등이 상속받고 있는 DefaultMessageSourceResolvable 가 구현함)

DefaultMessageSourceResolvable 클래스는 Spring의 MessageSourceResolvable 인터페이스를 구현한 클래스로, org.springframework.context.MessageSource를 통해 메시지를 해결하는 데 필요한 모든 필수 값을 저장하는 쉬운 방법을 제공합니다.

위의 코드를 잠깐 살펴보면, getBindingResult() 를 통해 BindingResult를 가져오고, getAllErrors()로 몇 개의 에러가 터졌는지에 따라 ObjectError를 그만큼 갖고 오게 됩니다. 여기서 ObjectError는 DefaultMessageSourceResolvable 클래스를 상속받고 있는데, DefaultMessageSourceResolvable 의 getDefaultMessage 메서드를 통해 예외 메시지들을 손쉽게 가져오게 됩니다.

예를 들어, @Valid 유효성 검증에서 여러개의 유효성 검증에 걸린다면, 그 걸린 예외 들의 메시지들을 전부 가져오게 됩니다.

2023-07-31 15:44 UTC, tjdtls690 commented on backend/images/testImage1.PNG
이 이미지는 PR 보낼 때 Repository에 images 경로가 없어서 자꾸 깃헙 액션에서 gradle 테스트 에러가 뜨더라구요. 그래서 images 경로를 추가하기 위해 push한 이미지입니다.

2023-08-01 03:52 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostRequest.java
> +        String imageUrl,
프론트에서 공통된 형식을 사용하기 위한 필드인 것 같네요 .. 🥲

> 혹시 프론트에서 imageUrl을 보내더라도 백에서 imageUrl을 없애고 안받아줘도 문법적으로 에러 안뜨고 괜찮을까요? 그러면 걍 지워버리고 싶긴 한데...

2023-08-01 04:05 UTC, woo-chang approved these changes
수고하셨습니다 아벨 🙇🏻‍♂️
크게 수정할 사항은 보이지 않는 것 같아 approve 하도록 하겠습니다 :)
제일 신경쓸 부분이 많았던 부분이였는데 꼼꼼히 작성해주셨네요 👍

2023-08-01 04:05 UTC, woo-chang commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +                .map(DefaultMessageSourceResolvable::getDefaultMessage)
@tjdtls690
`ObjectError`가 `DefaultMessageSourceResolver`를 상속받고 있기 때문에 ObjectError에서 **getDefaultMessage**를 호출해도 아벨이 바꾼 코드와 동일한 동작을 할 것 같은데 DefaultMessageSourceResolver로 바꾼 이유가 궁금합니다!

2023-08-01 04:25 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostRequest.java
> +        String imageUrl,
없어도 될 것 같긴 한데 한번 실험해보시죠!

2023-08-01 04:33 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/PostContentImages.java
> +        final String contentImageUrl = ImageUploader.upload(contentImage);
@woo-chang
엄청난 그림과 함께 설명을 해주시니 쏙쏙 이해가 되네요...
무슨 의미로 그런 말씀을 하셨는지 알게되었습니다.
하나 배워갑니다!

2023-08-01 04:34 UTC, jeomxon commented on backend/src/main/resources/application.yml
> +      enabled: true
application.yml에서 ` h2:path: `에 대해서 지정하면 어떨까라는 말이었습니다!

2023-08-01 04:53 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/request/PostRequest.java
> +        String imageUrl,
실험 결과 : 지워도 문제 없는 것으로 판명. 바로 컷

2023-08-01 04:57 UTC, jeomxon approved these changes
리뷰에 대한 꼼꼼한 학습까지!!
고생많으셨습니다 :)
approve해두었으니 몇가지 질문만 마무리하시면 될 것 같네요 ㅎㅎ

2023-08-01 05:12 UTC, tjdtls690 commented on backend/src/main/resources/application.yml
> +      enabled: true
@jeomxon 

무슨 말인지 이해했습니다! path가 default로 /h2-console 가 설정되어 있긴 하더라구요. 가독성을 위해 명시하는 것도 괜찮아 보이네요.

2023-08-01 05:22 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +                .map(DefaultMessageSourceResolvable::getDefaultMessage)
@woo-chang 
인텔리제이에서 자동으로 만들어준게 DefaultMessageSourceResolver였어서 이걸로 한거긴 한데, 사실 뭘로 해도 크게 상관은 없다고 생각합니다. 그래도 비교해보자면 ObjectError가 훨씬 짧아서 가독성이 조금이라도 더 좋을 것 같네요. 수정하겠습니다.

2023-08-01 05:28 UTC, merged