댓글 조회 기능 구현
woowacourse-teams/2023-votogether pull request #182
Opened 2023-08-01 02:27 UTC by woo-chang

## 🔥 연관 이슈

close: #129

## 📝 작업 요약

게시글에 대한 댓글 목록 조회 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 게시글에 대한 댓글 목록 조회 기능을 구현하였습니다.
- `@EntityGraph`를 사용하여 댓글 응답 시 항상 필요한 회원을 fetch join해서 가져오도록 하였습니다.

## 🌟 논의 사항

`LocalDateTime`이 응답으로 반환될 때 `@JsonFormat`을 사용하기에 `yyyy-MM-dd HH:mm`과 같은 형식으로 반환되는데 이걸 깔끔하게 테스트할 수 있는 방법이 떠오르지 않아요 ㅜ 도와주세요 고수분들

2023-08-01 04:41 UTC, tjdtls690 approved these changes
ㅡ 즐 ㅡ

2023-08-01 04:41 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
> +        LocalDateTime updatedAt
```P3```
혹시 어노테이션이 붙은 필드들은 위아래로 개행을 하나씩 넣어주는 건 어떤가요? 제가 지금 그렇게 하고 있어서요.
그게 좀 더 가독성이 있어보여서 그렇게 했습니다.

2023-08-01 04:41 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
> +    }
```Q```
파일을 따로 안빼고 내부 레코드로 만든 이유가 있을까요?

2023-08-01 04:41 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
> +    List<Comment> findAllByPostOrderByCreatedAtAsc(final Post post);
```Q```
댓글을 가져올 땐 어차피 무조건 Member도 사용하게 되니까 @EntityGraph를 설정하신건가요?

2023-08-01 05:05 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
> +        LocalDateTime updatedAt
라인이 너무 길어보일까봐에 대한 염려도 있었는데 개행을 했더니 더욱 깔끔하게 보이는 거 같네요 ㅎㅎ 수정했습니다!

2023-08-01 05:06 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
> +    }
`member` 객체로 묶기 위해 내부에서만 사용되는 클래스라 판단하였습니다!

2023-08-01 05:07 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
> +    List<Comment> findAllByPostOrderByCreatedAtAsc(final Post post);
맞습니다! `@EntityGraph`를 통해 **fetch join**으로 회원도 항상 같이 가져올 수 있도록 하였습니다 :)

2023-08-01 05:13 UTC, jeomxon requested changes
깔끔하게 잘 작성해주셔서 따로 드릴 리뷰가 없네요!
고생하셨습니다~
궁금한 부분이 하나 있어서 request change로 해두었습니다.

2023-08-01 05:13 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
> +        List<CommentResponse> response = postCommentService.getComments(postId);
`P2`
missing final keyword

2023-08-01 05:13 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/dto/response/CommentResponse.java
> +        LocalDateTime updatedAt
이것도 record 컨벤션에 대해서 한번 이야기해봐야겠네요!

2023-08-01 05:13 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
> +            given(memberService.findById(anyLong())).willReturn(MemberFixtures.MALE_20.get());
`Q`
댓글 조회를 할 때 회원에 대한 인증이 필요한가요?
어느 누구든 어떤 게시글에 대한 댓글조회가 가능하지 않나요?
만약 그렇다면 filter에 대한 설정이 필요할 것 같아요.

2023-08-01 05:39 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/controller/PostCommentControllerTest.java
> +            given(memberService.findById(anyLong())).willReturn(MemberFixtures.MALE_20.get());
비회원 게시글 조회, 댓글 조회가 가능한 것을 알아버렸습니다 :) 수정완료했습니다 감사합니다 🙇🏻‍♂️

2023-08-02 01:57 UTC, jeomxon approved these changes
작성하시느라 고생하셨습니다~
신의 코드를 볼 수 있다는 것 자체로 영광이네요^^

2023-08-02 02:02 UTC, merged