게시글 상세 조회 기능 구현
woowacourse-teams/2023-votogether pull request #186
Opened 2023-08-01 14:22 UTC by tjdtls690

## 🔥 연관 이슈

close: #174 

## 📝 작업 요약

게시글에 대한 상세 조회 기능 구현

## 🔎 작업 상세 설명

전달받은 post id에 해당하는 하나의 게시글의 상세 조회 기능을 구현한다.

## 🌟 논의 사항

Post의 Dto 클래스들을 패키지를 좀 나누어서 정리해봤는데, 다들 어떠신지 궁금합니다

2023-08-02 02:13 UTC, woo-chang requested changes
수고하셨습니다 아벨 🙇🏻‍♂️
검증 관련하여 커멘트 남겨두었습니다!
확인 부탁드릴께요 :)

2023-08-02 02:13 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
> +        return post.getPostCategories().getPostCategories().stream()
`P3`
한 라인에는 `.` 1개만 있도록 개행을 주는건 어떨까요?!

2023-08-02 02:13 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
> +        return post.getPostOptions().getPostOptions().stream()
`P3`
`ditto`입니다!

2023-08-02 02:13 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`P1`
상세 조회는 게시글 투표 정보를 모두 확인할 수 있고, 게시글 작성자만 확인할 수 있는 것으로 알고 있습니다 😃

해당 게시글의 작성자인지에 대한 검증이 필요할 것 같아요 :)

2023-08-02 02:39 UTC, jeomxon requested changes
삽자루 형님 코드 작성하시느라 불철주야 고생이 많으십니다 :)
사소한 코멘트 남겨두었습니다! 확인 부탁드릴게요 ㅎㅎ

2023-08-02 02:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +            @Auth final Member loginMember
`P2`
리졸버로 받아오는 멤버 변수에 대한 네이밍에 대한 통일이 필요할 것 같아요!

2023-08-02 02:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
> +    }
`Q`
Record에서는 toString이 자동으로 적용되는 것으로 알고 있는데,
마지막에 개행을 추가하기 위해서 직접 override해주신 걸까요?

2023-08-02 02:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostOptionDetailResponse.java
> +        long optionId,
`Q`
저번에는 코드레벨에서도  Wrapper type를 사용하는 것을 선호한다고 하셨는데,
이번 pr에서는 전반적으로 Primitive type을 사용하신 이유가 있을까요?

2023-08-02 02:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +            throw new BadRequestException(PostExceptionType.NOT_VOTER);
`P2`
Not Voter라는 네이밍이 실제 예외상황에 대한 의미와 적절하지 않은 것 같아요.
현재는 투표자가 아니다!라는 뜻으로 밖에 해석이 안됩니다 ㅠㅠ

한글로 적어주신 메시지를 대신할 수 있는 직관적인 이름이 어떨까요?
`게시글 작성자라서 투표를 할 수 없다`라는 의미가 포함되면 좋겠어요.

2023-08-02 02:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +    private boolean contentImagesPresent(final List<MultipartFile> contentImages) {
`P3`
굳이 메서드 분리를 하지 않아도 될 것 같아요!
개인적으로는 오히려 복잡도가 증가하는 것 같아요.

2023-08-02 02:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +        return !Objects.isNull(contentImages) && !contentImages.isEmpty();
`Q`
`contentImages != null`로 나타낼 수도 있을텐데 이렇게 작성하신 이유가 있을까요?
그리고 null에 대한 것을 좀 더 상위 계층에서 확인할 수는 없나요?

2023-08-02 05:37 UTC, aiaiaiai1 reviewed
고생하셨습니다 아벨~
질문 한개 남겨드렸는데 확인해주시면 감사하겠습니다!

2023-08-02 05:37 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/dto/response/PostDetailResponse.java
> +        }
`Q`
StringBulider를 사용하신 이유가 게시글에 사진이 여러개 추가됬을때 url을 이어서 추가해주기 위함인가요??

2023-08-02 06:29 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
> +        return post.getPostCategories().getPostCategories().stream()
음... 생각해보면 인텔리제이에서도 개행을 해주면 오른쪽에 어떤 값이 튀어나오는지 알려주는 형식이니, 개행을 해주는 것이 코드의 흐름을 파악하는 데에 도움이 될 수 있겠네요. 전 stream() 메서드를 기준으로 개행을 하나씩 시작해주는 것이 습관이 되어있었습니다. stream의 시작점이 어딘지 한 눈에 보이게 하려고 했던 것 같아요. 수정하겠습니다.

2023-08-02 06:29 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
생각해보니 투표한 사람들도 상세 조회는 하지 못했었군요. 수정하겠습니다.

2023-08-02 06:29 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +            @Auth final Member loginMember
동의합니다. 다시 보니 member로 통일하는 것이 훨씬 깔끔해보이네요.

2023-08-02 06:29 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostDetailResponse.java
> +    }
그러게요. 생각해보니 record는 tostring을 재정의 해줄 필요가 없었네요. 바로 컷 하겠습니다.

2023-08-02 06:30 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/response/detail/PostOptionDetailResponse.java
> +        long optionId,
저번에 다즐과 피드백을 주고 받으면서 페이징에 대한 부분에서 원시 타입을 쓰는게 어떻겠냐는 제안이 나왔고, 거기서 잘못된 값이 오면 예외를 터뜨리지 말고 0을 줘서 첫번째 페이지를 보여주는 것이 더 합리적이겠다는 판단을 내렸습니다.

그런데 페이징 관련 변수만 원시타입으로 바꿔 준다는 것이, 다른 브랜치로 넘어와서 id들에도 원시 타입을 적용하는 실수를 저지른 것 같네요.

다시 원복하려고 합니다!

2023-08-02 06:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +            throw new BadRequestException(PostExceptionType.NOT_VOTER);
동의합니다. 더 직관적인 이름으로 개선하겠습니다.

2023-08-02 06:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +    private boolean contentImagesPresent(final List<MultipartFile> contentImages) {
그런가요? 그냥 저걸 메서드로 묶어서 메서드 이름을 contentImages가 있는가? 라는 이름을 지어줘서 분리해주면 contentImages가 있는지 판별하는 메서드라는 것을 더 빨리 알 수 있다고 생각했었습니다.

분리를 안한다면 뭔가 1. null인지 체크하고 -> 2. 비어있는지 확인하네? -> 그러면 contentImages가 있는지 따지는 코드구나! 

이런식으로 생각을 몇 단계 거쳐야 하는 번거로움이 더 있을 것 같아서요.
지금의 이름에서 is를 앞에 붙여서 isContentImagesPresent 라고 지어주면 더 보기 편하지 않을까 생각합니다. 어떠신가요

2023-08-02 06:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +        return !Objects.isNull(contentImages) && !contentImages.isEmpty();
여기 다시보니까 isNull에 느낌표를 붙이는 것이 아닌, nonNull메서드를 썼어야 했는데 제가 실수 했네요.

!= 대신 nonNull메서드를 쓰는 이유는, 사실 2가지중 어떤 것을 써도 별 상관 없다고 생각하지만 이왕이면 이미 라이브러리로 제공해주고 있는 메서드들을 쓰는 습관을 들이는 것이 더 좋을 것이라고 생각합니다.

간지의 이유도 조금 포함되어있습니다. （*゜ー゜*）

그리고 null 체크 로직의 위치는 컨트롤러에서 하기엔 역할이 어색해지거나 if문을 써야하고, 서비스에서 하기에도 null 체크 메서드를 하나 더 만들어서 굳이 그 메서드를 거쳐가게 해야되는 번거로움이 더 생길 수 있다는 생각이 들었습니다. 그래서 도메인에서 해당 데이터가 비어있는지 확인하면서 같이 체크해주는 것이 더 자연스럽다고 생각했습니다.

2023-08-02 06:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/dto/response/PostDetailResponse.java
> +        }
그런 건 아닙니다. 만약 이미지가 안 오면 빈 문자열, 오면 이미지 Url을 꺼내려고 했습니다. 그 과정에서 String을 +해주는 형식으로 하게 되면, String 은 불변 객체이기 때문에 성능면에서 불리하다고 생각되어 StringBuilder를 사용하게 되었습니다.

2023-08-02 08:39 UTC, woo-chang approved these changes
수고하셨습니다 아벨 🙇🏻‍♂️
제가 확인하고자 했던 부분은 다 확인한 것 같아
approve 하도록 할께요 :)

2023-08-02 09:07 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +    private boolean contentImagesPresent(final List<MultipartFile> contentImages) {
좋아요 :) 이 부분은 정답이 없다고 생각해서 편하대로 하시면 될 것 같아요 ㅎㅎ

2023-08-02 09:12 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +        return !Objects.isNull(contentImages) && !contentImages.isEmpty();
nonNull도 내부적으로는 !=로 사용되고 있네요 ㅎㅎ
그렇다면 실제로 null을 체크하기 위해 함수를 타고타고 들어가야할텐데,
스택에 함수 호출이 쌓이는 부분은 어떻게 생각하시나요?

2023-08-03 02:10 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +        return !Objects.isNull(contentImages) && !contentImages.isEmpty();
전 개인적으로 스택에 함수 호출이 몇개 더 쌓이는 것은 크게 상관없어 보입니다! 만약 해당 메서드의 내부 구현을 봐야만 이해가 가능한 코드라면 문제가 되겠지만, nonNull 이라는 메서드 명만 보고 바로 어떤 코드인지 파악이 가능하다면 좋다고 생각합니다 :)

2023-08-03 02:19 UTC, merged