(비회원) 게시글 목록 조회
woowacourse-teams/2023-votogether pull request #291
Opened 2023-08-08 02:26 UTC by woo-chang

## 🔥 연관 이슈

close: #285

## 📝 작업 요약

비회원일 때 게시글 목록을 조회하는 기능을 구현합니다.

## 🔎 작업 상세 설명

- 여러 가지 필터에 따른 동적 쿼리를 처리하기 위해 `Querydsl`을 적용하였습니다.
- `1:N` 관계에서 페이징 처리와 쿼리 최적화를 위해 `default batch fetch size`를 `50`으로 적용하였습니다.
- 테스트에 사용되는 엔티티를 편리하게 생성하기위해 `Persister` 빈들을 추가하였습니다.

## 🌟 논의 사항

- `Querydsl`의 동적 쿼리 생성 시 편리함과 안정성으로 인해 사용하게 되었는데 다른 분들은 어떻게 생각하시는지 궁금합니다!
- 테스트 엔티티 생성을 위해 `Persister` 빈을 만들어 보았는데 이 부분에 대해서도 피드백 주시면 감사합니다 :)

2023-08-08 08:04 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +@Component
`Q`
`@DataJpaTest`설정에서 컴포넌트스캔 필터 설정으로 `@Persister`를 인식하는거 같은데 그럼 `@Component`도 꼭 있어야하나요??
만약 있어야한다면 `@Persister`안에 `@Component`를 추가해서 `@Persister` 하나만 붙여서 작동할 수는 없나요??

2023-08-08 08:14 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +                    .nickname(nickname == null ? RandomStringUtils.random(10, true, true) : nickname)
`Q`
혹시나 혹시나 중복된 닉네임이 저장되어 오류가 생길수 있을 수 있는일은 없나요?

2023-08-08 08:20 UTC, jeomxon requested changes
비회원 게시글 목록 조회도 빠르게 만들어주셨군요..!
대부분의 코멘트는 질문일거예요 ㅎㅎ
QueryDSL은 제가 잘 모르긴하지만 코드만 봐도 이해하기 편하게 되어있네요.
각종 설정파일들이 추가되는 과정에서 모르는 부분에 대해서 질문을 드렸습니다.

TestPersister는 굉장히 신기하네요.
적용된다면 편하게 사용할 수 있을 것 같다는 생각이 듭니다.
코드 작성하시느라 고생하셨습니다! 많이 배우고 갑니다.

2023-08-08 08:20 UTC, jeomxon commented on backend/src/test/java/com/votogether/test/persister/VoteTestPersister.java
> +    }
`P3`
개행이 필요해보입니다.

2023-08-08 08:20 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +            System.out.println(postResponse.createdAt());
`P2`
실수로 넣으신거... 맞죠?

2023-08-08 08:20 UTC, jeomxon commented on backend/src/test/java/com/votogether/test/persister/Persister.java
> +public @interface Persister {
`Q`
이 어노테이션은 왜 필요한가요?

2023-08-08 08:20 UTC, jeomxon commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +public class MemberTestPersister {
`P3`
신기하네요...
TestPersister라는 suffix를 가진 클래스들은 내부 builder를 통해 생성해주고 save까지 해주는 역할을 담당하는 것 같은데 맞나요?
이렇게하면 테스트 메서드 내부에서의 중복 코드를 상당히 줄일 수 있겠군요.
처음에 이해하는데 시간이 조금 걸렸지만 이해하고나니 굉장히 좋은 방법인 것 같네요 :)
혹시 제가 제대로 이해하지 못한 것처럼 보인다면 한번 설명 부탁드릴게요!

2023-08-08 08:22 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +    public final class MemberBuilder {
`Q`
`Member`클래스에 있는 `@Bulider` 와 다른건가요??

2023-08-08 08:26 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +        for (final PostResponse postResponse : result) {
`P2`
`final` 키워드가 붙어있어요~

2023-08-08 08:28 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +                () -> assertThat(result.get(1).voteInfo().options().get(1).voteCount()).isEqualTo(4)
`P2`
같은걸 검증하고있어요~

2023-08-08 08:35 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +
`P3`
반복문이 많아서 살짝 헷갈리는데 작성자와 투표자를 분리하고 명시해주면 테스트코드를 이해하는데 수월할거같습니다!

2023-08-08 08:45 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
> +        }
테스트가 굉장히 꼼꼼하시군요.. 감탄하고갑니다 👍

2023-08-08 13:03 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
> +    public static PostResponse forGuest(final Post post) {
맞습니다! 정적 팩터리 네이밍 컨벤션도 좋지만, 의도를 드러내는 네이밍도 중요하다고 생각했습니다 :)

2023-08-08 13:15 UTC, woo-chang commented on backend/src/main/resources/application.yml
> +        default_batch_fetch_size: 50
해당 사이즈를 너무 작게 작으면 설정하기 전과 비슷하게 쿼리가 많이 나가고 사이즈를 너무 크게 잡으면 너무 많은 데이터를 가지고 와서 많은 리소스를 차지하기에 적절한 값으로 설정하는 것이 중요합니다.

제가 `50`으로 설정한 이유는 현재 저희 기획을 바탕으로 설정한 값입니다. 저희는 페이징 처리 시 10개의 게시글을 가져옵니다. 각각의 게시글은 최대 5개의 옵션을 가질 수 있기에 50으로 설정하면 10개 게시글에 대한 옵션을 모두 가져올 수 있고 총 50개 옵션에 대한 투표를 모두 가져올 수 있습니다. 그렇기에 50으로 설정하게 되었습니다 :)

2023-08-08 13:19 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/persistence/OrderByNull.java
> +public class OrderByNull extends OrderSpecifier {
우선 `OrderSpecifier`는 `Querydsl`에서 제공하는 클래스로, 정렬 조건을 나타내는데 사용됩니다. 어떤 필드에 대해 어떤 순서로 정렬할지 정의하는 역할을 수행합니다!

https://jojoldu.tistory.com/477

해당 클래스는 위의 링크를 참고하여 생성한 클래스입니다! Querydsl에서는 order by null 구문에 대해 지원하고 있지 않기 때문에 `null`을 넣게 되면 제대로 동작하지 않습니다. 그렇기에 Querydsl에서 공식적으로 권장하는 `NullExpression.DEFAULT` 값을 null 대신 제공하도록 하는 클래스라고 이해하시면 될 것 같습니다 :)

2023-08-08 13:20 UTC, woo-chang commented on backend/src/test/java/com/votogether/RepositoryTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Persister.class))
`@DataJpaTest`에서는 `Jpa`와 관련된 빈들만 등록하게 되는데, 해당 필터 설정을 통해 테스트에서 사용되는 `@Persister` 어노테이션이 붙은 컴포넌트를 찾아서 빈으로 등록하도록 지정하였습니다!

2023-08-08 13:24 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +            System.out.println(postResponse.createdAt());
레전드 에러 발견해주셨네요 감사합니다 🙇🏻‍♂️

2023-08-08 13:25 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/persister/Persister.java
> +public @interface Persister {
어노테이션을 사용하여 테스트에 사용되는 엔티티를 저장하는 객체임을 명시하고자 어노테이션을 생성하였습니다!

2023-08-08 13:26 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +public class MemberTestPersister {
정확히 이해하셨습니다! 엔티티 각 필드의 값은 중요하지 않고 저장된 데이터 개수만 필요한 경우 `xxxPersister.builder().save()`만 하더라도 연관관계 모두 반영해서 저장하도록 구현하였습니다 :)

2023-08-08 13:27 UTC, woo-chang commented on backend/build.gradle
> +//End Querydsl
무슨 기술이든 초기 설정하는게 제일 어려운 것 같아요 🥲

2023-08-08 13:27 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/PostOptionResponse.java
> +                post.isClosed() ? ((double) postOption.getVoteCount() / post.getTotalVoteCount()) * 100 : HIDDEN_COUNT
삼항 연산자 .. 반항 .. 위기를 기회로 ..

2023-08-08 13:30 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/PostResponse.java
> +    }
`Response`도 클라이언트한테 전달하는 데이터가 같다고 중복이 아니라 진짜 중복인지 확인 후 사용해야합니다. 변화가 발생했을 때 동일한 변화가 응답에도 발생한다면 그때 완전한 중복이라고 볼 수 있듯 회원 조회 로직과 비회원 조회 로직은 역할이 다르다고 생각합니다.

또한 내부적으로도 회원 조회로직에는 내가 투표한 글에 대해서도 결과를 볼 수 있지만, 비회원은 투표를 할 수 없기에 이를 별도로 처리해줘야 합니다. 비슷한 로직이라고 해당 로직 내부에서 회원/비회원 분기 처리하면 해당 메서드의 복잡도가 커져서 유지보수 어렵게 만드는 요인이 됩니다. 그렇기에 메서드를 분리해서 역할을 분리하였고, 추후에 있을 변화에도 유연하게 대처할 수 있도록 하였습니다 :)

2023-08-08 13:41 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
> +    List<Post> findAllByClosingTypeAndSortType(
`Querydsl`에서는 `Spring Data JPA`의 `Page`나 `Slice`와 같은 페이징 처리를 위한 객체를 직접 반환하는 기능을 제공하지 않습니다! 직접 만드는 방법도 존재하지만, 현재는 Page, Slice 클래스에서 제공하는 정보를 활용하고 있지 않기에 `List`로만 반환하더라도 괜찮을 것 같은데 어떻게 생각하시나요?!

2023-08-08 13:42 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                return OrderByNull.DEFAULT;
https://github.com/woowacourse-teams/2023-votogether/pull/291#discussion_r1287108378

동일한 내용인 것 같아 링크로 대체하겠습니다 ㅎㅎ

2023-08-08 13:46 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +@Component
`xxxRepository`와 같은 빈들을 주입받기 위해 빈 등록이 필요합니다!

말씀해주신 것처럼 `@Persister`안에 `@Component`를 추가해서 사용하면 중복을 줄일 수 있었네요 :)
꼼꼼한 리뷰에 배워갑니다 감사합니다 🙇🏻‍♂️

2023-08-08 13:48 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +                    .nickname(nickname == null ? RandomStringUtils.random(10, true, true) : nickname)
중복된 닉네임이 발생할 가능성은 존재합니다 🥲

하지만 실제 운영에 사용되는 코드도 아니고 메 테스트마다 롤백되기에 최대한 확률적으로 오류가 발생하지 않도록 설정하였습니다! 혹시 중복없이 랜덤값을 무한히 만들어낼 수 있는 방법이 있을까요?!

2023-08-08 13:49 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +    public final class MemberBuilder {
테스트 시 사용되는 엔티티를 편리하게 만들어내기 위한 빌더입니다!

이를 통해 테스트에서 엔티티를 만들어 내기 위한 중복된 코드를 줄일 수 있게 만들어 보았습니다 :)

2023-08-08 13:50 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +        for (final PostResponse postResponse : result) {
불필요한 출력문이 있어서 삭제하도록 하였습니다 :)

2023-08-08 13:50 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +                () -> assertThat(result.get(1).voteInfo().options().get(1).voteCount()).isEqualTo(4)
매의 눈 .. 너무 꼼꼼하게 리뷰해주셨네요 감사합니다 🙇🏻‍♂️👍

2023-08-09 01:53 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                .where(deadlineEq(postClosingType))
지금보니 제 질문이 잘못되었군요..ㅎㅎ
QueryDSL을 사용하기 위해서는 항상 구현체를 만들어주어야한다고 생각하면 되겠군요.
그렇다면 기존에 PostRepository를 사용하지 않고 따로 PostCustomRepository를 만들어서 사용하신 이유도 알 수 있을까요?

2023-08-09 01:55 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
> +    List<Post> findAllByClosingTypeAndSortType(
맞습니다 사실 `slice`의 기능을 사용할 일이 없는것 같더라고요 `List`로도 충분한것 같습니다!

2023-08-09 01:56 UTC, jeomxon commented on backend/src/test/java/com/votogether/RepositoryTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = Persister.class))
아 그래서 Persister어노테이션에 다른 기능이 없었군요.
단순히 식별자의 느낌으로 사용하는 것이라고 이해하면 되겠네요!

2023-08-09 01:59 UTC, jeomxon commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +@Component
레전드... 한수 배웁니다

2023-08-09 02:12 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/test/persister/MemberTestPersister.java
> +                    .nickname(nickname == null ? RandomStringUtils.random(10, true, true) : nickname)
UUID...??

2023-08-09 02:16 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/persistence/OrderByNull.java
> +public class OrderByNull extends OrderSpecifier {
설명 감사합니다 ㅎㅎ
QueryDSL의 order by null구문을 만들어서 contributor가 되어주십쇼...

2023-08-09 02:18 UTC, jeomxon approved these changes
리뷰 반영해주시느라 고생하셨습니다!
덕분에 많이 배워갑니다~
저도 QueryDSL을 자유자재로 쓸 수 있는 그 날이 올때까지...
정진!

2023-08-09 02:23 UTC, aiaiaiai1 approved these changes
다즐 친절한 답변 감사합니다!
리뷰반영 고생하셨어요~
테코톡도 파이팅~

2023-08-09 04:06 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/persistence/OrderByNull.java
> +public class OrderByNull extends OrderSpecifier {
좋은데요 한번 해보고 싶은 첼린지이긴 하네요 ㅎㅎ

2023-08-09 08:28 UTC, jeomxon approved these changes
카테고리 추가 좋습니다!
불필요한 클래스가 보여서 확인 부탁드릴게요~

2023-08-09 08:28 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/category/exception/CategoryExceptionType.java
> +    }
`P2`
이 클래스는 필요 없을 것 같아요!

2023-08-09 08:28 UTC, aiaiaiai1 reviewed
카테고리 필터링 굿굿
간단하게 질문 남겼습니다..!

2023-08-09 08:28 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepository.java
> +            final Long categoryId,
`Q`
`categroy`가 아닌 `categoryId`로 파라미터로 받은 이유가 궁금합니다!

2023-08-09 08:28 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                )
`Q`
`where`에서 여러 조건을 `,`로 연결하면 `.and`(and조건)와 동일하게 되는건가요??

2023-08-09 08:28 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/repository/PostCategoryRepository.java
> +}
`Q`
해당 레파지토리를 만들어야
`import static com.votogether.domain.post.entity.QPostCategory.postCategory;`
를 통해 postCategory를 사용할 수 있게 되는건가요?!

2023-08-09 08:42 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                )
네 맞습니다 👍

2023-08-09 09:01 UTC, merged

2023-08-09 11:03 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/category/exception/CategoryExceptionType.java
> +    }
저도 비회원 구현 안했으면 그냥 사용했겠거니하고 넘어갔을텐데,
로직이 비슷하다보니 우연히 보이더라구요 ㅎㅎ
고생하셨습니다 다즐 :)
내일 테코톡 파이팅!