내가 쓴 게시글 목록 조회 기능
woowacourse-teams/2023-votogether pull request #295
Opened 2023-08-08 14:52 UTC by aiaiaiai1

## 🔥 연관 이슈

close: #289 

## 📝 작업 요약

내가 쓴 게시글 목록 조회 기능 구현

## 🔎 작업 상세 설명

회원 본인이 작성한 게시글 목록 조회 기능을 구현했습니다.
다즐이 비회원 게시글 목록 조회에서 구현하신 QueryDSL 쿼리코드와 설정코드를 똑같이 추가하여 구현하였습니다.

## 🌟 논의 사항

다즐의 비회원 게시글 목록 조회가 머지되면 충돌 해결하여 후에 머지 할거같습니다.

2023-08-09 08:16 UTC, woo-chang requested changes
수고하셨습니다 루쿠 🙇🏻‍♂️
잘 작성해주신 것 같습니다 👍
소소한 질문과 커멘트 남겨두었으니 확인 부탁드릴께요 :)

2023-08-09 08:16 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
> +            Thread.sleep(10);
`P1`
`Thread`를 `sleep` 시키는건 큰 비용이 드는 작업이라고 생각해요 :)

생성 시간 순으로 정렬하는 테스트에서 제대로 정렬되지 않아서 해당 코드를 사용했다고 생각해요! 저도 제대로 정렬되지 않아서 이유를 찾아보니 이전에 `datetime(6)`으로 바꿔놨던 코드가 다시 `datetime(2)`로 변경되어있더라구요.

다시 6으로 변경하였더니 `Thread.sleep` 없이 정상적으로 동작하였습니다! 루쿠도 변경해보는건 어떨까요?!

2023-08-10 04:55 UTC, jeomxon approved these changes
코드 작성하시느라 고생하셨습니다~
수정 사항이 거의 없어보여서 approve하겠습니다!

2023-08-10 04:55 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +                .when().get("/posts/me")
`P3`
```suggestion
        List<PostResponse> result = RestAssuredMockMvc
                .given().log().all()
                .param("page", 0)
                .param("postClosingType", PostClosingType.PROGRESS)
                .param("postSortType", PostSortType.LATEST)
                .when().get("/posts/me")
```
given, when, then을 한번에 보여주기에는 이렇게 작성하는 것이 가독성이 더 좋다고 생각해요!
루쿠는 어떻게 생각하시나요?

2023-08-10 04:55 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
> +            assertThat(posts.get(1)).isEqualTo(closedPost_V1);
`P2`
assertAll로 묶어주는 것이 좋아보여요~
이 클래스의 then절은 전부 확인 부탁드릴게요!

2023-08-10 10:57 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/controller/PostController.java
> +            @ApiResponse(responseCode = "400", description = "잘못된 입력으로 실패.")
게시글 조회다 보니 에러가 발생 할 수 있는 상황이 없는 것 같아 삭제 조치하였습니다..!

2023-08-10 10:57 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +                member, postClosingType, postSortType, pageable);
좋아요~

2023-08-10 11:12 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +                .when().get("/posts/me")
좋아요~ 수정하였습니다!

2023-08-10 14:07 UTC, woo-chang reviewed
수정 사항 잘 반영해주셨습니다 👍
한 가지만 더 확인되면 approve 하도록 할께요 :)

2023-08-10 14:07 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +        );
`P2`
내가 쓴 게시글은 투표 결과를 바로 확인할 수 있기에 사람들이 투표한 결과가 응답에 잘 반영되고 있는지에 대한 검증이 필요할 것 같아요! 서비스 테스트에는 해당 기능을 테스트 하는 것이 테스트하는 가장 큰 이유일 것 같습니다 :)

2023-08-11 04:34 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +        );
추가하였습니다~ 근데 그러면 게시물조회와 관련된 모든 api에는 투표 결과에 대해서도 테스트를 해줘야되는건가요?

2023-08-12 07:41 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +        );
저는 확인해주는게 조금 더 안정성 있는 테스트 코드를 만들어주는 것 같아요 😀

2023-08-12 07:42 UTC, woo-chang approved these changes
확인했습니다 수고하셨습니다 ㅎㅎ

2023-08-12 09:24 UTC, merged