(회원) 게시글 검색 기능
woowacourse-teams/2023-votogether pull request #314
Opened 2023-08-09 15:45 UTC by aiaiaiai1

## 🔥 연관 이슈

close: #290 

## 📝 작업 요약

(회원) 게시글 검색 기능 구현

## 🔎 작업 상세 설명

회원으로 키워드를 통해 게시글을 검색하는 기능을 구현했습니다.

## 🌟 논의 사항

현재는 키워드가 제목이나 내용에 포함되면 검색이 이루어지고 키워드에 대해서는 아무런 제약이 없는 상태입니다.
키워드의 글자수를 제한한다던가 혹은 "" 와 같이 빈문자열로 검색했을때를 예외상황으로 봐서 예외로 처리해야할지를 잘 모르겠더라고요. 
검색 방식이나 제약 같은 부분에 대해서 다른분들의 의견은 어떠한지 궁금합니다!

2023-08-10 13:56 UTC, jeomxon requested changes
질문 위주로 코멘트 남겼습니다~
코드 작성하시느라 고생하셨어요 루쿠 ㅎㅎ

2023-08-10 14:16 UTC, woo-chang requested changes
수고하셨습니다 루쿠 🙇🏻‍♂️
`Querydsl`을 금방 잘 사용하시네요 👍
몇 가지 커멘트 남겨두었으니 확인 부탁드릴께요 :)

2023-08-10 14:16 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                .join(post.writer).fetchJoin()
`P3`
한 줄에 점 하나씩 있는 것이 저문의 말처럼 가독성은 더 좋다고 생각합니다 👍

위의 상황에서는 `member`와 조인하는 것을 `fetch join`으로 만든다는 점에서 하나의 맥락인 것 같아 같은 라인에 붙어있는 것이 코드를 이해하기는 더 쉽다고 생각이 들어서 붙여도 괜찮다고 생각하는데 이 부분에 대해서 저문은 어떻게 생각하시나요?!

2023-08-10 14:16 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +
`P2`
해당 기능에도 `Service` 테스트가 없는 것 같아요 :) 이전과 동일하게 검색한 게시글이 마감되었을 때, 투표했을 때, 내가 쓴 게시글일때 투표 결과를 잘 담고 있는지 검증해주는 것이 중요할 것 같아요!

2023-08-10 14:21 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                .join(post.writer).fetchJoin()
P3로 지정했던 만큼 크게 중요한 사안은 아니었습니다!
저도 개인적인 생각일 뿐이고, 메서드 체이닝에 대한 컨벤션이 지금까지 그래왔기에 말씀드렸었습니다.
fetchJoin을 함께 사용하는 것이 말씀을 들어보니 더 맥락을 이해하기 쉬울 것 같기도 하네요!
루쿠가 편하신대로 반영해주시면 좋을 것 같아요~

2023-08-11 12:08 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/repository/PostRepositoryTest.java
> +        @DisplayName("게시글 목록을 키워드를 통해 검색한다.(내용)")
제목 or 내용으로 검색하는건데 중복되서 테스트 하는건 아닐까요,,,?? 일단 추가해보았습니다!

2023-08-12 02:47 UTC, jeomxon approved these changes
코멘트 반영하시느라 고생하셨습니다!
approve할게요~

2023-08-12 07:43 UTC, woo-chang approved these changes
확인했습니다 수고하셨습니다 ㅎㅎ

2023-08-12 10:06 UTC, merged