성별, 나이 수정 기능 구현
woowacourse-teams/2023-votogether pull request #339
Opened 2023-08-11 04:38 UTC by jeomxon

## 🔥 연관 이슈

close: #338 

## 📝 작업 요약

성별, 나이 수정기능 구현했습니다.

## 🔎 작업 상세 설명

없음.

## 🌟 논의 사항

없음.

2023-08-11 04:58 UTC, woo-chang requested changes
수고하셨습니다 저문 🙇🏻‍♂️
깔끔하게 잘 작성해주셨네요 👍
소소한 질문과 커멘트 남겨두었는데 확인부탁드릴께요 :)

2023-08-11 04:58 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/dto/MemberDetailRequest.java
> +public record MemberDetailRequest(
`P3`
```suggestion
@Schema(description = "회원 상세 정보 수정 요청")
public record MemberDetailRequest(
```
불필요한 공백이 들어가있어요 ㅎㅎ

2023-08-11 04:58 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/dto/MemberDetailRequest.java
> +        Integer birthYear
`P3`
```suggestion
        @Schema(description = "성별", example = "MALE")
        Gender gender,
        
        @Schema(description = "출생년도", example = "2000")
        @NotNull(message = "출생년도는 빈 값일 수 없습니다.")
        @Min(value = 4, message = "출생년도는 4자리만 가능합니다.")
        @Max(value = 4, message = "출생년도는 4자리만 가능합니다.")
        Integer birthYear
```
이 부분도 컨벤션으로 얘기하면 좋을 것 같은데 각 필드마다 공백을 주는 것이 어떨까요?

자바 `validation` 어노테이션까지 포함되니 가독성이 떨어지는 부분이 있는 것 같아요!

2023-08-11 04:58 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +    }
`P3`
저희 기획으로는 성별과 출생년도는 한번에 입력되고, 한번 설정하면 수정이 불가능하다는 것으로 알고 있습니다! 따라서 항상 같이 업데이트 될 것 같은데 하나의 메서드로 묶는 방법은 어떻게 생각하시는지 궁금합니다 :)

각각 메서드로 존재한다면 각각 수정이 가능하다는 의도를 내포한다고 생각할 수 있을 것 같아요 🤔
```java
public void updateDetail(final Gender gender, final Integer birthYear) {
    this.gender = gender;
    this.birthYear = birthYear;
}
```

2023-08-11 04:58 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +        }
`P3`
같은 성별과 같은 출생년도로 바꾸는 것이 예외로 볼만한 상황인지에 대한 고민도 해보면 좋을 것 같아요 :)

저문이 예외라고 판단했던 생각의 흐름이 궁금해요 ㅎㅎ

2023-08-11 04:58 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +    public void updateDetails(final MemberDetailRequest request, final Member member) {
`P1`
기획적으로 출생년도와 성별은 한번 입력하고 수정이 불가능한 것으로 알고 있습니다!

이미 출생년도와 성별이 지정되어 있는지에 대한 검증이 필요할 것 같아요 😙

2023-08-11 04:58 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
> +
`P1`
성별, 출생년도가 지정되어 있을 때 검증이 추가된다면 해당 테스트 코드도 추가되면 좋을 것 같아요 ㅎㅎ

2023-08-11 10:10 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/dto/MemberDetailRequest.java
> +        Integer birthYear
동의합니다 수정할게요~

2023-08-11 10:11 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +    }
이 부분도 그냥 별 생각없이 구현했던 것 같은데, 잡아주셔서 감사합니다 ㅎㅎ
말씀해주신 방법으로 수정하는 것이 훨씬 의미있어보이네요~

2023-08-11 10:20 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +    public void updateDetails(final MemberDetailRequest request, final Member member) {
최상단에서 검증해주면 된다는 생각에 여기서 하게된다면 두번의 조회를 통한 중복 검증이 발생하게 되어서 과연 필요할까?에 대해서 생각해봤습니다.
이런 관점에서 봤을 때도 검증이 꼭 필요하다고 생각하시나요?

2023-08-11 10:22 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
> +
위의 리뷰에 적어둔 코멘트에 답을 받고 더 생각해보겠습니다!!

2023-08-11 10:22 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +        }
사실 상위 계층에서 검증이 되어서 올 것 같다는 생각은 들었습니다.
단순히 입력을 받는 상황이라고 가정하고 같은 값으로 수정을 할 때 예외를 발생시킨다면, 불필요한 update를 하지 않을 수 있다는 생각이었습니다.

2023-08-11 10:36 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +        }
제가 질문을 애매하게 적은 것 같네요 🥲

같은 값으로 변경했을 때 사용자가 예외 상황이라고 알려주는 것이 괜찮은가에 대한 질문이었습니다! 해당 상황을 예외로 보게 되면 사용자는 예외 메시지를 확인하게 될 것이고, 예외 상황으로 보지 않고 같은 값으로도 변경 가능 한다면 사용자는 예외 메시지를 확인하지 않게 됩니다.

현재는 수정이 불가능하지만, 수정이 가능한 상황으로 먼저 가정하겠습니다. 저의 짧은 견해로는 성별과 출생년도를 같은 값으로 변경하더라도 문제가 없다는 생각이 들었습니다. 유효한 성별, 출생년도 데이터라면 같은 값으로 바꾸어도 문제되는 상황이 없다고 생각이 들었기 때문입니다 ㅎㅎ

그래서 저문이 예외상황이라고 판단한 근거가 듣고 싶었습니다 ☺️

2023-08-11 10:40 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +    public void updateDetails(final MemberDetailRequest request, final Member member) {
해당 API는 성별, 출생년도가 `null`인 회원도 호출가능하게 해야 수정이 가능할 것 같아요! 그래서 최상단에서 검증하는 로직이 빠져야할 것 같은데 저문이 말한 최상단이 제가 말하는 최상단과 일치하는게 맞을까요?! 🤔

2023-08-11 13:48 UTC, aiaiaiai1 requested changes
고생하셨어요 저문 :)
소소소한 코멘트와 검증관련해서 의견남겨드렸습니다~!

2023-08-11 13:48 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +    private static void validateExistentDetails(final MemberDetailRequest request, final Member member) {
`P2`
`static`이 붙어있어요!

2023-08-11 13:48 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
> +        @DisplayName("출생년도가 4자리가 아니라면 400을 반환한다.")
`P3` 
4444는 4자리라서 `유효하지 않는 출생년도가 아니라면` 은 어떤가요

2023-08-11 13:48 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +    public void updateDetails(final MemberDetailRequest request, final Member member) {
최상단에서 검증하는게 `requestdto`에서 하는 검증인가요?
`requestdto`에서 빈값인지 검증하고 
해당 메서드에서는 회원의 성별, 출생년도가 `null`일때만 수정할 수 있도록 조건을 걸어줘야할거같아요.

--------------------
> 해당 API는 성별, 출생년도가 null인 회원도 호출가능하게 해야 null인 회원이 수정할 수 있을 것 같아요 :)

-> 아니면 argumentResolver에서 성별, 출생년도가 매번 null인지 아닌지 확인하는 것보다 투표하는 메서드에서 성별, 출생년도가 null인 회원은 투표하지 못하게 막는건 어떤것 같나요?

2023-08-11 13:48 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +        }
저도 사용자 입장에서 생각해보면  이게 왜 에러지 라고 생각할 수 도 있을거같습니다
아니면 저문의 의도대로 불필요한 update를 막기위해서 예외를 발생시키지 않고 return으로 통해 update를 안하게끔 할 수도 있을거같아요!

2023-08-12 03:31 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +        }
다들 좋은 의견 감사합니다!
좀 더 생각을 해보고 말씀해주신 것들도 들어보니,
수정 됐을 때 같은 값이면 굳이 예외를 발생시켜줄 필요가 없을 것 같네요.
해당 예외를 null인 상황일 때만 수정할 수 있도록 변경해볼게요~

2023-08-12 03:40 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +    public void updateDetails(final MemberDetailRequest request, final Member member) {
레전드 생각을 하고 있었네요!
다들 의견주셔서 감사합니다
수정해볼게요~

2023-08-12 05:58 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/member/controller/MemberControllerTest.java
> +        @DisplayName("출생년도가 4자리가 아니라면 400을 반환한다.")
꼼꼼한 확인 감사합니다 :)
수정해볼게요~

2023-08-12 07:48 UTC, woo-chang approved these changes
확인했습니다 수고하셨어요 ㅎㅎ

2023-08-12 08:42 UTC, aiaiaiai1 approved these changes
고생하셨습니다 ㅎㅎ 👍

2023-08-12 08:43 UTC, merged