게시글 선택지 투표기능, 투표 수정기능 구현 #36
woowacourse-teams/2023-votogether pull request #47
Opened 2023-07-14 04:51 UTC by aiaiaiai1

## 🔥 연관 이슈

close: #

## 📝 작업 요약

수행할 작업을 1~2줄 사이로 요약해주세요.

## 🔎 작업 상세 설명

주요 기능 및 로직에 관해 설명해주세요.

## 🌟 논의 사항

크루들과 이야기 해보고 싶은 부분을 적어주세요.

2023-07-14 09:03 UTC, jeomxon requested changes
루쿠 작성하시느라 고생하셨습니다 :)
간단한 코멘트 먼저 남겨봤어요~
코드 전반적으로 final 키워드가 빠진 부분들이 보이네요..!
테스트 제외하고 먼저 코멘트 남길게요.

2023-07-14 13:04 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +
객체관점에서 `Post`가 `List<PostOption>`을 가지고 있지 않다는것이 어색하게 느껴졌던게 가장컸고
`Post`에 속하는 여러`PostOption`을 편하게 가져오기위해서 사용했습니다

2023-07-14 13:07 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/controller/VoteController.java
> +            final Member member
파라미터 변수명을 `optionId`로 사용하기엔 불명확한 이름인거 같아 변수명을 `postOptionId`로 짓기위해 속성을 따로 지정했습니다

2023-07-14 13:11 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +                member.getId(), originPostOptionId);
저는 정확한 기준은 따로 없고 인텔리제이에서 한줄이 너무 길어 잘 안보여지게되면 하는거 같은데 저문은 어떤방식으로 개행을 하시나요??

2023-07-14 13:20 UTC, aiaiaiai1 commented
final 키워드 추가했습니다~

2023-07-14 13:22 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +                member.getId(), originPostOptionId);
저도 정해놓은 행 최대 길이 설정이 넘어가면 개행을 하는데,
만약 행 길이가 넘어가서 개행을 하게 된다면 아래와 같은 형식으로 하는게 더 가독성이 좋은 것 같아서 채택하여 사용하고 있어요!
루쿠만의 기준이 있다면 해당 방식을 사용하여 일관성있게 유지하시면 좋을 것 같아요 :)

이 코드 같은 경우에는 행 최대 길이로 설정한 120이 넘지 않고 한 줄로 작성했을 경우도 크게 가독성이 떨어진다는 생각이 들지는 않아요. 루쿠가 편하신대로 일관성만 가져가시면 좋을 것 같네요 ㅎㅎ

```suggestion
        Vote vote = voteRepository.findByMemberIdAndPostOptionId(
                member.getId(),
                originPostOptionId
        );
```

2023-07-15 10:53 UTC, woo-chang requested changes
첫 PR 코드 작성하느라 수고하셨습니다 :)
질문, 의논해보고 싶은 사항에 대해 몇 가지 코멘트 남겨보았습니다!
확인해보시고 답변 달아주시면 감사합니다 🙇🏻‍♂️

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +                .orElseThrow(() -> new IllegalArgumentException("게시글이 존재하지 않습니다."));
예외 처리 방법에 대해서도 같이 얘기해보고 적용해보면 좋을 것 같아요 :)

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = member.vote(post, postOptionId);
`postOption`도 존재하는 옵션인지에 대한 검증이 필요할 것 같아요!

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        member.plusPoint(1);
증가되고 감소되는 포인트는 어디서 관리될지 얘기도 필요할 것 같아요 ㅎㅎ

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +    }
투표를 멤버 객체가 생성하는 것에 대해서는 어떻게 생각하시는지 궁금합니다 🤔

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +            final Long newPostOptionId
여기서도 유효한 투표옵션인지에 대한 검증이 빠져있는 것 같아요!

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = member.vote(post, postOptionId);
해당 게시글에 대한 옵션인지에 대한 확인도 필요할 것 같아요!

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = member.vote(post, postOptionId);
이미 투표한 게시글에 대한 투표인지에 대한 검증도 필요할 것 같아요 :)

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +            final Long newPostOptionId
두개의 옵션이 해당 게시글에 대한 옵션인지에 대한 검증도 필요할 것 같습니다 :)

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = voteRepository.findByMemberIdAndPostOptionId(
기존에 투표한 옵션이 존재하지 않으면 예외 상황으로 볼 수 있지 않을까요?!

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = voteRepository.findByMemberIdAndPostOptionId(
```suggestion
        Vote vote = voteRepository.findByMemberAndPostOption(
```
`Member`, `PostOption` 2개 다 찾은 상태이니 객체를 통해 찾는 방법은 어떨까요? ID로 조회할 때와 객체로 조회할 때는 어떤 차이가 있을까요?

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        vote.changePostOption(postOption);
투표를 수정하는 방법을 사용하셨네요! 기존의 투표를 삭제하고 새로운 투표를 저장하는 방법도 있을 것 같은데 투표를 수정하는 방법을 사용한 이유가 궁금합니다 😃

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +    }
post를 가져와서 post의 메소드를 호출하는 방법을 사용하신 이유가 있으신가요? 서비스 메서드에서 `post.isWriter` 메서드를 호출하는 방법도 있는 것 같아서요!

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    }
해당 방법으로 `PostOption`을 찾게 되면 항상 모든 `PostOption`을 조회하는 쿼리가 먼저 발생하게 될 것 같은데, `PostOptionRepository`를 `id`로 조회하는 방법을 사용하지 않은 이유가 궁금합니다!

2023-07-15 10:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +        return deadline.isBefore(LocalDateTime.now());
`LocalDateTime` 메서드를 잘 활용해주셨네요 👍🏻

2023-07-15 10:53 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
> +    @DisplayName("게시글의 작성자 여부를 확인한다.")
작성사가 같지 않을 때의 테스트도 해보는건 어떨까요? ㅎㅎ

2023-07-15 10:53 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/entity/PostTest.java
> +    @DisplayName("게시글의 마감 여부를 확인한다.")
마감되지 않았을 때도 테스트 해보는건 어떨까요?!

2023-07-16 12:09 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
> +public interface VoteRepository extends JpaRepository<Vote, Long> {
연관관계 편의 메서드를 활용한다는것이 Member.votes를 연관관계 주인으로 해서 Vote레파지토리가 필요없이 
Memeber레파지토리를 통해서 vote의 데이터값이 저정하게끔한다는 말씀이신가요??

2023-07-16 13:11 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    @OneToMany(mappedBy = "post")
`VOTE`가 `POST_OPTION_ID`를 fk로 가지고있어서 참조무결성 제약조건에 걸릴거같은데 VOTE도 같이 지울수 있는방법이 혹시 있을까요??

2023-07-16 16:03 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/controller/VoteController.java
> +
자료 감사합니다~

2023-07-17 07:39 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/controller/VoteController.java
> +    public ResponseEntity<Void> changeVote(
음 ... 일단 한번 소극적으로 검토해보겠습니다

2023-07-17 09:12 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = member.vote(post, postOptionId);
>   해당 게시글에 대한 옵션인지에 대한 확인도 필요할 것 같아요!
`Post` 클래스에서 `postOptionId`를 통해 `PostOption`을 가져올때 검증이 존재합니다!

> `postOption`도 존재하는 옵션인지에 대한 검증이 필요할 것 같아요!
위처럼 검증하게 되면 PostOption 자체가 존재하는지에 대한 검증은 필요가 없을거같은데 어떻게 생각하시나요??

>  이미 투표한 게시글에 대한 투표인지에 대한 검증도 필요할 것 같아요 :)
검증을 추가해보았는데 주어진 파라미터로는 검증하기가 어려워서 살짝 과정이 복잡해지긴했습니다

2023-07-17 09:14 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +    }
저는 맴버가 주체가 되어 투표를 한다고 생각해서 맴버가 투표 객체를 생성하게 한거같아요

2023-07-17 14:02 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +            final Long newPostOptionId
PostOption 리파지토리 추가해서 검증 추가하였습니다!

2023-07-17 14:03 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        Vote vote = voteRepository.findByMemberIdAndPostOptionId(
레파지토리가 컬렉션의 역할을 하는만큼 객체로 파라미터를 받게하니 더 객체지향스러워졌어요~ 👍

2023-07-17 14:09 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/service/VoteService.java
> +        vote.changePostOption(postOption);
처음에 변경감지를 이용하면 기존의 투표를 찾아서 삭제하고 다시 저장하는 과정 없이 
투표를 찾아서 수정만해주면 되겠다라고 생각해서 더 편리하다고 생각했는데요
그러다보니 기존의 투표를 수정할려고하니 vote 객체에 새로운 메서드가 추가되고 투표를 수정할때 검증과정이 투표할때와 동일하게 중복이 되었습니다

2023-07-17 14:11 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +    }
최종적으로 vote객체를 반환하는 메서드 안에서 검증로직들이 들어가게끔 하고 싶었는데 member객체가 아닌 post객체가 vote객체를 반환하도록하니 문제가 해결되었습니다 👍

2023-07-17 14:17 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/Post.java
> +    }
`PostOption`이 `Post`에 속하고 있는지 확인하기위해 만들었었는데
`id`로 조회해서 `PostOption`을 찾는 리파지터리를 만들어 
`id`를 통해 `PostOption`을 찾는 메서드와`Post`객체에서 PostOption이 존재하는지 확인하는 메서드를 분리했습니다

2023-07-18 01:40 UTC, woo-chang approved these changes
검증도 추가되고 전체적으로 코드가 깔끔해진 것 같습니다 👏🏻

많은 고민을 가지고 꼼꼼하게 개발하시느라 수고하셨습니다 🙇🏻‍♂️

2023-07-18 01:47 UTC, jeomxon approved these changes
빠른 진행을 위해서 Approve하겠습니다!
리뷰 반영 + 코드 작성 하시느라 정말 고생하셨습니다 :)

2023-07-18 02:10 UTC, merged