요청, 응답 로그 설정
woowacourse-teams/2023-votogether pull request #481
Opened 2023-08-21 02:54 UTC by woo-chang

## 🔥 연관 이슈

* close: #402

## 📝 작업 요약

요청, 응답에서 발생하는 데이터에 대한 로그를 설정하였습니다.

## ⏰ 소요 시간

15시간
- 요청, 응답 데이터를 읽기 위해 입력 스트림을 사용하면 다시 데이터를 읽을 수 없는데, 이를 해결하는 과정에서 오래 걸렸습니다.

## 🔎 작업 상세 설명

- 일반 `JSON` 요청은 입력 스트림의 바이트를 저장해두고 해당 바이트를 해석해서 사용할 수 있지만, 멀티 파트 요청에서 사용되는 `Part`는 바운더리를 추출하고 파싱하고 다시 `Part`를 만드는 과정이 매우 복잡하기 때문에 이를 저장하고 복원하는 것이 매우 어려운 작업입니다.
- 따라서 멀티 파트 요청의 경우 `Part` 데이터는 로그에서 제외시키도록 하였고, 나머지 요청 흐름에서 발생하는 정보에 대해서만 로그를 남길 수 있도록 하였습니다.

## 🌟 논의 사항

로그 레벨과 사용하지 않는 로그에 대해서는 조금 더 얘기가 필요할 것 같아요 :)

2023-09-29 14:58 UTC, aiaiaiai1 requested changes
으어 코드가 너무 어려워요 ㅓㅏㅏㅏㅜㅡㅏㅜㅏㅓ
전체적으로 코드에 대한 것보다는 로그 출력과 관련해서 간단하게 저의 의견을 남겨보았습니다!
aop구현하시느라 고생하셨어요~

2023-09-29 14:58 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/global/log/context/LogContext.java
> +    }
Q.
여기 클래스에서 메서드가 호출될때마다 스택같은곳에 호출시간을 쌓아놓고 
메서드가 리턴될때 해당 메서드의 실행시간을 계산해서 로그로 출력해주는것 방식은 어떤것 같나요??

2023-09-29 14:58 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/global/log/aop/Logger.java
> +                logContext.totalTakenTime()
Q.
메서드호출이 끝난 시점을 구간기록과 같은 방식으로 로그로 출력하고 있는데 
호출이 끝나는 시점을 로그로 남기는것 보다 해당 메서드가 호출되고 리턴되기까지의 시간을 로그로 남기는게 더 의미있다고 생각이 들었는데 이 방법으로 로그를 남기는건 어떤것 같나요?

2023-09-29 14:58 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/global/util/CorsUtils.java
> +    }
P3
유틸클래스 생성자는 private으로 막아두면 좋을거같아요! + final 클래스까지..?

2023-10-04 11:11 UTC, jeomxon approved these changes
무시무시하고 어려운 AOP를 통해 요청, 응답 로그를 멋지게 구현해주셨군요 👍🏻
작성하시느라 고생 많으셨습니다 다즐 ㅎㅎ

이해하기 어려운 부분이 많아서 코멘트가 거의 질문인 것 같아요...
흐름을 대충은 이해했는데 세부적인 부분까지 이해하기가 정말 어렵네요.

부탁을 하나 드리고 싶은데, 전체적인 흐름을 한번 정리하여 나타내주실 수 있을까요?
추후에 다시 코드를 보면 이해하기 어려울 것 같다는 생각이 들었어요.
이후에 다시 확인할 떄 흐름도 같은 것이 있으면 이해하기 훨씬 수월할 것 같다고 느꼈어요.
추가적으로 질문이 생기면 코멘트 남기겠습니다 :)

2023-10-04 11:11 UTC, jeomxon commented on backend/src/test/java/com/votogether/test/ControllerTest.java
> +
`Q`
어떤 역할을 하나요?

2023-10-05 02:42 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
> +    public FilterRegistrationBean<CorsFilter> corsFilterRegistrationBean() {
개발 환경, 운영 환경에서는 `CORS`를 허용해주는 역할을 하고 있는 `Nginx`를 리버스 프록시 서버로 두고 있기 때문에 애플리케이션 자체적으로 CORS 설정이 필요하지 않습니다!

하지만 로컬에서 `8080` 포트로 스프링 부트 애플리케이션을 실행시키는 경우, 리버스 프록시 서버가 없기 때문에 `localhost:3000`에서 실행되는 프론트 요청에 대해 CORS 에러가 발생하게 되었습니다. 분명히 `CorsRegistry`를 설정했음에도 왜 CORS 에러가 발생하는지 궁금하여 이에 대해 알아보게 되었습니다.

현재 저희는 인증을 위해 `JwtFilter`를 사용하고 있습니다! 클라이언트의 요청이 들어오면 필터 -> 서블릿 -> 인터셉터 -> 핸들러 순으로 요청이 전달되는데, CorsRegistry는 `DispatcherServlet`이 실행시키기 때문에 필터에서 요청이 전달되지 않으면 CORS 에러가 발생하게 됩니다.

현재 JwtFilter에는 `Preflight` 요청에 대한 처리가 되어있지 않아서 토큰이 존재하지 않다는 에러를 발생시키게 되고 CorsRegistry까지 요청이 전달되지 못합니다. 따라서 문제를 해결하기 위해 가장 앞단에 `CorsFilter`를 두어 이에 대한 처리가 가능하도록 설정하였습니다 :)

2023-10-05 02:49 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/aop/PreparedStatementMethodInterceptor.java
> +    public Object invoke(final MethodInvocation invocation) throws Throwable {
같이 얘기를 나눴던 대로 하나의 로직을 합쳐도 괜찮을 것 같다는 생각이 들어요 !

저도 2가지 방법 모두 괜찮은 방법이라고 생각이 들어서, 우선은 그대로 가는 방향이 좋을 것 같아요 ㅎㅎ

2023-10-05 02:55 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/presentation/RequestLogInterceptor.java
> +            log.info("[Web Request START] : [\n{}]", requestLog);
<img width="1306" alt="스크린샷 2023-10-05 오전 11 55 22" src="https://github.com/woowacourse-teams/2023-votogether/assets/78212016/ccf55198-f76e-4983-8295-f064fedfcf40">

훨씬 깔끔하네요 ㅎㅎ 좋습니다 👍

2023-10-05 03:02 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/aop/Logger.java
> +        log.info("[{}]  {}  time={}ms",
<img width="1580" alt="스크린샷 2023-10-05 오후 12 01 21" src="https://github.com/woowacourse-teams/2023-votogether/assets/78212016/d873ec31-82be-4de9-baf0-f1b2650f43f0">

해당 부분도 감싸보았는데 오히려 가독성이 떨어지는 것 같았어요 🥲

2023-10-05 03:42 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/aop/Logger.java
> +                logContext.totalTakenTime()
좋은 방법인 것 같습니다 ㅎㅎ 감사합니다

말씀해주신 방법대로 스택을 이용해서 메서드별 실행 시간을 확인할 수 있도록 구현하였는데, `ms` 단위여서 아주 작은 오차들이 발생하더라구요. 0.01초 단위의 아주 작은 오차들이여서 괜찮을 것 같다는 생각이 들었는데 이 부분에 대해서는 어떻게 생각하시나요?!

2023-10-05 03:45 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/util/CorsUtils.java
> +    }
꼼꼼한 리뷰 좋아요 👍

2023-10-05 03:54 UTC, woo-chang commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-webflux'
운영 환경에서 `error` 레벨의 로그가 남겨지면 즉각 대응이 필요한 상황이기에 이를 바로 알리기 위해 슬랙 알림이 필요하였습니다!

저희는 `Logback`이 아닌 `Log4j2`를 사용하고 있기 때문에 `Logback`의 `SlackAppender` 라이브러리를 사용할 수 없었습니다. `Log4j2`도 `SlackAppender` 라이브러리가 존재하는지 찾아보았으나, 오래된 라이브러리만 존재했고 적절한 라이브러리를 찾을 수 없어서 직접 구현해서 사용하기로 결정하였습니다. 마침 직접 구현해서 사용한 분이 정리한 글이 있어 해당 글을 참고하였습니다.

슬랙 알림을 보내기 위해 HTTP 통신이 필요한 상황에서 3가지의 선택지가 존재했습니다.
- `RestTemplate`
- `WebClient`
- `FeignClient`

RestTemplate, FeignClient는 기본적으로 Blocking 방식으로 동작하기 때문에 슬랙 알림을 위해 제어권을 뺏기게 되는 상황으로 성능에 영향을 줄 수 있습니다. 알림은 비동기로 처리해도 되는 로직이기에 비동기를 지원하는 WebClient의 선택이 필요했고, 이를 사용하기 위해 `webflux` 의존성을 추가하게 되었습니다 :)

2023-10-05 03:55 UTC, woo-chang commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-webflux'
기존에 존재하는 `web` 의존성과 충돌이 나지 않을까라는 생각도 했던 것 같아요. 2개의 의존성이 모두 존재하는 경우, 스프링 부트 애플리케이션은 `SERVLET` 방식을 선택하기 때문에 `Netty` 서버가 아닌 `Tomcat` 서버로 동작하게 되는 것을 문서를 통해 확인할 수 있었고, Tomcat 서버로 가동하면서 WebClient 기술만 사용할 수 있다는 것도 알게 되었습니다!

2023-10-05 03:57 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/config/WebMvcConfig.java
> +        config.setMaxAge(6000L);
로컬에서만 사용되는 기능이기 때문에 큰 의도없이 설정한 값입니다!

해당 값을 어느 정도로 하면 좋을까요? 🤔

2023-10-05 03:58 UTC, woo-chang commented on backend/src/main/resources/log4j2-local.xml
해당 로거를 제거할 때 추후에 필요한 상황이 있지 않을까라는 생각에 주석으로 남겨두었던 것 같습니다.

현재 로그 기능이 정상적으로 동작하는 것을 확인했고 아직 추가적인 로그 데이터가 필요하지 않은 상황이라고 판단되기 때문에 주석 처리되어있는 로거들을 제거하는 방향으로 수정하였습니다 !

2023-10-05 04:16 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/context/LogContextHolder.java
> +@RequestScope
우선 요청마다 데이터가 구분되어야 하는 상황에서 해당 어노테이션 사용을 고려해볼 수 있을 것 같아요! 이와 비교해볼 선택지는 `ThreadLocal`이 있을 것 같습니다.

톰캣은 HTTP 요청을 처리하기 위해 요청 당 1개의 스레드를 사용하기에 2개 다 괜찮은 선택지라고 생각되지만, `ThreadLocal`는 아래와 같은 단점이 존재합니다.
- ThreadLocal에 저장된 변수 값들이 스레드가 다시 재사용될 때까지 메모리에 남아있을 수 있기 때문에 사용이 끝난 ThreadLocal 값은 적절히 제거가  필요하다.

`@RequestScope`는 요청동안 유지되는 Bean이고 요청이 종료되면 자동으로 메모리에서 할당이 해지되는 값이기 때문에 위와 같은 문제를 걱정할 필요가 없기에 해당 방법을 선택해서 구현하게 되었습니다.

단점이라고 한다면 아래의 단점이 존재할 것 같아요 !
- **요청마다 `Bean`이 생성되고 소멸하는 오버헤드가 존재한다.**
  - Bean 내부에 많은 것들을 포함하고 있으면 오버헤드가 큰 문제가 발생할 수 있겠지만 현재는 몇 개의 작은 필드들만 저장하고 있기 때문에 큰 오버헤드는 들지 않을 것이라 생각해요 :)

2023-10-05 04:24 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/aop/QueryCountAop.java
> +@Aspect
`@Configuration` 어노테이션과 같이 `AOP`에 대한 행위를 담고 있는 클래스임을 알려주는 어노테이션입니다 !

해당 클래스 내부에는 어떤 행위를 수행할지에 대한 `Advice`와 어떤 곳에 행위를 적용할지에 대한 `Pointcut` 정보가 담겨있습니다 :)

2023-10-05 04:26 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/aop/LogAop.java
> +    @Pointcut("@within(org.springframework.web.bind.annotation.RestController)")
`Pointcut`을 설정하여 `AOP`를 통해 수행될 작업을 어느 곳에 적용할지를 결정할 수 있습니다.

Pointcut 표현식이 존재하는데, 위의 표현식은 `RestController` 어노테이션을 가진 곳에 적용한다는 의미를 가지고 있습니다 !

2023-10-05 04:27 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/context/AnonymousLogId.java
> +
큰 의도는 존재하지 않았습니다 😀

홀수보다는 안정성 있는 짝수로 설정하고 싶었고 8자리 정도면 여러 요청을 동시에 보내더라도 랜덤하게 설정된 값으로 유니크하지 않을까라는 생각으로 8자리를 선택했던 것 같습니다 ㅎㅎ

2023-10-05 04:29 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/log4j2/SlackAppender.java
> +        final WebClient webClient = WebClient.builder()
저도 이번에 처음 사용해본 기술이라 블로그를 최대한 참고하여 작성했던 것 같아요 🤓

`WebClient`를 만들기 위해 필요한 데이터를 설정하는 부분으로 이해했기에 항상 `HttpClient`를 함께 사용하는 것 같지는 않습니다 !

2023-10-05 05:13 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
> +        memberIdHolder.setId(tokenPayload.memberId());
@RequestScope와 관련있습니다 !

2023-10-05 08:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/aop/QueryCountAop.java
> +    public Object getConnection(final ProceedingJoinPoint joinPoint) throws Throwable {
`JoinPoint` 인터페이스는 호출하는 메서드에 대한 정보를 가지고 있는 인터페이스입니다.

`@Around`를 사용하는 경우 특정 메서드 전, 후의 동작을 설정할 수 있는데, `@Around`가 적용된 메서드의 경우 파라미터로 `ProceedingJoinPoint`를 사용한다고 합니다. 이를 통해 원래의 메서드를 호출하거나, 파라미터 목록 등의 정보를 얻을 수 있습니다 !

2023-10-05 08:02 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/context/LogContext.java
> +    private int methodDepth = 0;
메서드가 호출될 때마다 메서드 호출 스택의 깊이가 깊어지기 때문에 서로 다른 의미를 가지고 있습니다 !

각각의 행위를 잘 드러내는 메서드명과 필드명을 사용하고자 했습니다 🤓

2023-10-05 08:03 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/log/log4j2/Attachment.java
> +package com.votogether.global.log.log4j2;
요청, 응답 로그에 사용되는 클래스들이 아닌 `log4j2`가 발생시키는 로그에 대한 슬랙 알림을 위한 클래스들이 모여있는 패키지이기 때문에 패키지명을 `log4j2`로 정하였습니다 !

2023-10-05 08:07 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/controller/PostQueryControllerTest.java
> +
`@WebMvcTest`와 같은 테스트 환경을 사용하지 않고 `@InjectMocks`와 `@Mock`으로 구성된 테스트 환경을 사용할 때는 `RestAssuredMockMvc`의 `standaloneSetup` 메서드를 통해 테스트 환경을 만들어주는 것이 테스트에서 필요한 의존성만 가져갈 수 있는 방법입니다.

저희 프로젝트에서 `Presentation` 계층의 테스트는 @WebMvcTest 환경을 사용하고 있기 때문에 해당 환경에 알맞은 애플리케이션 컨텍스트가 생성되어 있는 상태이기에 이미 구성된 애플리케이션 컨텍스트를 활용하는 것이 좋다고 생각하였습니다. 이를 위해 MockMvc 의존성을 주입받아 RestAssuredMockMvc에 세팅해주는 작업을 진행하였습니다 !

2023-10-05 08:09 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/ControllerTest.java
> +
`@WebMvcTest`를 사용하기에 빈으로 등록되어 있는 인터셉터에 대한 동작도 실행되게 됩니다. 인터셉터도 실제 빈으로 동작하게 하기 위해서는 인터섭터에서 주입받고 있는 객체들에 대한 의존성 주입도 필요하게 되고, 저희가 테스트해야할 컨트롤러의 로직보다 인터셉터 세팅에 더 많은 리소스가 들어가게 됩니다.

따라서 본질적으로 테스트하고자 하는 부분에 집중하고자 인터셉터 로직은 `mocking`을 통해 처리하고자 하였습니다 :)

2023-10-05 09:01 UTC, tjdtls690 approved these changes
고생하셨습니다!

2023-10-05 09:23 UTC, aiaiaiai1 approved these changes
고생하셨습니다~~!

2023-10-05 10:01 UTC, merged