회원의 닉네임을 일정주기를 통해 변경할 수 있도록 구현
woowacourse-teams/2023-votogether pull request #498
Opened 2023-09-01 09:22 UTC by jeomxon

## 🔥 연관 이슈

close: #491 

## 📝 작업 요약

초기에 랜덤닉네임이 지정된 후에 1회는 자유롭게 변경이 가능합니다.
1회 변경 후에는 최소 14일이 지나야 닉네임을 변경할 수 있도록 로직을 추가하겠습니다.

## ⏰ 소요 시간

1시간 

## 🔎 작업 상세 설명

없음.

## 🌟 논의 사항

없음.

2023-09-04 07:53 UTC, woo-chang reviewed
깔끔하게 잘 구현하신 것 같아요 저문 👍

소소한 질문이랑 테스트 관련 커멘트 남겨두었는데 확인해주시면 감사합니다 :)

2023-09-04 07:53 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +        return (!this.getCreatedAt().equals(this.getUpdatedAt())) &&
현재는 변경 가능한 필드가 닉네임밖에 없어서 괜찮을 것 같은데, 변경 가능한 필드가 생긴다면 조금 더 고민이 필요한 부분인 것 같네요 ㅎㅎ

2023-09-04 08:39 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +        return (!this.getCreatedAt().equals(this.getUpdatedAt())) &&
맞습니다 이 부분에 대해서 많이 생각을 했었는데, 이 방식으로 구현한만큼 잘 인지하고 있어야한다고 생각했어요.
현재는 문제가 없을 것 같아서 이대로 가져갈 생각입니다!

2023-09-04 08:39 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/member/service/MemberServiceTest.java
> +        @DisplayName("최초 닉네임을 변경한 후 닉네임 변경 주기가 지나지 않았다면 예외가 발생한다.")
한번 작성해보겠습니다..!

2023-09-05 14:04 UTC, woo-chang reviewed
테스트까지 잘 작성해주셨네요 👍

소소한 커멘트와 한 가지 궁금한 점이 있어 마지막으로 답변 부탁드릴께요 🙇🏻‍♂️

2023-09-05 14:04 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/member/entity/MemberTest.java
> +        }
```java
@Test
@DisplayName("15일전에 변경된 닉네임은 14일 주기로 변경할 때 성공적으로 변경된다.")
void success() {
    // given
    Member member = Member.builder()
            .nickname("저문")
            .gender(Gender.MALE)
            .birthYear(1966)
            .socialId("abc123")
            .socialType(SocialType.KAKAO)
            .build();
    LocalDateTime now = LocalDateTime.now().minusDays(15L);
    ReflectionTestUtils.setField(member, "createdAt", now);
    ReflectionTestUtils.setField(member, "updatedAt", now);

    // when
    member.changeNicknameByCycle("저라니", 14L);

    // then
    assertThat(member.getNickname()).isEqualTo("저라니");
}
```

리플렉션을 사용해서 테스트를 잘 해주셨네요 👍👍

테스트를 위한 리플렉션 유틸 클래스도 있어서 이를 활용하면 더 좋을 것 같아요! `throws Exception` 부분도 제거할 수 있을 것 같아요 ㅎㅎ

한 가지 궁금한 점은 리플렉션을 사용하면 `createdAt`, `updatedAt` 값을 설정할 수 있기에 메서드에 날짜를 받도록 수정하지 않아도 테스트할 수 있었을 것 같은데 메서드를 수정하신 이유가 궁금합니다!

2023-09-08 05:19 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/member/entity/MemberTest.java
> +        }
리플렉션 유틸 클래스가 있었군요..! 적용해보도록 할게요 감사합니다.
Member가 정책에 대한 날짜를 가지고 있는 것보다 application계층에서 넘겨주는 것이 비즈니스 로직을 잘 나타낼 수 있다고 생각해서 변경했습니다!
정책에 따라 변경될 수 있는 부분이라는 생각이 드는데, 만약 정책이 변경되어서 코드를 변경하러 갈 때 저라면 비즈니스 로직이 있는 부분에서 수정이 가능하도록 하는 것이 자연스럽다고 생각했어요.

하지만 현재 로직이 문제가 있는 것 같아서 내부 로직을 다시 수정해볼게요..!

2023-09-08 07:21 UTC, aiaiaiai1 requested changes
저문 수정 사항 확인했습니다
간단한 커멘트 남겨드렸는데 확인해주세요~

be-리뷰 완

2023-09-08 07:21 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +
`P2`
`isNotPassedChangingCycle` 메서드에 프리픽스로 시작하는 닉네임인지를 검증하는게 어색하다고 생각되는데
&& 로 연결 되어있는 두 boolen 식을 각각 메서드로 추출하고
추출한 메서드를 `changeNicknameByCycle`에서 &&로 연결한는건 어떤가요??


```suggestion
    public void changeNicknameByCycle(final String nickname, final Long days) {
        if (nickname.startsWith(INITIAL_NICKNAME_PREFIX)) {
            throw new BadRequestException(MemberExceptionType.INVALID_NICKNAME_LETTER);
        }
        if (isNotPassedChangingCycle(days) && ! isInitalNickname()) {
            throw new BadRequestException(MemberExceptionType.NOT_PASSED_NICKNAME_CHANGING_CYCLE);
        }
        this.nickname = new Nickname(nickname);
    }

    private boolean isNotPassedChangingCycle(final Long days) {
        return this.getUpdatedAt().isAfter(LocalDateTime.now().minusDays(days));
    }
    
    private boolean isInitalNickname() {
       return this.nickname.startsWith(INITIAL_NICKNAME_PREFIX) 
    }

```

2023-09-08 07:21 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +            throw new BadRequestException(MemberExceptionType.INVALID_NICKNAME_LETTER);
`P2`
`익명의손님`은 초기 닉네임이름이라 유효하지않는건 아닌거같아서 
초기 닉네임으로는 지정할수없습니다 처럼 예외 메시지를 새로 추가하는건 어떤가요?

2023-09-09 03:27 UTC, woo-chang approved these changes
아주 사소한 커멘트하나 남겼습니다 :)

반영해주셔도 좋고 반영하지 않아도 좋습니다 ㅎㅎ

be-리뷰 완

2023-09-09 03:27 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +            throw new BadRequestException(MemberExceptionType.INVALID_NICKNAME_LETTER);
`P2`
초기 닉네임에 대한 제한을 걸어 해당 닉네임으로 닉네임 변경 여부를 확인하는 방법으로 변경하셨네요 🤓

초기 닉네임이라 유효하지 않은 닉네임이라는 예외 메시지를 수정하거나, 닉네임 변경 여부 확인을 위해 리프레쉬 토큰을 저장하는 것처럼 레디스에 마지막 변경 시간을 저장하는 방법도 고려해볼 수 있을 것 같아요. 최대 2주기 때문에 2주 후에는 사라지는 데이터이고, 레디스가 만약 다운되었을 때 발생할 수 있는 이펙트로는 닉네임 변경이 한번 가능해진다 정도일 것 같아서 고려해볼 수 있을 것 같은데 정책에 맞지 않는 사용자의 행동이 발생할 수 있다는 단점도 있을 것 같네요 🥲

확실히 안정성을 보장하려면 `DB`에 새로운 테이블이나 컬럼을 추가하는 방법도 생각해볼 수 있을 것 같아요 :)

2023-09-09 06:25 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +
좋은 제안인 것 같아요 ㅎㅎ
안그래도 함수의 역할이 명확하지 않다는 생각만하고 그냥 넘어갔던 것 같은데 짚어주셔서 감사합니다!
말씀하신 방향대로 수정해볼게요 :)

2023-09-09 06:31 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +            throw new BadRequestException(MemberExceptionType.INVALID_NICKNAME_LETTER);
루쿠가 말씀하신대로 수정해볼게요!
단순히 유효하지 않다고 생각했었는데, 초기 닉네임으로 지정이 되니 유효하지 않다라는 메시지보다는
별도의 메시지로 분리되면 좋을 것 같네요 ㅎㅎ

2023-09-09 06:45 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +            throw new BadRequestException(MemberExceptionType.INVALID_NICKNAME_LETTER);
레디스를 사용하는 방식에 대해서는 생각해보지 않았는데 좋은 의견 감사합니다 :)
확실히 말씀해주신 것처럼 정책이고, 사용자에게 안내가 되기 때문에 갑자기 닉네임이 변경된다면 의문이 들 것 같긴해요!
그래서 db에 추가하는 방법도 생각해봤는데, 초기에 한번 사용되고 그 이후에는 추가적으로 사용되지 않을 필드라는 생각이 들어서
최대한 db에 저장하는 방법을 가져가고 싶지 않았어요.
그래서 초기 닉네임에 제한을 거는 방법을 사용했습니다!

레디스 설정한 pr이 더 늦게 merge될 것 같기도 해서 레디스에 적용하기보다는 지금 형식을 그대로 가져갈 생각입니다.
또한 현재의 구조를 확장한다고 가정하면 초기 닉네임 prefix에 대한 제한 뿐만아니라 부적절한 언어들에 대해 필터링할 때 확장하기 쉬울 것 같아요.

2023-09-09 07:23 UTC, aiaiaiai1 approved these changes
저문 확인했습니다~
고생하셨어요!

2023-09-09 07:39 UTC, merged