(비회원) 전체 카테고리 목록 조회 API 구현
woowacourse-teams/2023-votogether pull request #52
Opened 2023-07-14 12:46 UTC by aiaiaiai1

## 🔥 연관 이슈

close: #50 

## 📝 작업 요약

(비회원) 전체 카테고리 목록 조회 기능 구현

## 🔎 작업 상세 설명

비회원 권한일때 전체 카테고리 목록을 조회하는 기능입니다.

## 🌟 논의 사항

없음

2023-07-14 13:08 UTC, jeomxon requested changes
루쿠 코드 작성이 빠르시네요!!
작성하시느라 고생하셨습니다 :)
사소한 리뷰 남겨보았습니다~

2023-07-14 13:08 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/category/dto/response/CategoryResponse.java
> +
record를 사용해보는 것은 어떨까요?

2023-07-14 13:08 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
> +                collect(Collectors.toList());
개행 시 `.`을 뒤에 두고 개행을 하셨네요.
이 부분만 그렇게 보이는 것 같은데 일관성을 위해 수정이 필요해보입니다~
`collect(Collectors.toList())` 와 `toList()`의 차이점은 무엇일까요?

2023-07-14 13:08 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +    @DisplayName("카테코리를 저장한다.")
카테코리..?

2023-07-14 13:08 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +    @DisplayName("같은 이름의 카테코리를 저장할 시 에러가 발생한다.")
여기도 카테코리가 있어요 ㅎㅎ

2023-07-14 13:08 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
> +                collect(Collectors.toList());
아예 하나로 합쳐서 리턴하는 것도 깔끔하고 보기 좋을 것 같아요!
루쿠는 어떻게 생각하시나요?

2023-07-14 13:08 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +
테스트 코드 작성 시 루쿠만의 개행 기준은 어떻게 되시나요?

2023-07-15 00:34 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
> +                collect(Collectors.toList());
하나로 합친다는 말씀이 어떤걸까요??

2023-07-15 00:35 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
> +                collect(Collectors.toList());
`Stream.toList()` 로 수정했습니다~ 덕분에 새로운 기능 배워갑니다

2023-07-15 00:42 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +
저는 객체 속성값이 잘보이도록 속성값을 한줄에 하나씩 있게끔 개행을 하는 편이에요

2023-07-15 11:03 UTC, woo-chang requested changes
빠른 속도로 개발해주고 계시군요 👏🏻
몇 가지 코멘트 달아두었으니 확인 부탁드릴께요
수고하셨습니다 :)

2023-07-15 11:03 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
> +    public List<CategoryResponse> getAllCategories() {
`@Transactional(readOnly = true)` 어노테이션을 추가해볼까요?

2023-07-15 11:03 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/category/service/CategoryService.java
> +                .toList();
`toList` good 👍 자바 17을 잘 활용하시네요~

2023-07-15 11:03 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +@Import(JpaConfig.class)
중복해서 사용될 것 같은데 이를 위한 어노테이션을 만들어볼 수 있지 않을까요? ㅎㅎ

2023-07-15 11:03 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +class CategoryRepositoryTest {
`Service`, `Controller`에 대한 테스트 코드가 누락된 것 같아요!

2023-07-15 11:03 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/category/repository/CategoryRepositoryTest.java
> +    }
저장에 대한 테스트인 것 같은데 `@Nested`를 사용해 응집성 있게 묶는게 좋을 것 같아요 :)

2023-07-17 15:56 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/category/dto/response/CategoryResponse.java
> +    }
파라미터에 `category`만 있는 메서드와 
다즐이 제안해주신 `category` 와 `isFavorite`을 가지는 메서드 둘다 가지는 거에 대해서는 어떻게 생각하시나요??

2023-07-18 01:56 UTC, woo-chang approved these changes
변경사항 확인했습니다 수고하셨어요 루쿠 🙇🏻‍♂️

2023-07-18 02:37 UTC, jeomxon approved these changes
반영해주시느라 고생하셨습니다 :)
백엔드 파이팅!

2023-07-18 02:38 UTC, merged