신고 도메인 리팩터링
woowacourse-teams/2023-votogether pull request #540
Opened 2023-09-07 09:12 UTC by tjdtls690

## 🔥 연관 이슈

close: #513 

## 📝 작업 요약

신고 도메인을 리팩터링합니다.

## ⏰ 소요 시간

예상 : 10시간
실제 : 6시간

## 🔎 작업 상세 설명

Report 도메인 관련 코드들의 가독성을 개선하기 위한 리팩토링

2023-09-13 03:23 UTC, woo-chang approved these changes
와 너무 깔끔하게 리팩토링 잘해주셨는데요 👍

괜히 삽자루 선생님이 아니군요 :) 많이 배워갑니다 !

아주 소소한 커멘트 하나 남겼습니다 ~ approve는 하도록 할께요 수고하셨습니다 ㅎㅎ

2023-09-13 03:23 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/report/service/strategy/ReportStrategy.java
> +    int NUMBER_OF_NICKNAME_CHANGE_REPORTS = 3;
`P2`
각각의 전략에서 필요한 값들은 각각의 전략에 두는게 응집성 측면에서 더 좋다고 생각합니다! 실제로도 해당 값을 수정한다고 생각해보았을 때 값을 수정하기 위해 해당 전략을 먼저 찾아갈 것 같아요 🤓

2023-09-14 07:57 UTC, jeomxon requested changes
전략패턴을 사용하여 멋지게 리팩터링 해주셨군요!
사소한 코멘트 몇개 남겨두었습니다.
고생하셨습니다👍🏻

2023-09-14 07:57 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
>          }
`Q`
assertThat이 있는 것과 없는 것의 차이는 무엇인가요?

2023-09-14 08:13 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/repository/ReportRepository.java
> +    void deleteByReportTypeAndTargetId(final ReportType reportType, final Long targetId);
레벨 4 미션하면서 테스트 코드 안하다보니까 프로젝트에서도 자연스럽게 안해버렸네요. 테스트 코드 추가하겠습니다.

2023-09-14 08:25 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
>          }
공식문서에 따르면, Syntactic sugar, e.g. 라고 합니다.

즉, '주장하다' 라는 의미 그대로 해석할 수 있는데요. 없을 땐 각 테스트 메서드에서 경고(메서드 이름에 노란색 배경)가 뜨더라구요. 설명을 보니, 테스트 메서드 안에서 실제로 테스트가 되는 로직이 없으니 테스트 되는 로직을 하나라도 만들라는 뜻이었습니다.

사실 assertThat() 이 없어도 테스트는 정상적으로 되는데, IDEA에선 RestAssuredMocnMvc를 쓸 때, 이걸 잡지 못하더라구요. RestAssured는 assertThat()을 껴주지 않아도 경고가 안뜨던데 얘만 왜이런지는 모르겠네요.

그래서 제 결론은, 경고도 없애면서 'assertThat() 뒤에선 이제 검증하는 것들이 나올테니 잘 봐라' 라는 뜻으로도 넣어주고 있습니다.

2023-09-14 08:27 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/report/controller/ReportCommandControllerTest.java
>          }
명시적으로 표시해주는 역할이고 큰 의미는 없다고 생각하면 될까요?

2023-09-14 08:33 UTC, jeomxon approved these changes
반영해주시느라 고생하셨습니다!
approve하겠습니다~

2023-09-14 08:34 UTC, merged