리프레시 토큰 기능(로그아웃 포함) 구현
woowacourse-teams/2023-votogether pull request #545
Opened 2023-09-08 05:14 UTC by jeomxon

## 🔥 연관 이슈

close: #532 

## 📝 작업 요약

spring-data-redis, TestContainers의존성을 추가했습니다.

이 작업이 머지된다면 도커에 레디스 이미지를 띄우는 작업도 필요할 것 같아요.
AuthService 테스트 시 레디스 이미지를 띄워서 진행합니다.

## ⏰ 소요 시간

순 시간만 12시간 걸린 것 같네요(트러블 슈팅 5시간을 포함하면...)

## 🔎 작업 상세 설명

없음.

## 🌟 논의 사항

자유롭게 의견 남겨주세요 :)

2023-09-09 08:10 UTC, aiaiaiai1 reviewed
저문 깔끔하게 구현해주셨군요! 👍 
몇가지 질문 남겨드렸는데 확인 부탁드려요!

2023-09-10 15:17 UTC, tjdtls690 requested changes
코드가 굉장히 깔끔합니다. 항상 많이 배워가네요. 
몇가지 리뷰 달았습니다!
- 문 -

2023-09-10 15:17 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        final String newRefreshToken = tokenProcessor.generateRefreshToken(refreshToken.getMemberId());
```P2```
밑에서도 리프레쉬 토큰을 새로 발급한다는 의미에서 newRefreshToken를 사용해주었는데, accessToken도 newAccessToken로 변경하는 것은 어떨까요.

2023-09-10 15:17 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    public ResponseEntity<LoginResponse> loginByKakao(
```Q```
흐름에 관한 질문입니다! 클라이언트에서 미리 쿠키에 엑세스 토큰이 있는지 확인하고 없으면  "/kakao/callback", 있으면 "/silent-login" API를 호출하는 흐름인건가요?

2023-09-10 15:17 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +        final AccessTokenRequest request = new AccessTokenRequest(accessToken);
```P1```
이 부분부터 밑으로 쭉 final 키워드 지워야 할 것 같아요.

2023-09-11 04:11 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +                .orElseThrow(() -> new BadRequestException(TokenExceptionType.NONEXISTENT_REFRESH_TOKEN));
좋은 의견 감사합니다. 먼저 찾은 후에 쿠키 값을 가져오는 것이 더 자연스러워 보이네요.
루쿠가 생각하시기에 두 코드의 성능차이가 유의미하다고 생각하시나요?
어떤 관점에서 메서드 순서 변경이 적절하다고 판단하신건가요?

2023-09-11 04:12 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        }
요청의 정당성 여부와 관계없이, 해당 리프레시 토큰에 대한 값을 지워주는 것이 보안에 유리하다고 생각했기 때문입니다.

2023-09-11 04:13 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/dto/LoginTokenResponse.java
> +}
해당 Dto는 service -> controller로 데이터를 전달하기 위해서 사용합니다.
따라서 패키지 구조를 다음과 같이 가져갔구요.
swagger어노테이션은 필요하지 않을 것 같아요!

2023-09-11 04:14 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
>          final Date now = new Date();
refreshToken을 생성하는 로직과의 통일성을 위해서 memberId로 통일했습니다.
원래도 내부적으로는 `member.getId()`를 통해서 값을 가져오고 있었기에 문제 없을 것이라고 생각했습니다.

2023-09-11 04:18 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    private void addRefreshTokenToCookie(final HttpServletResponse httpServletResponse, final String refreshToken) {
재귀에 빠져버렸습니다...

2023-09-11 05:45 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +        final TokenResponse tokenResponse = authService.reissueAuthToken(request, refreshToken);
그 점을 고려해서 `HttpServeltRequest`를 httpServletRequest로 가져가고 요청에 대한 것은 기존 메서드와 통일성있게 request로 가져가는 방식으로 정했는데, 어떻게 생각하시나요?

2023-09-11 05:46 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/RefreshToken.java
> +    private String refreshToken;
제가 생각했던 것은 레디스에서는 key, value쌍으로 데이터가 저장되기 때문에, Key에 식별자로 RefreshToken이 들어가고 value에 memberId를 넣는 방식을 채택했습니다.
RefreshToken은 현재 1인당 하나로 제한되기 때문에 식별자로써 사용되는 것도 문제없다고 생각했어요~

2023-09-11 06:10 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        final String newRefreshToken = tokenProcessor.generateRefreshToken(refreshToken.getMemberId());
좋은 것 같아요! 반영하겠습니다~

2023-09-11 06:11 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +        final AccessTokenRequest request = new AccessTokenRequest(accessToken);
감사합니다 꼼꼼한 리뷰👍🏻

2023-09-11 06:20 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    public ResponseEntity<LoginResponse> loginByKakao(
처음 로그인 시에는 카카오 로그인 api로 갑니다.
그리고 그 후에 토큰이 만료되었다는 메시지를 확인한 클라이언트가 액세스 토큰 재발급 요청을 하는 흐름으로 진행됩니다.

2023-09-11 07:25 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +                .orElseThrow(() -> new BadRequestException(TokenExceptionType.NONEXISTENT_REFRESH_TOKEN));
필터를 통해서 값이 1개만 반환되기때문에 성능차이는 거의 없을거같고 
단순하게 코드를 읽는 관점에서 필터를 통해 원하는 값을 가져온 후에 로직을 실행하는게 적절하다고 생각했습니다~
스트림이 여러 데이터를 순차적으로 조작하는거라 생각하는데 filter다음에 map이 오니까 filter를 통해 걸러진 데이터가 여러개가 있나? 라는 생각이 들어서요!

2023-09-11 07:32 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        }
그럼 `validateTokenInfo`메서드를 호출하는 `reissueAuthToken`메서드에서 `refreshTokenRepository.delete(refreshToken);`를 실행시키면 안되나요??

현재 메서드에서는 검증과 리프레시 토큰 삭제 역할 두가지가 있다고 생각해서요

근데 트랜잭션때문에 에러 발생하면 롤백되지 않나요?

2023-09-11 07:41 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +                .orElseThrow(() -> new BadRequestException(TokenExceptionType.NONEXISTENT_REFRESH_TOKEN));
감사합니다 수정하겠습니다!

2023-09-11 07:49 UTC, tjdtls690 requested changes
딱 하나 제가 잘못 질문을 전달한 부분에 대해서 재질문 드렸어요. 그 부분만 해결되면 바로 approve 할게요!

2023-09-11 07:49 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    private void addRefreshTokenToCookie(final HttpServletResponse httpServletResponse, final String refreshToken) {
```P2```
아 제가 수정도 잘못 했네요. 다시 수정해서 질문하자면 

addRefreshTokenToCookie 메서드 순서를 reissueAccessToken 내부에서 마지막으로 호출하니 reissueAccessToken 메서드 바로 밑(logout 메서드 위)에 두는 것을 얘기한 거였어요.

2023-09-11 07:49 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +        final TokenResponse tokenResponse = authService.reissueAuthToken(request, refreshToken);
사람마다 request의 default 의미를 다른 것으로 생각할 수도 있겠네요. 저문 말처럼 HttpServletRequest보다 좀 더 직접적인 사용자 요청에 가까운 AccessTokenRequest 를 request로 해주는 것이 더 나을 수 있겠네요.
동의합니다 :)

2023-09-11 07:54 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    private void addRefreshTokenToCookie(final HttpServletResponse httpServletResponse, final String refreshToken) {
아하 이런 의도셨군요..!
저는 개인적으로 controller는 요청을 확실히 드러내는게 좋을 것 같다고 생각했고,
public메서드들을 위에 몰아두는게 좋다고 판단해서 지금과 같은 순서로 배치했습니다.
그리고 `reissueAccessToken`메서드의 마지막에 둔다면 `loginByKakao`메서드에서도 사용하기 때문에 규칙성이 없을 것 같다고 생각했어요.
따라서 저는 지금과 같은 순서를 유지하는 것이 좋다고 생각하는데 추가적인 의견 있으신가요?

2023-09-11 09:33 UTC, aiaiaiai1 approved these changes
저문 확인했습니다! 고생하셨어요~

2023-09-11 11:50 UTC, woo-chang requested changes
새로운 기술이 많이 있어 복잡했을텐데 깔끔하게 잘 구현해주셨네요 👍👍

몇 가지 질문과 커멘트 남겼으니 확인 부탁드릴께요 🙇🏻‍♂️

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +        cookie.setPath("/");
`Q`
1. HttpOnly와 Secure 초기값은 `false`인가요?
2. `/` 경로를 지정함으로 모든 경로의 요청에 refreshToken이 쿠키에 담겨서 오는 것으로 이해했는데, 모든 요청에 refreshToken이 필요한지 궁금합니다!
3. `/` 경로를 지정하지 않으면 어떤값이 기본으로 설정되나요? 🤔

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
> +    ) throws JsonProcessingException;
`Q`
해당 예외를 `throws` 하는 이유가 무엇인가요?!

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/dto/request/AccessTokenRequest.java
> +public record AccessTokenRequest(
`P2`
```suggestion
public record RenewAccessTokenRequest(
```
재발급 의미를 조금 더 추가한 변수명은 어떠신가요 !

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/dto/response/AccessTokenResponse.java
> +@Schema(description = "인 토큰 재발급 응답")
`P1`
```suggestion
@Schema(description = "인증 토큰 재발급 응답")
```
오타 발견 ㅎㅎ

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/exception/TokenExceptionType.java
> +    UNMATCHED_INFORMATION_BETWEEN_TOKEN(2001, "토큰 간의 정보가 일치하지 않습니다.");
`P2`
`Token`에서 발생하는 예외도 `auth` 예외라고 봐도 괜찮을 것 같은데 저문은 어떻게 생각하시나요?
https://github.com/woowacourse-teams/2023-votogether/discussions/526

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/repository/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends CrudRepository<RefreshToken, String> {
`Q`
1. `@Id`는 String만 가능한가요? 다른 타입으로 설정이 가능하다면 위의 String도 해당 타입으로 변경하면 되는걸까요? 🤔
2. `RedisTemplate` 방법도 존재한데 `RedisRepository` 방법을 선택하신 이유가 궁금합니다!

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
>          final Member member = Member.from(response);
`P2`
`Member` 도메인에 response를 넘기고 있어 외부 요청과 응답에 대한 의존성이 있는 것처럼 보이는 것 같아요. `dto`로 명칭을 수정하거나 필요한 필드를 추출해서 각각 전달하는 방법은 어떠신가요 :)

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +    @Transactional(noRollbackFor = {BadRequestException.class})
`Q`
오 처음보는 설정 😎 어떤 설정인지 설명부탁드립니다 ㅎㅎ

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        validateTokenInfo(accessTokenPayload, refreshToken);
`P1`
검증 후에 삭제가 필요할 것 같아요. 인증 토큰과 일치하지 않지만 DB에 존재하는 리프레쉬 토큰이라면 정상적인 인증 토큰의 리프레쉬 토큰이 삭제되버리는 결과가 발생할 것 같습니다!

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        if (!accessTokenPayload.memberId().equals(refreshToken.getMemberId())) {
`P3`
혹시 모를 `Null` 안정성을 위해 `Objects.equals`를 사용해보는건 어떨까요? 🤓

2023-09-11 11:50 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        refreshTokenRepository.delete(refreshToken);
`P3`
삭제라면 존재하는지 검증없이 바로 삭제하는 방법도 존재하는데 존재하는지 검증을 거친 이유가 무엇인지 궁금합니다! `deleteById` 같은 메서드도 존재하는거죠?!

2023-09-11 11:50 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +        AccessTokenRequest request = new AccessTokenRequest(accessToken);
`P3`
AccessTokenRequest의 @NotBlank Bean Validation 설정을 통해 null이거나 빈 값이 들어올 경우 예외가 발생하는지에 대한 테스트도 있으면 좋을 것 같아요 :)

2023-09-11 11:50 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +                .cookie("refreshToken", tokenResponse.refreshToken())
`Q`
`Set-Cookie` 헤더에 해당 쿠키가 있는지에 대한 검증이 진행되는것으로 이해하면 될까요? 😀

2023-09-11 11:50 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
> +        @DisplayName("올바르지 않은 갱신 토큰이 주어지면 예외가 발생한다.")
`P3`
갱신 토큰이 없는 경우에 대한 테스트인 것 같아 테스트 메서드명을 이에 맞게 수정해보는건 어떨까요?!

2023-09-11 11:50 UTC, woo-chang commented on backend/src/test/java/com/votogether/test/config/RedisTestConfig.java
> +@TestConfiguration
`P3`
이렇게 사용하는군요 배워갑니다 👍👍

2023-09-11 12:12 UTC, jeomxon commented on backend/build.gradle
> +    testImplementation "org.testcontainers:testcontainers:1.19.0"
레디스를 이용한 테스트는 어떻게 진행할 수 있을까를 고민해보다가 처음 EmbeddedRedis가 있다는 사실을 알았습니다.
편하게 사용할 수 있을 것 같다고 생각을 했었는데, [EmbeddedRedis 레포지토리](https://github.com/ozimov/embedded-redis)를 확인해보니 마지막 커밋이 2020년 6월 11일인 것을 확인할 수 있었습니다. 즉 현재 업데이트가 지속적으로 이뤄지지 않는다고 할 수 있었어요.
또한 EmbeddedRedis는 스프링 컨텍스트에 일대일 매핑이 되기 때문에 테스트 환경에서 포트 충돌로 인한 문제가 발생할 수 있습니다.

따라서 위와 같은 문제를 해결하기 위해서 테스트 컨테이너를 도입했습니다.
물론 도커 컨테이너를 생성하고 삭제할 때 시간이 늘어난다는 단점이 있지만,
포트 충돌로 인한 문제를 사전에 방지할 수 있다는 점, 지원되지 않는 EmbeddedRedis를 굳이 사용할 필요가 없다는 점에서 테스트 컨테이너를 채택했습니다.

해당 버전을 선택할 때 따로 고려할 부분이 없었기에 최신 버전을 선택하기 위해서 [테스트 컨테이너 레포지토리](https://github.com/testcontainers/testcontainers-java)를 확인한 후 선택했습니다.
<img width="300" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/51906604/a91dfd7f-46ca-47b1-880b-dcbfef56f228">

2023-09-11 12:29 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/config/RedisConfig.java
> +        return new LettuceConnectionFactory(host, port);
먼저 스프링부트에서 기본적으로 제공되는 의존성인 lettuce를 사용하여서 복잡도를 줄이고자 했습니다.
[Jedis 보다 Lettuce 를 쓰자](https://jojoldu.tistory.com/418)를 보면 lettuce의 비동기처리로 인해 jedis보다 성능이 뛰어난 것을 알 수 있습니다.
Redisson도 존재한다고 알고 있는데, 이는 락에 대한 추가적인 기능이 필요할 때 사용하면 좋을 것이라는 생각이 들었습니다.
위와 같은 이유들로 Lettuce를 사용했습니다.

2023-09-11 12:43 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/RefreshToken.java
> +public class RefreshToken {
생각지도 못했는데 사용하니 잘 작동하네요!
`record`로 변경해볼게요

2023-09-11 12:59 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +                .cookie("refreshToken", tokenResponse.refreshToken())
네 이해하신 바가 맞습니다!

2023-09-11 13:14 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +        cookie.setPath("/");
1. 네 맞습니다. 설정을 한 것과 하지 않은 쿠키를 전부 시험해봤었는데 초기값이 false였습니다.
2. 제가 처음에 잘못생각했던 것 같은데 모든 요청에 RefreshToken도 같이 보내줘야한다고 생각했던 것 같아요.
    액세스 토큰 재발급, 로그아웃 두가지 경우의 모든 요청에 대해서 쿠키를 보내줘야하기 때문에 `/auth`에 setPath를 하는 것이 더 적절 
    할 것 같네요. 수정하겠습니다.
3. 이것도 시험해봤었는데, `/auth/kakao`으로 왔습니다. 즉 요청한 uri로 설정되는 것 같아요.

2023-09-11 13:27 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
> +    ) throws JsonProcessingException;
TokenProcessor클래스의 ObjectMapper에 readValue메서드에서 발생할 수 있습니다.
이게 Controller까지 넘어와서 던져주고 있습니다.

2023-09-11 13:28 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/dto/request/AccessTokenRequest.java
> +public record AccessTokenRequest(
`reissued`라는 prefix를 추가해보겠습니다!

2023-09-11 13:29 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/dto/response/AccessTokenResponse.java
> +@Schema(description = "인 토큰 재발급 응답")
증 추가했습니다 ㅋㅋㅋㅋ

2023-09-11 13:38 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/exception/TokenExceptionType.java
> +    UNMATCHED_INFORMATION_BETWEEN_TOKEN(2001, "토큰 간의 정보가 일치하지 않습니다.");
auth예외라고 보는 것이 좋을 것 같네요.
`AuthExceptionType`로 네이밍을 변경해보겠습니다.

2023-09-11 13:44 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
>          final Member member = Member.from(response);
dto로 네이밍을 변경해보겠습니다.

2023-09-11 15:03 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +    @Transactional(noRollbackFor = {BadRequestException.class})
BadRequestException이 해당 메서드 내부에서 발생한 경우에 rollback을 하지않고 이전까지 모두 커밋하도록 하는 옵션입니다!

2023-09-11 15:15 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/RefreshToken.java
> +    private String refreshToken;
어떤 부분을 보고 다중 로그인에 대한 상황을 말씀하신건가요?

2023-09-11 15:33 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/repository/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends CrudRepository<RefreshToken, String> {
1. 현재 @Id가 붙은 타입에 대해서는 String으로 설정된다고 하네요. 다른 타입으로의 설정이 완전히 불가능하지는 않은 것 같아요. 하지만 말그대로 Id이기 때문에 추가적인 설정이 필요할 것 같습니다.
2. RedisTemplate에 대한 설정코드가 추가적으로 필요하고, 현재는 간단한 CRUD기능으로 충분하다고 생각해서 RedisRepository를 사용하여 구현했습니다.

2023-09-11 16:11 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        validateTokenInfo(accessTokenPayload, refreshToken);
저는 재발급 요청을 보낸 경우에는 정상적으로 검증이 됐든 안됐든, 보안상의 문제 때문에 삭제를 시켜줘야한다고 생각했어요.
잘못 요청을 보냈더라도 부작용은 재로그인 정도밖에 되지 않기 때문에 크게 문제없지 않을까요?

2023-09-11 16:11 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        if (!accessTokenPayload.memberId().equals(refreshToken.getMemberId())) {
변경했습니다!

2023-09-11 16:13 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        refreshTokenRepository.delete(refreshToken);
삭제로직을 나중에 생각해서 이렇게 구현했었나보네요..!
`deleteById`로 삭제해주면 더 좋을 것 같네요. 수정해보겠습니다.

2023-09-11 16:29 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/auth/service/AuthServiceTest.java
> +        @DisplayName("올바르지 않은 갱신 토큰이 주어지면 예외가 발생한다.")
수정했습니다~

2023-09-11 17:24 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +        AccessTokenRequest request = new AccessTokenRequest(accessToken);
처리 후 테스트 추가했습니다!

2023-09-12 00:52 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
>  @RequiredArgsConstructor
중요한 어노테이션 순서대로 배치하자는 팀의 컨벤션이 존재하는데, `@RequestMapping`이 더 중요하다고 생각했습니다 !

2023-09-12 00:56 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
> +    ) throws JsonProcessingException;
`Checked Exception`이라면 컨트롤러까지 던지기보다는 애플리케이션 계층에서 처리해주는 것이 어떨까요? 🤔

2023-09-12 01:43 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/RefreshToken.java
> +    private String refreshToken;
동일한 멤버에 대해 여러가지 `RefreshToken`이 등록될 수 있는 상황이라 그렇게 생각했습니다 !

2023-09-12 01:44 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +        validateTokenInfo(accessTokenPayload, refreshToken);
좋은 것 같습니다 :)

2023-09-12 01:49 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +    @Transactional(noRollbackFor = {BadRequestException.class})
말씀하신대로 리프레시 토큰이 존재하지만 인증 토큰이랑 매칭되지 않는 경우 `BadRequestException`이 발생하는데, 그 경우라도 보안 때문에 접근된 리프레시 토큰을 삭제하기 위해 롤백시키지 않는 해당 옵션을 사용하는 것으로 이해했어요.

https://bcp0109.tistory.com/328

저도 이 부분에 대해 전혀 몰라 찾아보며 리뷰를 진행하게 되었는데, 위의 블로그에 따르면 `CrudRepository`를 사용하는 경우 트랜잭션을 지원하지 않는다고 하더라고요. 트랜잭션을 사용하려면 `RedisTemplate` 사용이 필요하다고 되어있는데 이 부분이 맞을까요? 🤔

`BadRequestException`이 발생했을 때 롤백되지 않는지 확인하는 테스트도 있으면 좋을 것 같아요 :)

2023-09-12 04:44 UTC, tjdtls690 approved these changes
Redis 적용하여 리프래쉬 토큰 구현 코드 보고 많이 배웠습니다. 수고하셨어요~!
(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧

2023-09-12 05:14 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +    @Transactional(noRollbackFor = {BadRequestException.class})
제가 noRollbackFor옵션을 왜 제거했었는지 다시 생각이 났네요.
레디스는 트랜잭션에서 롤백이 보장되지 않았기 떄문에 위의 옵션을 추가했다가 다시 제거했는데 잊고 있었네요...
트랜잭션을 위해서 RedisTemplate을 사용하도록 변경해야할 것 같네요

2023-09-12 05:20 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/RefreshToken.java
> +    private String refreshToken;
그렇네요 아까 이야기 나눴던 것처럼
현재는 다중로그인이 가능하고 그에따른 문제는 없을 것 같아요!

2023-09-12 06:42 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
> +    ) throws JsonProcessingException;
알려주신 방법으로 변경했습니다!

2023-09-12 06:57 UTC, tjdtls690 requested changes
한 가지 리뷰에 대해서만 해결되면 바로 approve 할게요

2023-09-12 06:57 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/repository/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends CrudRepository<RefreshToken, String> {
```P1```
트랜잭션을 위해 RedisTemplate을 사용하게 되면 RedisRepository는 필요 없을 것 같아요!

2023-09-12 07:18 UTC, woo-chang approved these changes
수정까지 빠르게 해주셨네요 👍

approve 하도록 하겠습니다 ~~

2023-09-12 07:20 UTC, tjdtls690 approved these changes

2023-09-12 07:23 UTC, merged