인기게시글 랭킹 목록 조회 기능
woowacourse-teams/2023-votogether pull request #546
Opened 2023-09-08 05:55 UTC by aiaiaiai1

## 🔥 연관 이슈

close: #539 

## 📝 작업 요약

인기게시글 랭킹 목록 조회 기능을 구현했습니다.

## ⏰ 소요 시간

3시간

집중력 저하 및 에너지 고갈 + 테스트코드 작성 고민

## 🔎 작업 상세 설명

모든 게시글에 대해서 인기순으로 10개의 게시글을 순서대로 조회합니다.

## 🌟 논의 사항

2023-09-11 07:36 UTC, jeomxon requested changes
코드 빠르고 깔끔하게 작성해주신 것 같아요!
고생하셨어요 루쿠 ㅎㅎ

코멘트 몇개 남겨보았습니다! 전반적으로 잘 구현해주셔서 리뷰하기 편했어요 :)

2023-09-11 07:36 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/dto/response/post/PostCompactResponse.java
> +    public static PostCompactResponse of(final Post post) {
`P2`
정적 팩터리 메서드 컨벤션에 맞게 from으로 변경하는 것이 어떨까요?

2023-09-11 07:36 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +                .toList();
`P2`
```suggestion
    private Map<Post, Integer> calculateRanking(final List<Post> posts) {
        final List<Post> sortedPosts = posts.stream()
                .sorted(Comparator.comparingLong(Post::getTotalVoteCount).reversed())
                .toList();
```
내림차순으로 정렬하는 경우 이렇게 변경하는 것은 어떨까요?

2023-09-11 07:36 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`Q`
위의 rankings라는 Map에서 정렬을 해줬는데  return문에서 다시 정렬을 해주는 이유가 무엇인가요?
만약 순서가 `HashMap`에서 순서가 보장되지 않기 때문이라면, `LinkedHashMap`을 사용하는 것은 어떤가요?

2023-09-11 07:36 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`P3`
같은 흐름인 것 같은데 여기서는 개행없이 가는 것은 어떨까요?

2023-09-11 07:36 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`P2`
```suggestion
final Map<Post, Integer> rankings = new HashMap<>();
int ranking = 1;
long previousVoteCount = Long.MAX_VALUE;

for (Post post : sortedPosts) {
    final long currentVoteCount = post.getTotalVoteCount();
    if (currentVoteCount != previousVoteCount) {
        ranking++;
    }
    rankings.put(post, ranking);
    
    previousVoteCount = currentVoteCount;
}

```
이렇게하면 로직을 조금 단순화 할 수 있을 것 같아요

2023-09-11 07:36 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +    @DisplayName("상위 10개의 인기 게시물을 조회한다.")
`P2`
같은 등수인 경우에 대한 테스트 코드도 추가하는건 어떨까요?

2023-09-11 14:19 UTC, woo-chang requested changes
수고하셨습니다 루쿠 🙇🏻‍♂️

저문이 꼼꼼히 리뷰해주셔서 저는 소소한 커멘트만 남겨보았습니다

확인해주시면 감사합니다 :)

2023-09-11 14:19 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/response/post/PostCompactResponse.java
> +public record PostCompactResponse(
`P3`
`PostSummaryResponse`와 같은 변수명은 어떠신가요?!

2023-09-11 14:19 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +            final int ranking = (currentVoteCount == previousVoteCount) ? previousRanking : currentRanking;
`P3`
여기 로직도 추후에 리팩토링하면 좋을 것 같아요!

2023-09-11 14:19 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`P3`
위의 로직에서 첫 게시글은 랭킹이 `2`가 되는거 아닌가요? 🤔

가독성은 너무 좋은 것 같습니다 👍

2023-09-11 14:19 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +        assertThat(result.get(0)).isEqualTo(postRankingResponse);
`P2`
```suggestion
        assertThat(result).usingRecursiveComparision().isEqualTo(List.of(postRankingResponse));
```
`result` 자체로 비교하도록 수정해보는건 어떨까요?

2023-09-11 16:00 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
레전드... 수정하였습니다!

2023-09-11 16:15 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
좋은 제안 감사합니다!
if문안에 ++이 있어서 첫 게시글 랭킹을 0으로 수정해보았는데
중복순위가 있을때  1 1 1 4 5 가 아닌 1 1 1 2 3 이 되더라고요 ㅠ

2023-09-11 16:34 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/service/PostServiceTest.java
> +    @DisplayName("상위 10개의 인기 게시물을 조회한다.")
사실상 해당 테스트가 같은 등수인 경우에 대한 테스트라서
같은 등수가 아닌 경우에 대한 테스트를 따로 추가했습니다~

2023-09-11 16:43 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/dto/response/post/PostCompactResponse.java
> +public record PostCompactResponse(
좋아요~ 제안 감사합니다!

2023-09-11 16:45 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +            final int ranking = (currentVoteCount == previousVoteCount) ? previousRanking : currentRanking;
인정합니다...

2023-09-11 16:47 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +        assertThat(result.get(0)).isEqualTo(postRankingResponse);
오 이런방법이,, 또하나 배워갑니다,, 👍

2023-09-12 02:03 UTC, woo-chang approved these changes
수고하셨습니다 🙇🏻‍♂️

리팩토링 관련 사항을 제외하고는 반영된 것 같아

approve 하도록 하겠습니다 ~~

2023-09-12 04:41 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
그러네요 일단 이 로직은 추후에 리팩터링 해보는 걸로 해야할 것 같네요..ㅎㅎ

2023-09-12 04:43 UTC, jeomxon approved these changes
리뷰 반영하느라 고생하셨습니다~
approve할게요!

2023-09-12 05:10 UTC, merged