[REFACTOR] 게시글 도메인 리팩터링
woowacourse-teams/2023-votogether pull request #549
Opened 2023-09-10 16:31 UTC by woo-chang

## 🔥 연관 이슈

* close: #512

## 📝 작업 요약

게시글 도메인을 리팩토링하였습니다.

## ⏰ 소요 시간

3일 .. ?

예상치 못한 부분에서 에러가 종종 발생하여 생각보다 시간이 오래 걸리게 된 것 같습니다 🥲

많은 기능을 혼자 구현하고 개발한 아벨 존경합니다 🙇🏻‍♂️

## 🔎 작업 상세 설명

- 한 클래스에 1000줄이 넘던 코드를 역할에 맞게 분리하였습니다.
  - `PostGuestService` : 게시글과 관련한 비회원 로직
  - `PostCommandService` : 게시글 생성, 수정, 삭제 등과 같이 도메인의 변화를 주는 로직
  - `PostQueryService` : 게시글 도메인의 변화 없이 조회만 발생하는 로직
- 연관관계를 값 객체에서 상위 엔티티로 올려 연관관계가 잘 보이도록 수정하였습니다.
  - 추후에 연관관계 엔티티의 로직이 많아진다면 값 객체로 분리해봐도 좋을 것 같습니다!
- 중복되는 코드를 제거하고 중복이 발생하는 부분은 메서드로 추출하였습니다.
- 하나의 메서드에서는 하나의 역할만 수행하도록 하여 코드 가독성을 개선하였습니다.
- 코드 컨벤션이 일치하지 않았던 부분에 대해 코드 컨벤션을 수정하였습니다.
- 어노테이션 기반의 테스트 유틸이 아닌 상속 구조의 테스트 유틸을 생성하여 테스트에서 중복되는 부분은 재사용할 수 있도록 하였습니다.
- 리팩토링 전 `214`개의 테스트에서 `100`개 가량 테스트를 작성하여 `329`개의 테스트로 검증 안정성을 높였습니다.

## 🌟 논의 사항

리팩토링하면서 코드 컨벤션으로 맞추고 싶은 부분 `Discussion`에 올려두었는데 같이 얘기해보면 좋을 것 같아요 :)

https://github.com/woowacourse-teams/2023-votogether/discussions/526

PR이 생각보다 커진 것 같아 리뷰를 해주시는 분들께 죄송하네요 🥲 리뷰를 통해 많은 질문과 커멘트 주시면 많이 배워가도록 하겠습니다!

2023-09-16 08:49 UTC, aiaiaiai1 requested changes
레전드 코드... 레전드 도메인...
리펙터링 하시느라 고생 많으셨습니다 
어떤 한권의 책를 새롭게 읽는 느낌이였는데 책 내용이 좀 고급진(?) 느낌이였습니다 ㅋㅋ
이걸 어떻게 다 하신건지...
몇가지 궁금한점과 코멘트 남겨드렸는데 혹시 추가적으로 어떤 부분에 대해서 코드리뷰를 좀더 받고싶은부분 있으시면 다음 요청때 리뷰 다시 함 해볼께요!
수고많으셨습니다 👍 👍

2023-09-16 08:49 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                .from(post)
Q.
`distinct`가 빠진거같은데 여기는 없어도 되나요?

2023-09-16 08:49 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
> +            nativeQuery = true
ㅎㄷㄷ 이게 머죠

2023-09-16 08:49 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
> +    DUPLICATE_UPDATE_POST_OPTION(517, "게시글 옵션을 중복해서 수정할 수 없습니다."),
P3
게시글 옵션에 대한 예외는 PostOptionExcpetion으로 따로 분리하는건 어떤가요?

2023-09-16 09:01 UTC, jeomxon requested changes
엄청난 양의 리팩터링을 진행해주셨군요..ㅎㅎ
이렇게 변경하기도 힘들텐데 정말 고생 많으셨습니다!

전반적으로 보면서 느낀 것은 전체적인 컨벤션 통일과 가독성을 올리는 메서드 분리라고 느끼고 해당 부분을 중점적으로 코멘트 남겨봤어요.
많은 양의 코드를 분리, 수정했음에도 깔끔하게 바꿔주신 것 같아서 인상깊었고, 코드 한줄한줄에서 리팩터링에 대한 고민의 흔적이 느껴졌던 것 같아요.
코드량이 많아서 제대로 확인 못한 부분도 있는데, 세세하게 보지 못했던 부분은 다시한번 읽으면서 추가로 코멘트 남겨볼게요!
현재는 테스트를 제외하고 한번 쭉 읽으면서 남길만한 코멘트들을 남겨봤습니다!
코멘트 확인에도 많은 노력이 들 것 같아 최대한 칭찬은 아꼈습니다! 칭찬 드릴 부분이 너무 많고 배웠던 부분도 많은데 다 표현하지 못해서 아쉽네요..ㅎㅎ

정말 고생하셨습니다!!

2023-09-16 09:45 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
`@Entity` 필드는 자동으로 테이블과 매핑이 되기에 이름이나 별다른 속성이 없으면 제거해도 괜찮을 것 같아서 삭제했습니다 ㅎㅎ

2023-09-16 09:47 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
> +    void deleteAllWithPostIdInBatch(@Param("postId") final Long postId);
`In`도 좋은 것 같습니다! 하지만 뒤에 `InBatch`가 사용되고 있어 `In`이 반복되는 느낌이 들어 `With`를 사용했습니다 :)

2023-09-16 09:47 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +        addPostOptions(post, postCreate.getPostOptions());
다 같이 얘기해보면 좋을 것 같아요 👍

2023-09-16 10:05 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostDeadline.java
> +        }
해당 부분도 검증이 필요한 것 같습니다 ! 그렇게 구현해보았는데, 마감된 게시글을 생성할 수가 없어 마감된 게시글에 대한 테스트가 어려워지더라구요 🥲

이 부분은 어떻게 해결할 수 있을까요?!

2023-09-16 10:08 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
해당 메서드에서는 인덱스를 알기보다는 `sequence`를 아는 것이 훨씬 좋은 것 같네요 👍👍

2023-09-16 10:13 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentControllerDocs.java
> +            @Valid final CommentCreateRequest commentCreateRequest,
`@PathVariable` 등과 같이 `ArgumentResolver`가 생성해주지 않는 매개변수들은 컨트롤러 레벨에 `@Validated` 어노테이션을 붙임으로 검증할 수 있는데, 컨트롤러 레벨에 해당 어노테이션을 붙이게 되면 컨트롤러가 구현하는 인터페이스에도 동일하게 어노테이션을 적용해주어야 같은 메서드로 인식했습니다! 따라서 필요한 어노테이션을 붙이도록 하였습니다 :)

2023-09-16 10:24 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/post/PostOptionCreateRequest.java
> +@Setter
`@ModelAttribute`의 경우 기본 생성자가 있는 경우 기본 생성자와 setter를 사용하고, 다른 생성자가 존재하는 경우 해당 생성자로 필드를 초기화하고 초기화하지 않은 필드에 대해서는 setter를 통해 초기화를 진행합니다.

그렇기에 전체 생성자와 getter만 있어도 된다고 생각하고 사용해보았으나 postOptions를 제대로 초기화하지 못해 예외가 발생하였습니다 🥲 정확한 원인은 파악하지 못했는데 혹시 왜 그런지 알고 계신가요?

2023-09-16 10:26 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/post/PostOptionCreateRequest.java
> +    @Schema(description = "게시글 옵션 이미지 파일", example = "votogether.png")
https://github.com/woowacourse-teams/2023-votogether/pull/549#discussion_r1327943578

위의 이유로 인해 `@Setter` 사용이 필요하였고 record 클래스가 아닌 일반 클래스로 dto를 구현하게 되었습니다. 추가적으로 필드가 final인 경우 setter가 동작하지 않기 때문에 해당 키워드를 사용하지 않았습니다!

2023-09-16 10:28 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
> +                .from(post)
1:N 관계의 조인이 발생하지 않기 때문에 중복되는 데이터가 발생하지 않아 `distinct`를 제거하였습니다 😀

2023-09-16 10:30 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
> +            nativeQuery = true
기존 자바 코드에서 처리하던 부분을 쿼리로 옮기도록 수정하였습니다! 연령대별 투표 횟수만 필요한 상황인데 자바에서 해당 로직을 처리하게 되면 모든 투표 `Entity`를 생성하게 됩니다. 먼 미래의 일이긴 하지만 투표가 1억건대로 많은 상황인 경우 모든 투표 객체를 생성해야하기에 메모리가 부족해지는 문제도 발생할 수 있다고 생각하였습니다.

따라서 필요한 정보만 쿼리를 통해 가져올 수 있도록 네이티브 쿼리를 작성하는 방식을 선택하였습니다 🤓 하지만 가독성적인 부분이 좋지 않은 것 같아서 이 부분에 대해서는 추가적인 고민이 필요할 것 같아요 🥲

2023-09-16 10:31 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
> +    DUPLICATE_UPDATE_POST_OPTION(517, "게시글 옵션을 중복해서 수정할 수 없습니다."),
좋습니다 😎👍

2023-09-16 10:43 UTC, tjdtls690 requested changes
다즐 구현하느라 정말 수고하셨습니다. 코드보고 많이 배웠어요.
역시 ㅡ 즐 ㅡ

2023-09-16 10:43 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +        }
```P2```
```suggestion
        if (postContentImage == null && updatedImageUrl != null) {
            post.addContentImage(updatedImageUrl);
            return;
        }
        
        updateExistingPostContentImage(post, postContentImage, updatedImageUrl);
```

이런식으로 Early Return 방식을 사용하는 것은 어떨까요. 물론 if 중첩이 크게 없어서 가독성 차이가 별로 나진 않지만, 저는 나중을 위해서라도 되도록이면 처음 코드를 작성할 때부터 else 문은 쓰지 않는 것을 권장하는 편입니다.

2023-09-16 10:43 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +        }
```P2```
ditto

2023-09-16 10:43 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
```Q```
이 검증 로직은 deletePost 메서드에서만 사용되고 있는데, deletePost 메서드 바로 밑에 두는 것이 저희가 정한 컨벤션에 맞다고는 생각합니다. 하지만 가독성 측면에서 봤을 땐, 여러 검증 로직 메서드들과 같이 두는 것도 나쁘진 않다는 생각이 드네요.

이에 대한 다즐의 의견이 궁금합니다 :)

2023-09-16 10:43 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    private void deletePost(final Long postId, final List<String> postContentImagePaths) {
```P1```
'report_type'이 'POST'와 같고 'target_id'가 '지우려는 Post의 ID'와 같은 Report도 삭제해주어야 할 것 같아요!

2023-09-17 07:03 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommandController.java
> +@Validated
`@Validated`는 스프링에서 제공하는 기능으로 바인딩 과정에서 검증이 이루어지는 것이 아닌 `AOP` 기술을 통해 검증이 진행되게 됩니다.

`@Valid`는 기본적으로 컨트롤러에서만 동작하며 Java Bean 객체만 검증하기 때문에 Dto가 아닌 `@PathVariable`, `@RequestParm`의 검증은 수행할 수 없기에 해당 값들을 검증하기 위해 추가적인 어노테이션을 사용하였습니다!

2023-09-17 07:05 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/post/PostCreateRequest.java
> +public class PostCreateRequest {
https://github.com/woowacourse-teams/2023-votogether/pull/549#discussion_r1327943578

위의 커멘트와 관련있습니다! `@AllArgsConstructor`와 `@Getter`로 동작하지 않아서 `record`를 사용할 수 없어서 변경하였습니다. 혹시 왜 위의 방식대로 동작하지 않는지 알고 계신가요 🥲

2023-09-17 07:10 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/comment/Comment.java
> +@EqualsAndHashCode(of = {"id"}, callSuper = false)
`Entity`의 식별자가 `ID`이기 때문에 `id`로 동등성을 비교하는 것이 편리하여 보통 지정해서 사용하는 편입니다 🤓

2023-09-17 07:11 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostContentImage.java
> +    public void updateImageUrl(final String imagePath) {
인텔리제이를 통한 수정 기능을 사용하다보니 의도하지 않게 변수명이 변경된 경우인 것 같습니다 😂 원래대로 수정하였습니다 :)

2023-09-17 07:12 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostDeadline.java
> +
https://github.com/woowacourse-teams/2023-votogether/pull/549#discussion_r1327941802

위의 커멘트와 관련있는 부분입니다! 마감시간을 원하는대로 설정할 수 없어 마감된 게시글에 대한 테스트가 어려워졌습니다 🥲

테스트까지 용이하게 만들 방법이 있을지 궁금합니다!

2023-09-17 07:13 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
> +
투표 옵션이 조회되는 경우 해당 옵션에 대한 투표 수까지 함께 필요한 경우가 많았기에, 투표 옵션을 조회할 때는 항상 해당 투표 수를 조회하도록 구현하였습니다!

2023-09-17 07:14 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
> +    ;
큰 의도를 가지고 작명하지는 않았습니다! 먼저 예외 메시지를 작성한 뒤 해당 메시지에 알맞은 `Enum`명을 정하도록 했습니다 :)

2023-09-17 07:21 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/CommentRepository.java
> +    @Modifying(flushAutomatically = true, clearAutomatically = true)
우선 `@Query` 어노테이션을 사용하여 `INSERT`, `UPDATE`, `DELETE` 동작을 수행할 때는 `@Modifying` 어노테이션이 필요합니다. 해당 방식을 사용하면 영속성 컨텍스트를 거치는 것이 아닌 DB로 직접 쿼리가 전달되게 되어 영속성 컨텍스트와 데이터 불일치 문제가 발생할 수 있습니다. 이를 막고자 변경 사항을 flush하고 영속성 컨텍스트를 비워주는 옵션을 설정하게 되었습니다.

2023-09-17 07:22 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/repository/PostCustomRepositoryImpl.java
>              final Pageable pageable
내가 작성한 게시글 조회 시에는 카테고리 필터링이 들어가지 않기 때문에 제외하도록 하였습니다 :)

2023-09-17 07:23 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    @Transactional
해당 이야기가 나오기 전에 작성한 코드라 기존 컨벤션인 메서드마다 붙이는 방식으로 진행하고 있었습니다. 전체적으로 수정하였습니다 🤓

2023-09-17 07:27 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/repository/dto/VoteCountByAgeGroupAndGenderDto.java
> +    @QueryProjection
`Querydsl`을 사용할 때 반환값을 `dto`로 생성하고자 하는 경우 `dto` 생성자에 해당 어노테이션을 붙여줘야 사용할 수 있습니다!

2023-09-17 07:31 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/dto/request/comment/CommentCreateRequest.java
> +public record CommentCreateRequest(
프론트와 함께 정한 API 명세로 인해 body로 데이터를 전달하기로 하였고, dto 형태가 되어야 Bean Validation도 진행할 수 있기에 객체로 받도록 하였습니다 :)

2023-09-17 07:33 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        validateWriter(comment, loginMember);
객체는 상태에 대한 것만을 응답하고, 상태에 따라 예외 상황으로 볼지에 대한 판단은 서비스 계층에서 하는 것이 적절하다고 생각해서 도메인에서는 상태에 대한 응답을 전달하고 예외는 서비스에서 던지도록 구현하였습니다 :)

2023-09-17 07:34 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        validateWriter(comment, loginMember);
도메인의 상태가 항상 예외 상황이 아닌 경우도 있을 것 같아요. 어떤 로직에서는 해당 상태가 예외가 될 수 있지만, 어떤 로직에서는 해당 상태가 예외가 아닌 상황도 충분히 발생할 수 있을 것이라고 생각이 들어요!

2023-09-17 07:38 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
체고입니다 아벨 👍👍

2023-09-17 07:44 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
말씀해주신대로 검증 로직이 많이 존재하고 있기에 응집성 측면에서 같이 두는 것이 좋아보여요 😄

2023-09-17 08:12 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    private void deletePost(final Long postId, final List<String> postContentImagePaths) {
생각지도 못했던 부분인데 꼼꼼하게 잘 잡아주셨네요 👍 감사합니다 ㅎㅎ

2023-09-17 08:24 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
말씀해주신대로 정상적인 상황일 때 새로 생긴 옵션이라면 `null`이 오도록 구현되어있습니다! 2가지 방법 중 존재하지 않는 ID가 왔을 경우 올바르지 않은 상황으로 보고 예외를 던지는 것이 더 적절하다 생각하여 해당 방식으로 수정이 필요할 것 같네요 :)

감사합니다 ㅎㅎ

2023-09-17 16:53 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommandController.java
> +@Validated
오 처음 알게된 사실이네요..!
설명 감사합니다 새로운 걸 배워가네요

2023-09-17 18:54 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/PostDeadline.java
> +        }
음... 리플렉션??

2023-09-17 19:18 UTC, aiaiaiai1 approved these changes
다즐 질문답변과 리뷰반영하시느라 고생많으셨습니다! 👍👍  
빨리 배포됐음 좋겠네요! 근데 그 컨플릭트.. 어마무시한거같던데 .. 화이팅..입니다..!!

2023-09-18 05:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/controller/PostGuestController.java
> +public class PostGuestController implements PostGuestControllerDocs {
```P1```
PostGuestController -> PostGuestQueryController 로 변경해주어야 할 것 같아요.

2023-09-18 05:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/controller/PostCommentController.java
>      private final PostCommentService postCommentService;
```P1```
Query, Command로 나누어주어야 할 부분이 2가지 보여요!
1. PostCommentController -> PostCommentCommandController, PostCommentQueryController
2. PostCommentService -> PostCommentCommandService, PostCommentQueryService

2023-09-18 05:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostGuestService.java
> +public class PostGuestService {
```P1```
PostGuestService -> PostGuestQueryService 변경 후 @Transactional(readOnly = true)를 클래스 위에 붙여주면 될 것 같아요 :)

2023-09-18 05:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
```P1```
위에서 얘기한 것처럼 PostCommentService가 아직 Command, Query로 안나누어진 것 같아요 :)

2023-09-18 05:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        validateWriter(comment, loginMember);
사실 지금도 많이 헷갈리네요. 어떤 상황에 대한 판단(true or false)까지는 도메인의 역할이 확실하다고 주장할 수 있지만, throw를 통해 예외를 던지는 행위 자체는 도메인의 역할로 볼 수 있을까? 아니면 지금처럼 Service 계층에서 던져주어야 할까? 라는 고민이 가장 큽니다.

제가 직접적으로 느낀 장단점을 말해보자면,

서비스 계층에서 예외를 던지는 입장에서의 장단점
장점
1. 서비스 계층의 한 부분에 예외 처리 로직을 응집시킬 수 있어서 파악하기 편할 수 있다.
2. 각 도메인 객체들이 상태에 대한 부분만을 갖고 있을 수 있다.

단점
1. 예외 처리 상황이 많아지면 Service의 크기가 기하급수적으로 커질 수 있다.
2. 여러 상태(도메인)에 대한 예외 처리 로직을 하나의 Service가 모두 갖고 있어서 오히려 가독성이 떨어질 수 있다.

이에 대한 다즐의 의견이 궁금합니다.

2023-09-18 05:40 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
```P2```
```suggestion
private List<PostOptionUpdateRequest> extractPostOptionAdds(
        final Set<Long> postOptionIds,
        final List<PostOptionUpdateRequest> postOptionUpdates
) {
    validatePostOptionIds(postOptionIds, postOptionUpdates);

    return postOptionUpdates.stream()
            .filter(postOptionUpdate -> postOptionUpdate.getId() == null)
            .toList();
}

private void validatePostOptionIds(
        final Set<Long> postOptionIds,
        final List<PostOptionUpdateRequest> postOptionUpdates
) {
    boolean hasInvalidId = postOptionUpdates.stream()
            .map(PostOptionUpdateRequest::getId)
            .anyMatch(id -> id != null && !postOptionIds.contains(id));

    if (hasInvalidId) {
        throw new BadRequestException(PostOptionExceptionType.UNRELATED_POST_OPTION);
    }
}
```

이런 식으로 분리해준다면 메인 메서드는 주된 로직에만 더 집중하고 유효성 검증 로직도 따로 분리하여 더 명확해 질 수 있을 것 같은데 어떻게 생각하시나요 :)

2023-09-18 05:48 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +                        postOptionUpdate -> postOptionUpdate,
```Q```
이 부분에서 Function.identity()를 쓰기엔 가독성 측면에서 좀 안좋게 느껴지는지 궁금합니다.

2023-09-18 05:48 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
> +
다만 voteCount라는 점에서 `Long`타입으로 변경하면 어떨까? 라는 생각이 드네요.
또한 primitive 타입으로 지정하신 이유가 있을까요?

2023-09-18 05:51 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/exception/PostExceptionType.java
> +    ;
예외 클래스에 대한 메시지를 어떻게 일관성 있게  네이밍 할 수 있을지 생각해보았는데,
PostException.~~라는 방식을 사용하기 때문에 리팩터링 하는 과정에서 POST라는 단어를 제외하는 것이 좋을 것 같다고 생각했어요.
중복되는 단어를 제외시켜준다면 코드의 가독성 또한 증가할 것이라는 생각도 들었구요.

2023-09-18 05:51 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
혹은 이러한 방식도 생각해볼 수 있을 것 같아요.
```suggestion
private List<PostOptionUpdateRequest> extractPostOptionAdds(
        final Set<Long> postOptionIds,
        final List<PostOptionUpdateRequest> postOptionUpdates
) {
    validatePostOptionIds(postOptionIds, postOptionUpdates);

    return postOptionUpdates.stream()
            .filter(postOptionUpdate -> postOptionUpdate.getId() == null)
            .toList();
}

private void validatePostOptionIds(
        final Set<Long> postOptionIds,
        final List<PostOptionUpdateRequest> postOptionUpdates
) {
    postOptionUpdates.stream()
            .map(PostOptionUpdateRequest::getId)
            .filter(Objects::nonNull)
            .filter(id -> !postOptionIds.contains(id))
            .findFirst()
            .ifPresent(invalidId -> {
                throw new BadRequestException(PostOptionExceptionType.UNRELATED_POST_OPTION);
            });
}
```

2023-09-18 05:53 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/post/dto/request/post/PostCreateRequest.java
> +public class PostCreateRequest {
ModelAttribute를 거의 사용해본 적이 없어서 그런 문제가 있는지 몰랐네요...
저도 이 부분은 좀 더 공부해야봐야할 것 같아요.

2023-09-19 01:43 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
> +
`long` 타입으로 변환 좋습니다 😙

`primitive` 타입으로 정한 이유는 `null`이 될 수 없는 값이기에 `null`이 될 수 없음을 명시적으로 나타내고자 했습니다 !

2023-09-19 01:51 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommentService.java
> +        validateWriter(comment, loginMember);
사실 이 부분을 명확하게 결정하기는 어려운 부분인 것 같아요 🥲

각각의 장단점은 아벨이 말해준 것처럼 명확해보여서 장단점에 맞게 트레이드 오프를 하면서 상황에 맞게 적절한 방법을 선택해 나가는 것이 중요할 것 같아요 :)

2023-09-19 01:52 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostGuestService.java
> +public class PostGuestService {
현재는 해당 `PR`이 빨리 머지되는 것이 더 우선시되는 상황인 것 같아 해당 부분은 나중에 전체적으로 `Query`와 `Command`를 분리하면서 수정하도록 하겠습니다 !

2023-09-19 02:02 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +    }
스트림 활용을 너무 잘 하시네요 👍👍

2023-09-19 02:04 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostCommandService.java
> +                        postOptionUpdate -> postOptionUpdate,
이 부분 고민해봤는데 가독성이 너무 안좋더라구요 🥲 따라서 명시하는 방법을 선택했습니다 :)

2023-09-19 03:21 UTC, jeomxon approved these changes
8천줄의 레전드 리팩터링을 하시느라 고생하셨습니다..!
🔥좋은 코드 덕분에 저도 많이 배웠네요 ㅎㅎ🔥
이만 approve하겠습니다 :)

2023-09-19 03:39 UTC, tjdtls690 approved these changes
많은 코드 리뷰 받고 수정하시느라 고생 많으셨어요!! 역시 ㅡ 즐 ㅡ

2023-09-19 06:13 UTC, merged