Refactor/#686
woowacourse-teams/2023-votogether pull request #721
Opened 2023-10-06 09:56 UTC by inyeong-kang

## 🔥 연관 이슈

close: #686
close: #709

## 📝 작업 요약
* TwoButtonModal 을 기존의 Modal 로 대체
* 마감시간 사용자지정 모달에서 초기화 버튼이 모달 밖으로 튀어나오는 UI 버그 해결

## ⏰ 소요 시간
* 1일 (반응형 같이 css 관련 삽질한 부분이 있었습니다..😂)

## 🔎 작업 상세 설명
* 기존 TwoButtonModal 모습
![image](https://github.com/woowacourse-teams/2023-votogether/assets/81199414/57f74b7b-e96a-4121-8664-8b1526a6276c)
* TwoButtonModal을 Modal 로 대체한 모습
![image](https://github.com/woowacourse-teams/2023-votogether/assets/81199414/ad3bf98b-a545-4808-bdde-0721700f7a04)

## 🌟 논의 사항
* 모달의 종류와 쓰임새에 대해 잘 정리한 글이 있어 공유합니다!
https://brunch.co.kr/@tigrisdesign/3
* Skyscanner가 Modal 에 대한 문서화가 굉장히 꼼꼼해서 공유합니다😀
https://backpack.github.io/storybook/?path=/story/bpk-component-modal-v2--multiple-modals

2023-10-06 20:34 UTC, Gilpop8663 requested changes
그리고 현재 모달은 div로 되어 있는데요 dialog 태그를 사용하면 웹 접근성을 좀 더 챙길 수 있을 것 같아요

dialog 태그를 사용하게 되면 탭 인덱스가 모달 내부에서만 동작하도록 되어서 불필요한 정보를 덜 주게 되어서 사용자가 헷갈리지 않을 것 같습니다



dialog로 만든 모달 예시) Drawer

https://github.com/woowacourse-teams/2023-votogether/assets/80146176/cf2d43e2-8088-4134-be96-695bfd5047aa

https://github.com/woowacourse-teams/2023-votogether/assets/80146176/88644eed-6016-434f-8028-bed35246430b



현재 구현된 모달


https://github.com/woowacourse-teams/2023-votogether/assets/80146176/9f82549c-5901-425d-b376-88a0518dd920


https://github.com/woowacourse-teams/2023-votogether/assets/80146176/ba579f9c-188f-45fa-8bb1-b57c928ff456


현재 삭제 모달을 dialog로 변경해서 적용해본 예시



https://github.com/woowacourse-teams/2023-votogether/assets/80146176/c65c313b-c249-42b3-af05-1a6e879e17d7


dialog 태그로 변경하는 것은 제안이라서 가볍게 들으셔도 좋아요!! 


-------------

또 다른 제안으로는 esc로 모달을 닫을 수 있으면 좋겠습니당
현재는 esc 이벤트는 없어서 아쉽다고 느꼈어요

2023-10-06 20:37 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-12 06:29 UTC, chsua reviewed
모달이 여러 개였는데 가장 기본형 모달이 생겨서 좋네요!
다른 곳에서 모달을 사용할 일이 있다면 이걸 사용하면 될 것 같아요.
코드가 깔끔해지는 것을 보며 리팩토링이 중요하구나 느꼈습니다.

궁금한 점 등을 코멘트 달았습니다.
우스가 말씀하셨던 "두번째 버튼"이 취소버튼과 동일한 역할로 취급되는 것 같아서 그부분만 이야기를 나누어보면 좋을 것 같아요!

2023-10-12 06:29 UTC, chsua commented on frontend/src/components/common/Accordion/Accordion.stories.tsx
> -            <ModalTitle>정말 탈퇴하시겠어요?</ModalTitle>
훨씬 깔끔해졌어요!

2023-10-12 06:29 UTC, chsua commented on frontend/src/components/common/DeleteModal/index.tsx
> +      >{`${TARGET_FOR_DELETE[target]} 삭제하시겠습니까?\n삭제 버튼 클릭 시 취소할 수 없습니다.`}</S.Description>
혹시 이렇게 되면 ```계정 삭제하시겠습니까?``` 이렇게 나오나요?

2023-10-12 06:29 UTC, chsua commented on frontend/src/components/common/Modal/index.tsx
> +        secondaryClick();
저도 버튼으로 어느 위치에 "닫기"가 올지 모른다고 생각이 들어서 
props로 closeEvent를 내려받아서 esc, 배경클릭에 대한 이벤트를 대응하는 것이 어떨까 생각이 들어요~
아니면 두번째 버튼은 아예 닫기 버튼으로 고정시키는 게 좋을 것 같아요.

혹시 인지하지 못하고 다른 버튼 이벤트를 두번째로 내려줬다가 잘못 실행될 것 같아요.

2023-10-12 06:29 UTC, chsua commented on frontend/src/components/common/Modal/index.tsx
> +        <S.Body>{children}</S.Body>
크게 상관 없는 부분이지만 children이 없는 경우가 있는데 
```{ children && <S.Body>{children}</S.Body> } ```
이렇게 처리하지 않으신 이유가 있나요? 
min-hight가 100%로 들어가있던데 관련이 있나요?

2023-10-12 06:29 UTC, chsua commented on frontend/src/components/common/Modal/style.ts
> +    max-width: 500px;
가로길이가 많이 설정되어서 어떻게 되는건지 잘 모르겠어요😂

2023-10-12 06:30 UTC, chsua commented
fe-리뷰완

2023-10-18 06:05 UTC, inyeong-kang commented on frontend/src/components/common/DeleteModal/style.ts
> +  font-size: 14px;
`--text-caption: 400 1.6rem/2rem san-serif;` 에서 font-size 가 원하는 크기보다는 살짝 커서 14px 로 수정했어요..!

2023-10-18 06:32 UTC, inyeong-kang commented on frontend/src/components/common/Modal/index.tsx
> +        secondaryClick();
기존에 있는 onModalClose를 부활시켰습니다😂
`handleModalClose` 로 닫기에 대해 대응할 수 있도록 해줬어요!

2023-10-18 06:35 UTC, inyeong-kang commented on frontend/src/components/common/Modal/style.ts
> +  }
넵 말씀하신 대로 의도한 것이 맞습니다. 잠깐 헷갈렸었나 봐요..ㅎㅎㅎ 
아래처럼 수정했어요!
```tsx
export const Container = styled.dialog<{ size: Size }>`
  display: flex;
  flex-direction: column;
  justify-content: space-between;

  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

  width: ${props => (props.size ? MODAL_SIZE[props.size] : '96%')};
  max-width: 290px;
  border-radius: 12px;
  border: 2px solid #f6f6f6;
  padding-left: 5px 0 0 10px;

  background-color: white;

  box-shadow: 0 0 6px 0 rgba(0, 0, 0, 0.5);

  @media (min-width: ${theme.breakpoint.sm}) {
    width: 50%;
    max-width: 500px;
  }
`;
```

2023-10-18 06:36 UTC, inyeong-kang commented on frontend/src/components/common/TimePickerOptionList/style.ts
> +  font-size: 14px;
요거도 같은 이유입니다~ (--text-caption: 400 1.6rem/2rem san-serif; 에서 font-size 가 원하는 크기보다는 살짝 커서 14px 로 수정했어요..!)

2023-10-18 06:36 UTC, inyeong-kang commented on frontend/src/components/common/DeleteModal/index.tsx
> +      >{`${TARGET_FOR_DELETE[target]} 삭제하시겠습니까?\n삭제 버튼 클릭 시 취소할 수 없습니다.`}</S.Description>
넵 맞습니다~

2023-10-18 06:38 UTC, inyeong-kang commented on frontend/src/components/common/Modal/index.tsx
> +        <S.Body>{children}</S.Body>
음 생각해보니 PropsWithChildren이라 children을 안넣는 경우도 있겠네요!
말씀해주신 부분 반영하겠습니다😄

2023-10-18 06:40 UTC, inyeong-kang commented on frontend/src/components/common/Modal/index.tsx
> +        <S.Body>{children}</S.Body>
`min-height`도 삭제해줬습니다! (Modal에 내용 없이 버튼만 넣고 싶은 경우도 고려해야 하므로...)

2023-10-18 06:42 UTC, inyeong-kang commented on frontend/src/components/common/Modal/style.ts
> +    max-width: 500px;
ㅎㅎㅎ인정합니다...(저도 코드 쓰면서 헷갈렸어요😂) 우스도 이 부분 코멘트 주셔서 수정했어요!

2023-10-18 06:51 UTC, inyeong-kang commented
1. Modal의 props로 handleModalClose 추가 (여기에 모달 닫기 관련 함수 할당)
2. Modal의 width 관련 스타일 수정

fe-리뷰완

2023-10-18 20:54 UTC, Gilpop8663 approved these changes
코드 확인 후 어프로브 했습니다

최고!

fe-리뷰완

2023-10-18 20:54 UTC, Gilpop8663 commented on frontend/src/components/common/Modal/style.ts
> +  margin-bottom: 16px;
이 부분도 아래와 같이 한줄로 사용할 수 있겠어요

2023-10-18 20:54 UTC, Gilpop8663 commented on frontend/src/components/common/Modal/style.ts
> +  padding-left: 5px 0 0 10px;
혹시 padding-left가 아니라 padding 아닌가요?

2023-10-18 20:54 UTC, Gilpop8663 commented on frontend/src/components/common/Modal/index.tsx
>        <S.Container tabIndex={0} size={size}>
dialog로 바뀌었는데 open이라는 속성 없이도 잘 보이네요!  신기한데용

2023-10-18 20:56 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-19 02:30 UTC, inyeong-kang commented on frontend/src/components/common/Modal/style.ts
> +  padding-left: 5px 0 0 10px;
오.... 매의 눈 감사합니다 ㅎㅎ

2023-10-19 02:36 UTC, inyeong-kang commented on frontend/src/components/common/Modal/style.ts
> +  padding-left: 5px 0 0 10px;
그런데 해당 속성은 필요하지 않아져서 삭제했어요~~!

2023-10-19 02:38 UTC, inyeong-kang commented
우스 코멘트 반영했습니다!

fe-리뷰요청

2023-10-19 05:13 UTC, chsua approved these changes
수정된 코드 읽었습니다!
고생하셨습니다!!
최고에요!

2023-10-19 05:13 UTC, merged