토스트 전역에서 조작이 가능하도록 변경
woowacourse-teams/2023-votogether pull request #733
Opened 2023-10-11 16:09 UTC by chsua

## 🔥 연관 이슈

close: #554 : 토스트 전역에서 조작이 가능하도록 변경
close: #677 : [BUG] 카테고리 에러 발생 시 이상하게 보여요
close: #722 : [BUG] 게시글이 삭제되면 404페이지가 아닌 데이터가 불러와지지 않는다는 에러페이지가 뜸
close: #726 : [BUG] 투표 통신 중 다시 투표를 하는 경우 투표요청이 막혔으면 좋겠습니다.

## 📝 작업 요약
1. 토스트 전역으로 이동
2. 에러 아이템 수정
3. 게시글 요청 시 404 status면 리액트 쿼리 재요청 하지 않음
4. 투표 중일 때는 투표 요청 api 통신 하지 않고 토스트 띄움
5. 서스펜스, 에러바운더리 적용 확인 및 미적용 시 적용 처리 

## ⏰ 소요 시간
3일 이상
- 미션과 토스트 setTimeout 오류 등으로 인하여 오래 걸림

## 🔎 작업 상세 설명
1. 토스트 전역으로 이동
    - 처음에 toast-root를 만들었으나 필요가 없어서 삭제
    - contextApi로 하위 컴포넌트에 toast를 추가하는 함수를 내려줌.
    - context에서는 toastList를 상태로 가지고 있음. 마지막으로 들어온 토스트를 기준으로 3초가 지나면 toastList를 비움
    - ```toast component```에서는 isBlind을 상태로 가지고 있어 생성된지 3초가 지나면 ```isBlind=true```가 되어서 ```styled component```로 ```display=none```을 만듦
```js
// hook/context/toast.tsx

    <ToastContext.Provider value={{ addMessage }}>
      <ToastContainer toastList={toastList} />
      {children}
    </ToastContext.Provider>
```

2. 에러 아이템 수정 (동영상 확인해주심 됩니다!)
    - 기본: 에러메세지
    - 선택: 로고 / 홈으로 가기 / 다시 시도
    - 선택사항은 기본이 false이고, props로 true로 내려주면 렌더링됨
    - 적용
        - 카테고리에서는 홈으로 가기, 다시 시도가 필요없다고 생각하여 메세지만
        - 홈페이지 게시글 리스트는 홈으로 가기가 필요없어 로고 + 메세지 + 다시 시도
        - 게시글 상세 페이지는 로고 + 메세지 + 다시 시도 + 홈으로 가기...
        - 기타 적용 

3. 게시글 요청 시 404 status 면 리액트 쿼리 재요청 하지 않음
    - 기존 방식으로는 status를 알 수 없어서 get할때만 status를 포함하는 객체로 error를 던져서 리액트쿼리 훅 안에서 이를 파싱해 판단
    - retry 속성은 오류가 난 경우 재요청을 몇 번 할 것인지 설정하는 속성. 함수 형태로 조건문을 걸어서 404면 재요청 안함, 아니면 3번까지 요청
```js

export const usePostDetail = (isLoggedIn: boolean, postId: number) => {
   ...(생략)

  const { data, isError, isLoading, error } = useQuery<PostInfo>(
    POST_DETAIL_QUERY_KEY,
    () => fetchApi(postId),
    {
      ...
      retry: (failCount, error) => {
        const fetchError = error as Error;
        const status = JSON.parse(fetchError.message).status;
        if (status === 404) {
          return false;
        }
        return failCount <= 3;
      },
    }
  );

   ...
};
```

4. 투표 중일 때는 투표 요청 api 통신 하지 않고 토스트 띄움
    - isLoading을 통해서 막았지만, **효과는 미비했다..!**
    - 현재 데브 서버에서 확인했을 때, 투표(post) > 새로운 포스트 리스트 데이터 불러옴 > 화면에 그려짐  이 흐름인데, 여기서 투표 post가 진행 중일 때 투표를 못하도록 막아도 실상 시간이 지연되는 이유는 새로운 포스트리스트가 만들어져서 데이터가 프론트로 전달되어 화면에 그려지는 것이 오래걸림. 때문에 **서버랑 협의해서 알맞게 에러메세지를 수정해줘야 함**

5. 서스펜스, 에러바운더리 적용 확인 및 미적용 시 적용 처리 
    - 최상단 에러바운더리는 글로벌 스타일이나 라우터를 사용할 수 없어 코드 수정
    - 기존 템플릿 모바일 헤더를 레이아웃으로 이동시키면서 서스펜스와 에러바운더리에서 적용되지 않는 경우가 생김.
    - 그래서 겸사겸사 거의 모든 get api 실패 시 UI를 확인하고 없다면 적용.
    - [동영상이 많아서 노션에 올림 ](https://www.notion.so/bbf777b9a8014d0590cdcb7484e224e2)

## 🌟 논의 사항
혹시 추가로 변경이 필요한 부분이 있다면 말씀해주세요!

2023-10-11 17:14 UTC, Gilpop8663 commented on frontend/src/hooks/context/toast.tsx
> +        if (timeId.current) window.clearTimeout(timeId.current);
if 문안의 settimeout 콜백함수 안의 if문이라서 읽기 어려웠다고 생각이 드는데요

이 부분도 실행된 후에 clearTimeout이라서 이미 실행되어서 취소할 것이 사라진 상태라고 추측이 되어요

코드를 삭제해서 코드 가독성을 좋게 하는것은 어떠세요?

2023-10-11 17:15 UTC, Gilpop8663 commented on frontend/src/hooks/context/toast.tsx
> +    if (toastList.find(toast => toast.text === message)) return;
오! 이렇게 중복을 방지하셨군요 💯💯💯

2023-10-11 17:18 UTC, Gilpop8663 commented on frontend/src/hooks/query/comment/useCreateComment.ts
> +        addMessage('댓글을 작성했습니다.');
댓글 작성이 되었다는 것을 사용자에게 알려주시게 된 이유가 궁금합니다

댓글 리스트가 밑에 길게 있을 때 사용자가 댓글 작성이 성공했는지 확인하러 맨 밑으로 스크롤해야하기 때문인가요?

2023-10-11 17:19 UTC, Gilpop8663 commented on frontend/src/hooks/query/comment/useEditComment.ts
> +        addMessage('댓글을 수성했습니다.');
오타있어요! 수성 => 수정

2023-10-11 17:19 UTC, Gilpop8663 commented on frontend/src/hooks/query/comment/useEditComment.ts
> +        const message = error instanceof Error ? error.message : '댓글 작성을 실패했습니다.';
`댓글 수정을 실패했습니다` 는 어떠세요?

2023-10-11 17:20 UTC, Gilpop8663 commented on frontend/src/hooks/query/post/useCreatePost.ts
> +      const message = error instanceof Error ? error.message : '회원 탈퇴를 실패했습니다.';
오타있습니다

 '회원 탈퇴를 실패했습니다.' => '게시글 작성을 실패했습니다.' 로 바꿔주세용

2023-10-11 17:22 UTC, Gilpop8663 commented on frontend/src/hooks/query/post/useCreateVote.ts
> +      addMessage(message);
원래 있던 console.error 에러 메세지 때문에 헷갈렸네요 😂

투표를 실패했습니다 너무 좋아요 👍👍👍

2023-10-11 17:22 UTC, Gilpop8663 commented on frontend/src/hooks/query/post/useEditPost.ts
> +        const message = error instanceof Error ? error.message : '회원 탈퇴를 실패했습니다.';
'회원 탈퇴를 실패했습니다.' => 게시글 수정을 실패했습니다. 오타요!

2023-10-11 17:31 UTC, Gilpop8663 commented on frontend/src/hooks/query/post/usePostDetail.ts
> +      },
fetch함수에서 보내주는 status를 활용하셨군요! fetchError.message가 어떻게 오는 지 궁금해서 console.log로 확인해봤었어요 ㅎㅎ 좋은데요?! 🌊🌊🌊

![image](https://github.com/woowacourse-teams/2023-votogether/assets/80146176/236ee2e9-3652-4ec0-b3c0-525f949c7fbf)

2023-10-11 17:31 UTC, Gilpop8663 commented on frontend/src/hooks/query/user/useWithdrawalMembership.ts
> +      addMessage('회원 탈퇴을 완료했습니다.');
회원 탈퇴을 => 회원 탈퇴를 은 어떠세요?

2023-10-11 17:33 UTC, Gilpop8663 commented on frontend/src/pages/ErrorBoundaryWithNarrowHeader.tsx
> +
레전드 꼼꼼함 🔥🔥🔥

2023-10-11 17:34 UTC, Gilpop8663 commented on frontend/src/pages/MyInfoPage/index.tsx
> +    useWithdrawalMembership();
컴포넌트에 필요한 것만 불러올 수 있어서 가독성이 크게 좋아진 것으로 느껴져요 🔥🔥🔥

2023-10-11 17:36 UTC, Gilpop8663 commented on frontend/src/pages/post/EditPostPage/index.tsx
> +  const errorText = '요청을 처리할 수 없습니다. 잠시후 다시 시도해주세요.';
중복되어서 사용되는 상수인데 따로 constant에서 관리하는 것은 어떠세요?

2023-10-11 17:40 UTC, Gilpop8663 commented on frontend/src/utils/fetch.ts
>    }
👍👍👍

2023-10-11 17:42 UTC, Gilpop8663 commented on frontend/src/utils/fetch.ts
>      throw new Error(error.message);
수아 덕분에 response.text가 이미 문자열인 줄 알았는데 여기서 한번 더 message로 보내줄 수 있는 걸 알 수 있었어요 👍👍👍

2023-10-11 17:45 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-12 07:24 UTC, chsua commented on frontend/src/components/common/Toast/index.tsx
> +
사실 clearTimeout은 저도 꼭 하지 않아도 된다고 생각을 해요.
다만, 혹시나 사라지지 않고 돌고 있을 경우를 대비해서 넣어논 코드입니다.
간혹 사라지지 않고 setTimeout이 계속 도는 경우 메모리누수가 일어난다고 하더라구요.

아래에 useEffect도 동일한 이유로 clear를 해놓았습니다!

2023-10-12 07:26 UTC, chsua commented on frontend/src/hooks/context/toast.tsx
> +        if (timeId.current) window.clearTimeout(timeId.current);
위와 동일한 이유로 작성해놓은 코드입니다! 
없다고 해서 오류가 나지는 않을 것 같지만 혹시 모를 메모리 누수를 위해 작성한 코드입니다!

2023-10-12 07:28 UTC, chsua commented on frontend/src/hooks/query/comment/useCreateComment.ts
> +        addMessage('댓글을 작성했습니다.');
작성되었다는 것을 알려주는 것이 좋다고 생각되어서 작성한 코드였는데,
막상 여러번 댓글을 작성하려고 하니 오히려 눈에 거슬리네요! 삭제하도록 하겠습니다!

2023-10-12 07:30 UTC, chsua commented on frontend/src/hooks/query/comment/useEditComment.ts
> +        const message = error instanceof Error ? error.message : '댓글 작성을 실패했습니다.';
댓글 작성과 수정/ 게시글 작성과 수정 성공 시 toast 노출 안하는 방향으로 수정했습니다!

2023-10-12 07:38 UTC, chsua commented on frontend/src/hooks/query/post/useEditPost.ts
> +        const message = error instanceof Error ? error.message : '회원 탈퇴를 실패했습니다.';
으악. 고친다는게 그냥 올려버렸네요 bb 꼼꼼함 대단해요

2023-10-12 07:49 UTC, chsua commented on frontend/src/utils/fetch.ts
>      throw new Error(error.message);
그 백엔드에서 에러메세지를 객체 형태로 던져줘서 그걸 풀어야 저희가 원하는 메세지를 얻을 수 있더라구요!
이런거 잘 소통해야 한다는 것을 다시금 느꼈습니다!

2023-10-12 08:49 UTC, inyeong-kang requested changes
와우~~~~ 
# 🎉레전드 리팩터링🎉

삭제된 코드들 보는데 활명수 먹은 기분인걸요?👍👍

미션도 있고 이런저런 것들로 바쁜 와중에 훌륭한 리팩터링 멋져요👏👏
덕분에 에러 처리에 대한 관심사를 UI에서 분리할 수 있어서 코드의 가독성이 크게 높아졌어요!!

에러 메시지 문구나 변수명, onError 관련해서 코멘트 남겼습니다~~

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/components/common/ErrorItem/index.tsx
> +export default function ErrorItem({
원래 ErrorItem? 이라는 네이밍이 왠지 CommentItem 같이 어떤 목록의 자식처럼 느껴지는데, 기존의 ErrorMessage 라는 컴포넌트명을 변경하신 의도가 궁금해요!

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/components/common/Toast/index.tsx
> +  const [isBlind, setIsBlind] = useState(false);
isBlind가 바로 와닿지 않아서 혹시 isShown 어떠신가용?
`const [isShown, setIsBlind] = useState(true);` , 아래 setTimeout 콜백 내에서는 `setIsShown(false)`

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/constants/animation.ts
> + * 토스트가 사용자에게 보여지는 시간(ms단위)을 뜻합니다.
디테일 👍👍👍👍👍

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/hooks/query/category/useCategoryFavoriteToggle.ts
> +        const message = error instanceof Error ? error.message : '카테고리 설정을 실패했습니다.';
보다 정확한 에러 메시지면 좋겠다는 생각이 들어서 아래와 같이 리팩터링한 코드를 제안합니다😀
```tsx
export const useCategoryFavoriteToggle = () => {
  const queryClient = useQueryClient();
  const { addMessage } = useContext(ToastContext);
  const LOGGED_IN = true;
  const queryKey = [QUERY_KEY.CATEGORIES, LOGGED_IN];

  const { mutate, isLoading } = useMutation(
    ({ id, isFavorite }: Omit<Category, 'name'>) =>
      isFavorite ? removeFavoriteCategory(id) : addFavoriteCategory(id),
    {
      onMutate: async ({ id, isFavorite }: Omit<Category, 'name'>) => {  // ❗❗ isFavorite 키 추가
        const oldCategoryList: Category[] | undefined = queryClient.getQueryData(queryKey);

        if (oldCategoryList) {
          await queryClient.cancelQueries(queryKey);
          const updatedCategoryList = oldCategoryList.map(item =>
            item.id === id ? { ...item, isFavorite: !item.isFavorite } : item
          );
          queryClient.setQueryData(queryKey, updatedCategoryList);
          // ❗❗ context를 return 해주는데, 기존에는 콜백함수 하나였지만 isFavorite 이라는 boolean 값도 함께 반환해주기
          return { isFavorite, () => queryClient.setQueryData(queryKey, oldCategoryList) };
        }
      },
      onError: (error, _, context) => {
        if (context) {
          context.rollback();
          const message = error instanceof Error ? error.message : `카테고리 즐겨찾기 ${context.isFavorite ? 해제' : '등록'}을 실패했습니다.`;  // ❗❗ 기존 isFavorite 값이 true였다면, 즐겨찾기 해제 요청을 한 것임
          addMessage(message);
          return;
        };
      },
      onSettled: () => {
        queryClient.invalidateQueries(queryKey);
      },
    }
  );

  return { mutate, isLoading };
};
```

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/hooks/query/comment/useCreateComment.ts
> +        addMessage('댓글을 작성했습니다.');
저도 궁금해요~~ (근데 우스 코멘트 보고 생각난건데 댓글 달면 맨 아래로 스크롤 자동으로 되게 해주는 것도 좋겠는걸요?)

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/hooks/query/post/useEditPost.ts
> +        const message = error instanceof Error ? error.message : '회원 탈퇴를 실패했습니다.';
우스 매의 눈이시군요?👏👏

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/pages/ErrorBoundaryWithNarrowHeader.tsx
> +              text="해당 페이지는 존재하지 않습니다. 확인 후 다시 요청해주세요."
`확인 후 다시 요청해주세요.` 문구를

`페이지 경로(또는 URL)를 정확히 입력해주세요.` 또는 `올바른 페이지 경로인지 확인해주세요.`

같은 문구로 대체하는 것은 어떠신가용?

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/pages/MyInfoPage/index.tsx
> +    useWithdrawalMembership();
인정합니다

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/pages/post/EditPostPage/index.tsx
> +  const errorText = '요청을 처리할 수 없습니다. 잠시후 다시 시도해주세요.';
잠시후 -> 잠시 후 
로 띄어쓰기 부탁합니다...ㅎㅎ

2023-10-12 08:49 UTC, inyeong-kang commented on frontend/src/pages/user/RegisterPersonalInfoPage/index.tsx
> +    addMessage('개인 정보를 이미 등록 완료하셨습니다.');
오~~~ 👍👍👏👏👏

2023-10-15 17:39 UTC, chsua commented on frontend/src/components/comment/CommentList/CommentItem/index.tsx
> +  const { addMessage } = useContext(ToastContext);
행위가 토스트 메세지 리스트에 메세지를 추가하는 것으로 변경되어서 함수명을 변경했습니다.
변경해야지,하고 변경한게 아니라 로직을 수정하는 과정에서 어울리는 함수명으로 변경하다보니 동일한 작업을 하지만 함수명이 변경되었네요ㅎㅎㅎ 혹시 이전 함수명이 더 이해하기 쉬우신가요??

2023-10-15 17:40 UTC, chsua commented on frontend/src/components/common/ErrorItem/index.tsx
> +  haveIcon?: boolean;
오 특별한 이유는 없습니다. 대체로 has를 많이 사용하나요??

2023-10-15 17:42 UTC, chsua commented on frontend/src/components/common/ErrorItem/index.tsx
> +export default function ErrorItem({
해당 컴포넌트가 메세지라는 이름을 가지기에는 내부에 많은 것들이 들어가 있습니다!
특히 홈페이지로 가는 버튼이나 로고 등을 가지고 있다는 점에서 하나의 item같다고 생각했습니다.
메세지는.. 그보다는 정말 text만 들어갈 것이라고 이해되어서 적절하지 않다고 느껴 변경했습니다.
혹시 더 적절한 네이밍이 있을까요?

2023-10-15 18:00 UTC, chsua commented
fe-리뷰요청

에러 메세지 등을 수정하였습니다!
코멘트 읽고 궁금한 점이나 답변 달았습니다! 확인 부탁드려요!

2023-10-16 17:54 UTC, inyeong-kang commented on frontend/src/components/common/ErrorItem/index.tsx
> +  haveIcon?: boolean;
백엔드에서 has- 라는 prefix를 많이 사용하셔서 has prefix가 일반적인 것으로 이해했어요 ㅋㅋㅋ 
근데 아이콘이 한 개가 아니라 다수일 수도 있다는 점에서 그대로 유지해도 되겠네요!!

2023-10-16 17:56 UTC, inyeong-kang commented on frontend/src/components/common/ErrorItem/index.tsx
> +export default function ErrorItem({
흠....... 저도 딱 좋은 네이밍이 떠오르지 않네요😅 
일단 유지해도 될거 같아요~~

2023-10-16 17:58 UTC, inyeong-kang commented
반영하신 코드 확인했습니다~~ 코멘트 하나 남긴거 봐주실 수 있나용?
https://github.com/woowacourse-teams/2023-votogether/pull/733#discussion_r1361057069

충돌이 많은데 무사히 해결되길 바랍니다... 대규모 리팩터링 고생 많으셨어유👍👍

fe-리뷰완

2023-10-17 01:41 UTC, Gilpop8663 approved these changes
코드 변경된 부분 확인하여 어프로브 했습니다 '👍👍👍

2023-10-17 01:41 UTC, Gilpop8663 commented on frontend/src/hooks/query/category/useCategoryFavoriteToggle.ts
> +            rollback: () => queryClient.setQueryData(queryKey, oldCategoryList),
rollback 사용 방법을 알게 되었어요 👍

2023-10-17 05:16 UTC, inyeong-kang approved these changes

2023-10-17 06:43 UTC, merged