배너 공지사항 조회 / 공지사항 목록 조회 / 공지사항 상세 조회 / 공지사항 수정 / 공지사항 삭제 api 구현 및 query hook 구현
woowacourse-teams/2023-votogether pull request #739
Opened 2023-10-12 08:55 UTC by Gilpop8663

## 🔥 연관 이슈

close: #737 

## 📝 작업 요약

- 배너 공지사항 조회 / 공지사항 목록 조회 / 공지사항 상세 조회 / 공지사항 수정 / 공지사항 삭제 api 구현 및 query hook 구현

## ⏰ 소요 시간

2시간 45분 api가 많아서 단순 코드 작성만 하는데 생각보다 시간이 더 걸렸어요

## 🔎 작업 상세 설명

- 공지사항 목록 조회를 할 때 useInfinitedQuery를 사용하였는데요. 그 이유는 더보기를 눌렀을 때 useState로 데이터를 한곳에 모아서 관리해야하는데 useInfinifyQuery에 이미 편하게 구현이 되어있어서 사용했습니다. 그래서 더보기를 사용해도 되고, 무한 스크롤을 사용해도 되는 코드로 구현해놓았습니다

### 캐시타임, 스테일타임을 건드렸습니다

- 배너 공지 사항 : 30분 / 이유 :  배너 공지사항이 바뀌는 일이 적다고 생각하였지만 혹시 공지사항이 바뀌었을 때 캐싱되어 있어서 공지사항을 못보는 상황까지 고려해서 1시간은 길다고 생각했고, 30분으로 하였습니다. 기본값으로 하기엔 너무 안변하는 데이터라서요

- 공지 상세 정보 : 1시간 / 이유 : 공지사항 상세 정보는 더더욱 바뀔 일이 적다고 생각하여 1시간으로 설정했습니다

- 공지 목록 : 30분 / 이유 : 공지 사항 목록이 바뀌는 일이 적다고 생각했지만, 목록이다 보니 배너 공지사항이 바뀐다면 목록도 바뀌어야 하기에 배너 공지 사항 시간과 일치시켰습니다.

### 에러

현재 토스트 PR이 올라와있는 상태여서 우선 콘솔에러로 하였는데요. 추후 토스트 코드를 통해 에러나 성공을 보여주면 좋겠다고 생각했습니다

### api 감싸기

api가 변하진 않았지만 한번 감싸주었는데요. 이렇게 하는 편이 나중에 쉽게 코드를 고칠 수 있을거라고 생각해서 감싸줘보았습니다

2023-10-13 14:34 UTC, inyeong-kang requested changes
타입 관련 코멘트 남겼습니다!! 
공지사항 관련 API가 많은데 빠르고 꼼꼼한 구현 대단합니다👍👍

2023-10-13 19:25 UTC, Gilpop8663 reviewed
fe-리뷰요청

2023-10-13 19:25 UTC, Gilpop8663 commented on frontend/src/api/notice.ts
> +export type NoticeRequest = Omit<NoticeResponse, 'createdAt' | 'id'>;
공지사항 생성 시 id는 받지 않기 때문에 제외시켰습니당
```
{
	title: string, (100자)
	content: string, (3000자)
	deadline: datetime (DHM 형태이다, yyyy-mm-dd HH:MM) : string
	bannerTitle : string, (100자)
  bannerSubtitle: string (100자)
}
```

2023-10-13 19:25 UTC, Gilpop8663 commented on frontend/src/hooks/query/notice/useStackedNoticeList.tsx
> +          console.error('공지 사항을 리스트를 불러오는데 실패했습니다');
알려주셔서 감사합니다 👍👍👍

2023-10-13 19:25 UTC, Gilpop8663 commented on frontend/src/types/notice.ts
> +  noticeList: Notice[];
제로 타입의 마술사이신가요? 🌊

그렇지만 바꾸지 않는 것이 더 유지 보수에 좋다고 생각이 들었습니다  그 이유는 아래와 같습니당

totalPageNumber와 currentPageNumber와 같은 명세가 백엔드에서 고쳐도 프론트에서는 고정이라고 생각을 하는데요. 유틸리티 타입으로 했을 때 오히려 수정하는 코드가 더 많아진다고 생각이 드는데 어떻게 생각하세요?

아래와 같이 api의 NoticeListResponse만 변경되어도 되는 코드가 제안해주신 코드로 한다면 프론트 코드에게 영향을 준다고 생각이 들어요

currentPageNumber가 pageNumber로 바뀌었을 경우 예시

export type NoticeList  = Omit<Notice, 'notices' | 'pageNumber'> & { noticeList: Notice[] ; currentPageNumbre :   number; };

2023-10-13 19:27 UTC, Gilpop8663 commented
제로! 제안해주신 코드에 대해  코멘트 달았읍니당

fe-리뷰요청

2023-10-15 18:53 UTC, chsua approved these changes
우스! 정말 많은 테스트 코드를 작성하셨군요!
쿼리 훅이 많이 제작되었네요!

혹시 읽으면서 이미 머지된 imageZoomModal의 코드가 있는데,
이전 브랜치로 계속 작업하셔서 그런건가요..?

그 외에는 css 글로벌스타일에 대한 코멘트가 몇가지 있습니다만, approve 하겠습니다!

2023-10-15 18:53 UTC, chsua commented on frontend/src/components/comment/CommentList/CommentTextForm/index.tsx
> +    const isPressCtrlAndEnterKey = (event.metaKey || event.ctrlKey) && event.key === 'Enter';
😆😆😆

2023-10-15 18:53 UTC, chsua commented on frontend/src/components/comment/CommentList/CommentTextForm/style.ts
> +    font-size: 1.4rem;
저희 얼른 1.4rem 글로벌 스타일 만들어야겠어요

2023-10-15 18:53 UTC, chsua commented on frontend/src/components/comment/CommentList/CommentTextForm/style.ts
> +      font-size: 1.2rem;
요건 var(--text-small)있는데 따로 처리 안하신 이유가 있나요?

2023-10-15 18:53 UTC, chsua commented on frontend/src/components/common/ImageZoomModal/ImageZoomModal.stories.tsx
> +function ImageZoomModalStory() {
요거 이전에 머지된 기능아닌가요..? 데자뷰..?

2023-10-15 18:53 UTC, chsua commented on frontend/src/hooks/query/notice/usePagedNoticeList.tsx
> +  const { data, isError, isLoading, error } = useQuery<NoticeList>(
오 이전에 이야기하실때 useInfiniteQuery 사용한다고 하셨던 것 같은데 useQuery를 사용하신 이유가 있으신가요??

2023-10-15 18:53 UTC, chsua commented on frontend/src/hooks/query/notice/usePagedNoticeList.tsx
> +  const { data, isError, isLoading, error } = useQuery<NoticeList>(
아 이게 페이지네이션으로 보이는 공지사항이군요

2023-10-16 05:33 UTC, Gilpop8663 commented on frontend/src/components/comment/CommentList/CommentTextForm/style.ts
> +      font-size: 1.2rem;
알려주셔서 감사합니다 ~ 👍

2023-10-16 05:33 UTC, Gilpop8663 commented on frontend/src/hooks/query/notice/usePagedNoticeList.tsx
> +  const { data, isError, isLoading, error } = useQuery<NoticeList>(
네 맞습니당~!

2023-10-16 12:02 UTC, inyeong-kang commented on frontend/src/types/notice.ts
> +  noticeList: Notice[];
음 우스의 의견도 어느정도 공감이 되는군요!!

저는 Omit으로 제외하는 타입이 3개까지는 괜찮다고 스스로 합의하
고,, 현재 신고 목록 조회 API 관련 타입을 이미 선언한 상태인데요,
key이름이 바뀌는게 3개 이내라면 Omit으로 처리할거 같아요!

그렇지만 만약 백엔드 측에서 대규모 리팩터링을 해버려서 키값들이 다 바뀐다면..?? 우스의 방식대로 하는 것이 합리적이라고 생각합니다😀

이건 수아의 의견도 궁금하군요 @chsua

2023-10-16 12:06 UTC, inyeong-kang commented on frontend/src/api/notice.ts
> +export type NoticeRequest = Omit<NoticeResponse, 'createdAt' | 'id'>;
아하 공지사항 수정할 때는 noticeId 가 url의 params로 넣어서 보내야 하는군요.. 공지사항 수정할 때 noticeId 값을 쿼리에 따로 전달하는 이유가 궁금했는데 궁금증이 해소되었습니다😄👍

2023-10-17 05:21 UTC, inyeong-kang approved these changes
타입 관련 컨벤션을 페어프로그래밍을 통해 일치하였습니다!! 화이팅~~

2023-10-17 05:33 UTC, merged