[FEAT] 공지사항 관련 기능 구현
woowacourse-teams/2023-votogether pull request #748
Opened 2023-10-15 15:03 UTC by woo-chang

## 🔥 연관 이슈

* close: #747

## 📝 작업 요약

공지사항 관련 기능을 구현하였습니다.

## ⏰ 소요 시간

4시간. 추정 시간과 동일하게 소요되었던 것 같습니다 :)

## 🔎 작업 상세 설명

- 공지사항 생성
- 배너 공지사항 조회
- 공지사항 목록 조회
- 공지사항 상세 조회
- 공지사항 수정
- 공지사항 삭제

간단한 기능 구현인만큼 꼼꼼한 테스트 코드를 작성하기 위해 노력하였습니다.
기존에 `380`여 개의 테스트 코드가 존재하였는데, 기능 구현 완료 후 `416`개의 테스트 코드가 작성되어 있습니다.

## 🌟 논의 사항

마감기한이 지나지 않은 공지사항이 존재하지 않을 때 모든 필드가 `NULL`인 응답을 반환하고 있는데, 어떻게 처리하면 좋을지 같이 얘기해보면 좋을 것 같아요 🤓

2023-10-16 16:22 UTC, aiaiaiai1 requested changes
안녕하세요 오랜만에 프로젝트 코드 리뷰를 하네요
몇가지 코멘트 남겼는데 한번 확인해주시면 될거같아요
테스트코드가 엄청 꼼꼼하시던데 고생하셨습니다!!

2023-10-16 16:22 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/notice/service/NoticeService.java
> +        );
p2
update도 create와 일관성있게 파라미터로 string을 받아서 update에서 Detail객체가 만들어지게 하는건 어떤가요?

2023-10-16 16:22 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/notice/service/NoticeServiceTest.java
> +
테스트코드 엄청나군요 👍

2023-10-16 16:30 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/service/NoticeService.java
> +        return new NoticeResponse(null, null, null, null, null, null, null, null);
빈 객체는 미리 만들어 두는게 좋을 것 같네요 감사합니다 👍

2023-10-16 16:33 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/service/NoticeService.java
> +    }
`Pageable`을 통해 `10`개씩 보내주도록 구현되어 있습니다 !

2023-10-16 16:34 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/controller/NoticeController.java
> +            @RequestParam @PositiveOrZero(message = "페이지는 0이상 정수만 가능합니다.") final int page
사용자에게 보여질 때는 `1`부터 보여지지만 인덱스가 `0`부터 시작하듯 `Pageable`을 사용하면 첫 번째 페이지가 `0`을 의미합니다!

따라서 첫번째 페이지 요청은 `0`을 보내도록 해야하는데, 혹시 제가 이해한 것이 맞을까요?! 😃

2023-10-16 16:35 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
> +        LocalDateTime updatedAt
`API` 명세에는 수정시각이 없었네요 🥲 내일 우스와 같이 얘기해보도록 하겠습니다 :)

2023-10-16 16:36 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/service/NoticeService.java
> +        );
해당 방법에 대한 고민도 했었습니다! 해당 방법을 사용하면 `update` 메서드에 파라미터가 너무 많이 전달될 것 같아 이를 줄이기 위해 외부에서 만들어서 전달하는 방법을 사용했습니다.

혹시 이 부분에 대해서는 어떻게 생각하시나요 ㅎㅎ

2023-10-16 16:36 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/notice/service/NoticeServiceTest.java
> +
미션을 통해 학습한 내용 프로젝트에 적용 🎉

2023-10-17 06:25 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/notice/controller/NoticeController.java
> +            @RequestParam @PositiveOrZero(message = "페이지는 0이상 정수만 가능합니다.") final int page
아하 그렇군요 프론트랑 맞추어져만 있다면 상관없을것 같네요~

2023-10-17 06:26 UTC, jeomxon requested changes
깔끔하게 잘 구현해주셔서 남길 코멘트가 거의 없네요!
작성하시느라 고생하셨습니다 :)

+ 이거 코드 보다가 제가 잘못 짠 로직 발견했네요..ㅎㅎ

2023-10-17 06:26 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/notice/entity/vo/BannerTitle.java
> +            return;
`P1`
예외 발생을 의도하고 로직을 만드신게 아닐까요?

2023-10-17 06:26 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
> +    public static final NoticeResponse empty = new NoticeResponse(null, null, null, null, null, null, null, null);
`Q`
메서드가 아닌 필드로 만들어주신 이유가 있나요?

2023-10-17 06:33 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/notice/service/NoticeService.java
> +        );
이건 사람마다 취향차이로 갈릴것 같네요
저는 어차피 notice가 생성될때 이미 여러개 파라미터를 빌더를 통해 전달 받고 있고 
update에서 파라미터가 많아져도 큰 문제는 없을거같아서 일관성을 유지하는 방향으로 할것같습니다!
근데 이건 개인성향차라서 다즐이 편하신대로 하시면 될거같네요~

++ update 메서드의 파라미터에서 개행이 빠져있어요

2023-10-17 06:37 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
> +        LocalDateTime updatedAt
어떻게 되었나요??!

2023-10-17 06:38 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/controller/NoticeController.java
> +            @RequestParam @PositiveOrZero(message = "페이지는 0이상 정수만 가능합니다.") final int page
응답도 요청과 마찬가지로 `0`으로 보내면 프론트에서 `1`로 보여지게 처리한다고 얘기했습니다 ㅎㅎ

2023-10-17 06:38 UTC, aiaiaiai1 approved these changes
다즐 고생하셨습니다~
api명세 관련부분만 결정된대로 적용하시면 될거같아요!

2023-10-17 06:43 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
> +        LocalDateTime updatedAt
우스와 얘기한 결과 사용하지 않는 필드라 삭제하도록 하겠습니다 !

2023-10-17 06:49 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/entity/vo/BannerTitle.java
> +            return;
배너 제목에는 `null`이 허용가능하기에 `null`일 때 검증 과정을 거치지 않고 바로 저장되도록 하였습니다 !

지금 코드를 다시 확인하니 공백일 때는 예외를 발생시켜주는게 좋을 것 같아요 👍

2023-10-17 06:56 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
> +    public static final NoticeResponse empty = new NoticeResponse(null, null, null, null, null, null, null, null);
계속해서 사용될 값이라 필드로 두고 재사용하려고 했습니다 !

생성하는데 큰 비용이 들지 않고, 계속 메모리에 두는 것보다는 필요할 때 만들어서 사용하는게 더 좋아보이네요 👍

2023-10-17 07:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/dto/response/NoticeResponse.java
> +    public static final NoticeResponse empty = new NoticeResponse(null, null, null, null, null, null, null, null);
말씀해주신 것처럼 필드로 사용하게 되면 `NoticeResponse`의 필드가 사용된다는 느낌도 강한 것 같아요.

확실히 새로운 객체를 생성한다는 의미로 메소드가 훨씬 직관적이네요 ㅎㅎ

2023-10-17 07:20 UTC, jeomxon approved these changes
빠르게 반영해주셨네요 ㅎㅎ
approve하겠습니다!

2023-10-17 08:07 UTC, tjdtls690 requested changes
고생하셨습니다 다즐

몇 가지 리뷰 남겼습니다 :)

2023-10-17 08:40 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/notice/service/NoticeService.java
> +    }
좋은데요 ㅎㅎ 감사합니다 :)

2023-10-17 08:50 UTC, tjdtls690 approved these changes
수고하셨습니다 다즐~!
역시 ㅡ 즐 ㅡ

2023-10-17 09:07 UTC, merged