신고 조치 예정 목록 조회 기능 구현
woowacourse-teams/2023-votogether pull request #750
Opened 2023-10-15 16:55 UTC by tjdtls690

## 🔥 연관 이슈

close: #746 

## 📝 작업 요약

신고 조치 예정 목록 조회 기능 구현

## ⏰ 소요 시간

6시간

## 🔎 작업 상세 설명

신고가 하나라도 존재하는 요소를 관리자 페이지의 신고 조치 예정 목록에서 조회한다.

## 🌟 논의 사항

얘기할 부분이 좀 많아서 논의 사항은 캠퍼스에서 직접 같이 얘기해봐야 할 듯 합니다.

2023-10-16 05:07 UTC, woo-chang requested changes
안녕하세요 아벨 :) 다즐입니다 ㅎㅎ

전체적인 로직을 깔끔하게 작성해주셔서 읽기 쉬웠던 것 같아요
몇 가지 소소한 커멘트와 질문 남겨두었는데 확인해주시면 감사합니다 🙇🏻‍♂️

2023-10-16 06:30 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/controller/ReportQueryController.java
> +    @GetMapping("/reports/admin")
다른 컨트롤러 보니까 메서드가 하나만 있는 경우엔 그냥 메서드에 붙여져 있더라구요. 그래서 가독성을 더 챙기기 위해 그렇게 했다고 생각했어서 똑같이 이렇게 하긴 했는데, 다즐의 의견이 궁금합니다 :)

2023-10-16 06:30 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/dto/response/ReportsResponse.java
> +        long totalPageCount,
API 명세에서 totalPageCount라고 되어있길래 변수명을 이렇게 했었는데, 방금 제로랑 얘기해서 totalPageNumber로 하기로 결정 되었습니다. 수정할게요!

2023-10-16 06:31 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/common/BaseEntity.java
> +    }
현재 ReportCustomRepositoryImpl의 findReportsGroupedByMemberAndReportTypeAndTargetId 메서드에서 Projections.constructor를 통해 Report를 초기화 하는 중인데, 이게 생성자를 직접 사용해서 초기화하는 형식이더라구요. 그리고 여기서 전달한 createdAt을 초기화 하려면 super() 생성자를 사용해서 초기화 해야만 createdAt이 null이 안되더라구요.

2023-10-16 06:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/entity/Report.java
> +        super(createdAt);
위 답변과 동일합니다 :)

2023-10-16 06:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        final int totalPages = reportRepository.findAll(pageable).getTotalPages();
개선해보겠습니다 :)

2023-10-16 06:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        return ReportsResponse.of(totalPages, page + 1, reports, targets);
그게 더 좋을 것 같네요. 개선해보겠습니다.

2023-10-16 11:36 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/report/controller/ReportQueryController.java
> +    @GetMapping("/reports/admin")
현재는 메서드가 1개밖에 없기에 지금으로도 괜찮다고 생각해요 ㅎㅎ

메서드가 추가된다면 분리하는 것으로 개선해봐도 좋을 것 같아요 👍

2023-10-16 11:40 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/common/BaseEntity.java
> +    }
`Report` 자체는 엔티티이기 때문에 `DB`에 저장되어 있는 데이터를 그대로 가져와야한다고 생각해요. `findReportsGroupedByMemberAndReportTypeAndTargetId` 메서드는 DB 데이터를 조작해서 필요한 데이터를 만들어내는 메서드이기 때문에 `Entity`를 직접적으로 매핑시키기 보다는 `DTO`를 통해 필요한 데이터를 만들어내는 방법으로 위의 문제를 해결할 수 있을 것 같은데 이 부분은 어떻게 생각하시나요? 🤓

2023-10-16 11:46 UTC, woo-chang reviewed
변경 사항 확인했습니다 ㅎㅎ

같이 얘기하고 싶은 부분 몇 가지가 더 있어 커멘트 남겨두었습니다 :)

2023-10-16 11:46 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        long totalCount = reportRepository.count();
`final` 키워드가 빠져있어요 :)

2023-10-16 11:46 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +    }
```java
private List<ReportResponse> convertToReportResponses(final List<Report> reports) {
    return reports.stream()
            .map(report -> {
                final var strategy = reportActionProvider.getStrategy(report.getReportType());
                return ReportResponse.of(report, strategy.parseType(report.getTargetId());
            })
            .toList();
}
```
수도 코드라 동작할지 모르겠는데 요렇게도 가능하지 않나요?!

2023-10-17 05:41 UTC, aiaiaiai1 requested changes
아벨 깔끔하게 잘 구현해주셨네요!
사소한 커멘트 남겨드려보았습니다!
고생하셨어요~

2023-10-17 05:41 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/report/service/ReportCommandService.java
> +    private final ReportActionProvider reportActionProvider;
provider로 묶으니까 훨씬 깔끔해지군요!

2023-10-17 05:41 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/report/service/strategy/ReportPostStrategyTest.java
> +
p1
DisplayName이 잘못된거 같아요

2023-10-17 05:44 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/common/BaseEntity.java
> +    }
괜찮은 것 같아요! 개선해보겠습니다 :)

2023-10-17 06:16 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +    }
사실 람다 안에서 뎁스가 더 들어가는 형식을 별로 좋아하지 않아서 메서드 분리를 한 번 더 했었는데, 이것도 나쁘지 않는 것 같네요 :)

다즐이 보기엔 그냥 하나로 합치는 것이 더 가독성이 좋게 느껴지는 지 궁금합니다.

2023-10-17 06:22 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +    }
사실 람다 안에서 뎁스가 더 들어가는 형식이 가독성이 별로 안좋은 것 같아서 메서드 분리를 한 번 더 했었는데, 이것도 나쁘지는 않은 것 같네요 :)

다즐이 보기엔 그냥 하나로 합치는 것이 더 가독성이 좋게 느껴지는 지 궁금합니다.

2023-10-17 06:44 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +    }
굿굿

2023-10-17 06:47 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +    }
parseReportResponse 메서드에서 reportActionProvider를 사용하고 있어서 서비스에다 두었습니다. 지금 다즐 피드백 보고 메서드를 2개로 줄였는데, 개인적으로 이 정도면 서비스에 두어도 괜찮을 것 같다는 생각이 들었어요.

만약 public 메서드가 6~7개를 넘어가면 reportActionProvider를 response에 같이 주어서라도 private 로직을 response에 전부 넘겨주는 것이 더 좋을 것 같다는 생각도 드는데, 현재 상황에선 괜찮을 것 같아서요.

루쿠는 어떻게 생각하시나요??

2023-10-17 07:02 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +    }
이정도의 메서드 개수이면 괜찮을것같습니다!

2023-10-17 07:02 UTC, aiaiaiai1 approved these changes
아벨 확인했습니다~
빠르게 approve 할께요!
고생하셨습니다!

2023-10-17 07:07 UTC, woo-chang approved these changes
확인했습니다 ㅎㅎ 수고하셨어요 🤓👍

2023-10-17 07:11 UTC, merged

2023-10-17 07:15 UTC, jeomxon requested changes
역시나 멋지게 잘 만들어주셨군요!
사소한 의문증들 남겨 두었으니 확인 부탁드릴게요 :)

2023-10-17 07:21 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/repository/ReportCustomRepositoryImpl.java
> +                                Expressions.stringTemplate("group_concat({0})", report.reason),
reportType, targetId는 group by로 묶였기 때문에 1개씩 잘 나오게 되는데, group by로 묶었을 때 report의 id, reason, createdAt은 여러 행이 나올 수 있는 컬럼들입니다. 그래서 max()는 여러개 묶인 것 중 가장 최신 것을 가져오기 위해 max()를 사용하였습니다.

```java
.orderBy(report.id.max().desc())
```

위처럼 정렬할 때 최신순으로 가져오고 있습니다.

2023-10-17 07:28 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/dto/ReportAggregateDto.java
> +        String reasons,
ReportAggregateDto는 api에 관련된 것이라기 보단, ReportCustomRepositoryImpl 클래스의 findReportsGroupedByReportTypeAndTargetId에서 데이터를 조회할 때 매핑할 용도로 만들었습니다.

Service 계층에서 ReportAggregateDto를 ReportPageResponse로 매핑하는 과정이 있어서 괜찮을 것 같다고 생각하는데 어떻게 생각하시나요

2023-10-17 07:32 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        return ReportResponse.of(reportAggregateDto, strategy.parseTarget(reportAggregateDto.targetId()));
뭔가 target으로 파싱한다는 의미로 했었었는데, 이게 Post의 id로 변할수도, 댓글 내용이나 멤버의 닉네임으로 변할 수도 있어서 어떤 이름이 좋을지 잘 생각이 안나네요.

targetId를 파싱한다는 의미에서 parseTargetId가 나을까요?

2023-10-17 07:39 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/strategy/ReportActionProvider.java
> +public class ReportActionProvider {
1. 클래스 명은 신고 관련 동작을 제공해준다는 의미에서 이렇게 붙였습니다.
2. 먼저 이걸 분리한 이유는 여러 서비스에서 공통으로 사용하게 되어서 중복 로직 제거, 서비스 크기 단축을 위해서였습니다. 처음 생각은 ReportType과 나머지 파라미터 하나를 전부 전달해서, 이 클래스 안에서 전략 메서드의 실행까지 역할을 맡도록 구현할까도 생각했었는데, 그렇게 되면 이 안에서 분기점이 많이 나올 수밖에 없다고 생각했습니다. 또한 파라미터에 따라 어떤 메서드를 실행시켜줄 지 판단하는 것도 굉장히 애매하다고 느껴져서 그냥 전략을 매핑해주는 용도로 사용하게 되었습니다.
이것 외엔 서비스의 Map 공통 로직을 처리할 방법을 생각해보진 못했습니다.

2023-10-17 07:45 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        return ReportResponse.of(reportAggregateDto, strategy.parseTarget(reportAggregateDto.targetId()));
GPT한테 추천 메서드명을 물어보니,

1. retrieveTargetInfo(): "검색"이라는 뜻을 갖는 retrieve와 "정보"라는 뜻을 갖는 info를 합쳐서 대상의 정보를 검색한다는 의미를 잘 전달하는 이름입니다.
2. getTargetDescription(): 대상의 설명이나 정보를 얻어오는 것에 중점을 둔 이름입니다.
3. identifyTarget(): 대상을 식별한다는 의미로, 어떠한 식별자를 사용하여 특정 대상을 구분하거나 식별하는 작업에 적합한 이름입니다.
4. lookupTargetDetails(): "조회"라는 뜻의 lookup와 "세부 사항"이라는 뜻의 details를 합친 이름으로, 대상의 세부 사항을 조회한다는 의미를 가집니다.

이렇게 나오네요...ㅋㅋ

2023-10-17 08:48 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/report/repository/ReportCustomRepositoryImpl.java
> +                                Expressions.stringTemplate("group_concat({0})", report.reason),
레전드 설명 잘 들었습니다.
이해 되었습니다!

2023-10-18 02:47 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        return ReportResponse.of(reportAggregateDto, strategy.parseTarget(reportAggregateDto.targetId()));
뭔가 `parse`라는 단어의 의미랑 맞지 않아서 한번에 이해가 잘 되지 않았어요.
제가 아는 `parse`의 의미는 "분해하다"라서요!

2023-10-18 02:51 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/report/dto/ReportAggregateDto.java
> +        String reasons,
String인데 reasons인 이유가 궁금했습니다!

2023-10-18 03:08 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/dto/ReportAggregateDto.java
> +        String reasons,
String이긴 한데 일단 쉼표로 이어져 있는 방식의 String이기 때문에 reasons로 했는데, 좀 더 가독성 좋은 변수명이 있을까요.
제 머리의 한계가...ㅋㅋ

2023-10-18 03:17 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/report/service/ReportQueryService.java
> +        return ReportResponse.of(reportAggregateDto, strategy.parseTarget(reportAggregateDto.targetId()));
개인적으로 parse 라는 이름을 많이 쓰는 이유가, 자바에서 제공하는 라이브러리에서도 Integer의 parseInt를 참고했었는데요. parse가 분석하다라는 뜻을 가지고 있어서, 분석해서 변환한다 라는 의미로 받아들였습니다.