알림 ui 구현 및 api 연동
woowacourse-teams/2023-votogether pull request #751
Opened 2023-10-15 17:29 UTC by chsua

## 🔥 연관 이슈

close: #740 

## 📝 작업 요약
알림 ui 구현 및 api 연동.

## ⏰ 소요 시간
3일
생각보다 할일이 많았습니다..

## 🔎 작업 상세 설명
### 디자인 추가 / 변경
1. 마이페이지 이동 트리거 변경
    - 기존 헤더에서 사이드바 닉네임 클릭으로 변경
    - 페이지 이동이란 것을 보여주기 위해 화살표 표시
    - 마이페이지 진입 시 화살표 사라짐 + 이벤트 사라짐
2. 기존 마이페이지 이동 버튼 위치에 알림 아이콘 생성
    - 사용자 정보를 받아 활성화 표시 (프라이머리 색상으로)
3. 알림 리스트 
    - 툴팁을 만들어 데스크탑에서는 툴팁으로 표시
    - 모바일에서는 기존 drawer을 이용해 오른쪽에서 나오도록 표시
    - 기본적으로 토글로 컨텐츠와 신고를 오갈 수 있음
4. 신고된 내역 알림을 클릭
    - 신고 상세 안내 페이지로 이동
    - 신고 관련 사유 및 정보를 가지고 있음
    - **기존 논의와 달리 게시물 페이지 전환이 아닌 게시물 포함으로 변경**

### 기능 안내
1. 알림 리스트 관련
```
// 데스크탑에서는 ToolTip 안에 AlarmContainer 가 children으로 들어감
// 모바일에서는 drawer 안에 AlarmContainer 가 children으로 들어감

AlarmContainer // 토글을 포함한 컴포넌트
 ┣ ContentAlarmList
 ┃ ┗ index.tsx
 ┣ ReportAlarmList
 ┃ ┗ index.tsx
 ┣ AlarmContainer.stories.tsx
 ┣ ListStyle.ts 
 ┣ index.tsx
 ┗ style.ts
```

2. 포함되는 폴더
    - url에 따라 처리
        - alarm : 알림 리스트(컨텐츠/신고), 신고 알림 단건 조회, 알림읽기
        - user: 최신 알림 읽기

## 🌟 논의 사항
1. preview 영상의 용량이 커서 동영상은 슬랙에 달아놓겠습니다
2. 어디까지 범용성있게 가지고 가야 할 지 잘 모르겠습니다. 그래서 컴포넌트도 조금 혼란스러운 것 같아요. 예로, 리스트는 동일한 UI를 가지고 있지만 둘로 분리되어 있습니다. 서스펜스를 사용하기 위해 컴포넌트를 분리해 api를 넣기 위함입니다만 리스트는 따로 또 분리했어야 했나 하는 생각도 드네요.
3. 왜인지 알림 리스트가 더보기를 누르지 않았는데도 자동으로 fetch를 해오는 경우가 있습니다. 왜인지 모르겠습니다. 더불어 페이지를 이동하고 돌아오면 fetch되어있던 이전 자료들이 눈에 보입니다. 이는 그 cashe time 때문인것같은데 그냥 0으로 설정할까요?? 
4. 에러 처리는 아직 dev에 토스트 pr이 머지되지 않아서 하지 않았습니다. 404인 경우도 postDetail 404와 동일하게 처리할 예정입니다.
5. 신고 처리 결과를 보는 트리거는 알림입니다만, 신고 처리 결과 자체가 알림과 관련이 없는데 api나 컴포넌트 이름에 alarm을 넣어야 하는지 의문이 듭니다. 고민하다가 사용자가 보는 라우터 url은 알림을 넣고 그 외에는 ```reportConfirmResult```을 사용했습니다. 오히려 이게 더 헷갈린다고 하면 변경하겠습니다. 변수명 추천 받습니다.

2023-10-15 18:03 UTC, chsua commented
fe-리뷰요청

2023-10-15 20:28 UTC, Gilpop8663 requested changes
1.
> 어디까지 범용성있게 가지고 가야 할 지 잘 모르겠습니다. 그래서 컴포넌트도 조금 혼란스러운 것 같아요. 예로, 리스트는 동일한 UI를 가지고 있지만 둘로 분리되어 있습니다. 서스펜스를 사용하기 위해 컴포넌트를 분리해 api를 넣기 위함입니다만 리스트는 따로 또 분리했어야 했나 하는 생각도 드네요.

리스트가 분리된다면 좋겠지만 분리되어도 알림, 신고를 패치해오는 컴포넌트가 또 생겨야하고, 내부에서 slice하는 로직도 따로 사용되는 UI 밖에서 처리를 해야하기에 현재에 비해 시간이 좀 더 들 것 같아요.  저는 리스트가 알림, 신고에서만 사용되기 때문에 나중에 리스트 디자인이 변해도 복붙 1번이면 되서 지금이 더 좋은 것 같아요.


2.
> 왜인지 알림 리스트가 더보기를 누르지 않았는데도 자동으로 fetch를 해오는 경우가 있습니다. 왜인지 모르겠습니다. 더불어 페이지를 이동하고 돌아오면 fetch되어있던 이전 자료들이 눈에 보입니다. 이는 그 cashe time 때문인것같은데 그냥 0으로 설정할까요??

모킹 데이터를 코멘트에 달았던 것처럼 함수로 실행하게 된다면 해당 동작은 일어나지 않네요. 알림 아이디를 통해서 준 리스트 키  값이 에러가 나서 기존에 있던 값과 새로 패치해온 것이 중복되어서 보여진 것 같아요

https://github.com/woowacourse-teams/2023-votogether/assets/80146176/e05808f4-51a3-4bc9-8ec0-1d6a37b11c67

3.
> 신고 처리 결과를 보는 트리거는 알림입니다만, 신고 처리 결과 자체가 알림과 관련이 없는데 api나 컴포넌트 이름에 alarm을 넣어야 하는지 의문이 듭니다. 고민하다가 사용자가 보는 라우터 url은 알림을 넣고 그 외에는 reportConfirmResult을 사용했습니다. 오히려 이게 더 헷갈린다고 하면 변경하겠습니다. 변수명 추천 받습니다.

신고 처리 결과에 alarm을 넣기엔 아무 관계가 없어보여서요 저는 현재 수아가 사용하신 변수명이 적절해보입니다 


-----------

### 제안사항


1. 현재 content, report로 되어있는데 한글로 보여주는 것은 어떠세요?

![image](https://github.com/woowacourse-teams/2023-votogether/assets/80146176/daf3422c-9389-4745-81cd-57ce934c5355)

![image](https://github.com/woowacourse-teams/2023-votogether/assets/80146176/6c95734f-630d-417b-a2ac-69cc6a5df352)

2. AlarmContainer 폴더를 components/alram 으로 옮기는 것은 어떠세요?

현재는 common에 있는데 알림에만 사용될 것 같아서요


------------------

정말 많은 것이 추가되고 바뀌었군요 !

알림 기능이 신경 쓸 것이 많아보였는데 꼼꼼히 구현하신 것 대단하다고 생각이 듭니다 🌊🌊🌊

최고! 🔥

2023-10-15 20:28 UTC, Gilpop8663 commented on frontend/src/styles/reset.ts
> +}
모든 페이지에서 스크롤바가 없을 때 예상치 못한 부작용은 없을지 고민이 되네요  당장은 생각나는 것이 별로 없는 것 같아요

알림에서만 세부적으로 스크롤을 없애는 것과 모든 페이지에서 스크롤을 없애는 것 중 모든 페이지에 적용하게 된 이유가 궁금합니다

2023-10-15 20:28 UTC, Gilpop8663 commented on frontend/src/hooks/query/useReportConfirmResult.tsx
> +  );
데이터가 없다면 수아의 방식처럼 바로 실패시키는 것이 사용자에게 답답함을 줄여주는 것 같아요 💯💯💯

2023-10-15 20:30 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-16 13:28 UTC, chsua commented on frontend/src/components/common/AlarmContainer/ContentAlarmList/index.tsx
> +    return <p>현재 도착한 알림이 없습니다!</p>;
수정했습니다!!

2023-10-16 18:23 UTC, inyeong-kang requested changes
Files changed 63..?
역대 프론트 Top3 안에 들거 같은데요..👍🎉

fe-리뷰완

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/__test__/api/user.test.ts
> +  test('클라이언트에서 사용하는 유저 정보 API 명세가 [nickname, gender, birthYear, postCount, voteCount, hasLatestAlarm]으로 존재해야한다', async () => {
conflict 사전 방지를 위해 hasLatestAlarm 뒤에 role도 추가해주실 수 있나요...ㅎㅎㅎ

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/styles/globalStyle.ts
> +    --bright-gray: #F4F4F4;
👍👍

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/pages/ReportAlarmPage/ReportConfirmResult/style.ts
> +  pointer-events: none;
혹시 이 속성이 어떤 의도로 필요한 건지 궁금해요!!
이벤트 발생을 막지 않는다는 건가용..??

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/pages/ReportAlarmPage/ReportConfirmResult/index.tsx
> +            })}
오 Set~~~~ 프로젝트에서 최초로 쓰였군요! 중복 제거 좋습니다👍

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/pages/ReportAlarmPage/ReportConfirmResult/ReportTargetPost/index.tsx
> +  return data && <Post postInfo={data} isPreview={false} />;
기존 Post 컴포넌트 재사용 너무 좋아요!

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/constants/path.ts
> +  ALARM: '/alarm',
alarms 로 복수형 형식으로 통일 어떠신가용

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/components/common/IconButton/IconButton.stories.tsx
>  export const UserInfo: Story = {
오 유저정보 스토리인데 category가 'alarm'인가용??

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/components/common/Drawer/Drawer.stories.tsx
> +      <NarrowMainHeader handleCategoryOpenClick={openDrawer} handleAlarmOpenClick={() => {}} />
handleDrawerOpenClick 어떠신가요? (Drawer에 카테고리 외에 유저 프로필도 있어서...)

2023-10-16 18:23 UTC, inyeong-kang commented on frontend/src/components/common/AlarmContainer/ReportAlarmList/index.tsx
> +export default function ReportAlarmList({ closeToolTip }: { closeToolTip: () => void }) {
common 에 위치하기에는 도메인적 요소가 많아보이는데 common 외에 다른 곳에 위치시키는 것 어떠신가요?
수아가 생각하시는 common 폴더에 위치할 수 있는 기준이 궁금해요!

2023-10-17 01:06 UTC, chsua commented on frontend/src/styles/reset.ts
> +}
스크롤 기능을 없애는 것이 아닌 스크롤 UI만 없애는 거라 상관 없을 것이라고 생각했습니다.

없애도 상관없고, 있으면 UI가 맞지 않는다면 없애는 것이 좋을 것이라고 생각했고,
그렇다면 일률적으로 모든 곳에 적용하는 것이 통일성 있지 않을까 생각했습니다!

2023-10-17 01:06 UTC, inyeong-kang commented
🌟 논의 사항
> preview 영상의 용량이 커서 동영상은 슬랙에 달아놓겠습니다

💯💯

> 어디까지 범용성있게 가지고 가야 할 지 잘 모르겠습니다. 그래서 컴포넌트도 조금 혼란스러운 것 같아요. 예로, 리스트는 동일한 UI를 가지고 있지만 둘로 분리되어 있습니다. 서스펜스를 사용하기 위해 컴포넌트를 분리해 api를 넣기 위함입니다만 리스트는 따로 또 분리했어야 했나 하는 생각도 드네요.
> 개인적인 의견으로 common 에는 NarrowHeader 처럼 여러번 범용적으로 재사용되는 것만 있어야 된다고 생각해요!

> 왜인지 알림 리스트가 더보기를 누르지 않았는데도 자동으로 fetch를 해오는 경우가 있습니다. 왜인지 모르겠습니다. 더불어 페이지를 이동하고 돌아오면 fetch되어있던 이전 자료들이 눈에 보입니다. 이는 그 cashe time 때문인것같은데 그냥 0으로 설정할까요??
🤔


> 에러 처리는 아직 dev에 토스트 pr이 머지되지 않아서 하지 않았습니다. 404인 경우도 postDetail 404와 동일하게 처리할 예정입니다.
👍


> 신고 처리 결과를 보는 트리거는 알림입니다만, 신고 처리 결과 자체가 알림과 관련이 없는데 api나 컴포넌트 이름에 alarm을 넣어야 하는지 의문이 듭니다. 고민하다가 사용자가 보는 라우터 url은 알림을 넣고 그 외에는 reportConfirmResult을 사용했습니다. 오히려 이게 더 헷갈린다고 하면 변경하겠습니다. 변수명 추천 받습니다.

github 처럼 approve 어떠신가요? reportApproveResult 추천합니다 (저도 신고 조치 fetch 함수명 reportApprove 로 바꿀까 고민 중..)

2023-10-17 01:54 UTC, chsua commented on frontend/src/pages/ReportAlarmPage/ReportConfirmResult/style.ts
> +  pointer-events: none;
네네 그 포스트 컴포넌트를 넣는다면 onClick event를 막아도 방지가 되지 않고 투표가 됩니다😂
그래서 아예 css 속성으로 못하게 설정했습니다.

2023-10-17 01:56 UTC, chsua commented on frontend/src/hooks/query/useReportConfirmResult.tsx
> +        // const fetchError = error as Error;
네네 맞습니다! 각주 위에 작성한다는 것을 잊었네요! 
toast 도입하면서 해제할 예정입니다!

2023-10-17 02:11 UTC, chsua commented on frontend/src/components/common/Drawer/Drawer.stories.tsx
> +      <NarrowMainHeader handleCategoryOpenClick={openDrawer} handleAlarmOpenClick={() => {}} />
근데 저 알림도 drawer라서 헷갈릴 것 같아요..

2023-10-17 02:47 UTC, chsua commented on frontend/src/components/common/AlarmContainer/ReportAlarmList/index.tsx
> +export default function ReportAlarmList({ closeToolTip }: { closeToolTip: () => void }) {
헤더 두 개에 사용될 예정이라 common에 넣었는데 만들고 보니 도메인이 강하네요! 
수정하겠습니다!

2023-10-17 05:52 UTC, chsua commented
fe-리뷰요청

2023-10-17 06:12 UTC, Gilpop8663 approved these changes
코드 변경된 부분 확인 후 어프로브 했습니다 🔥🔥🔥

2023-10-18 02:18 UTC, inyeong-kang approved these changes
충돌이 꽤 있는데 잘 해결되길...
코드 수정하신거 확인했습니다~

fe-리뷰완

2023-10-18 03:00 UTC, merged