마이페이지 비회원 이용가능하도록 하기 / 마이페이지에 공지사항, 관리자 페이지 추가
woowacourse-teams/2023-votogether pull request #754
Opened 2023-10-16 07:40 UTC by Gilpop8663

## 🔥 연관 이슈

close: #753 

## 📝 작업 요약

- 마이페이지 비회원 이용가능하도록 하기 / 마이페이지에 공지사항, 관리자 페이지 추가
- userInfo에 role 추가
- 마이페이지에서 유저 권한에 따라 다르게 렌더링 되도록 하기
- 관리자 페이지에서 관리자가 아니면 접근이 불가능하도록 설정
- 카카오 버튼 이미지 고화질로 변경

## ⏰ 소요 시간

1시간

## 🔎 작업 상세 설명

### path url

관리자 신고내역 페이지 : admin/reports
관리자 공지사항 페이지 : admin/categories

-------------

### 사진

### 비회원

<img width="1440" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/c809a4d6-38ad-43aa-816d-5f93fb508150">

<img width="402" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/2b47deab-dc9d-4619-8899-be9b2913bf8a">

------------

### 회원

<img width="405" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/dcb4165f-d610-4fa5-86a1-258c4ff148e7">

<img width="1195" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/9b48d47b-a359-4b5b-af6b-476711b9753e">

-----------

### 관리자

<img width="394" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/00b516ef-c1df-4957-880e-ae2cee8c258f">

<img width="1187" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/8aea56d6-ac0e-4753-aca3-6a662a70957a">

--------

### 로그인 페이지 카카오 버튼 이미지 수정 

약간 흐려서 완성도가 낮아보인다는 피드백을 들었어서 뚜렷하게 변경

### 변경 전

<img width="382" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/3ed3bde4-efc7-4296-8284-272383c0f270">

### 변경 후

<img width="417" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/90fbd3f5-868b-4ed4-8c72-dbaa096e1c17">

--------

## 🌟 논의 사항

관리자 페이지로 url을 직접 입력했을 때 관리자 계정임에도 접근이 불가능하다고 나오는데요. 이러한 것은 useEffect에서 토큰을 통해 자동 로그인이 진행된 후 유저 정보를 가져오는데, 이러한 과정을 거치려면 렌더링이 끝나야 되기 때문에 PrivateRoute에서는 관리자가 url로 직접 들어오는 것을 허용할 수 없었습니다

그렇지만 관리지이기 때문에 마이페이지에서 직접 들어오는 것은 가능하므로 괜찮은 수준의 문제라고 생각하여 PR 올리게 되었어요

2023-10-16 12:26 UTC, inyeong-kang requested changes
우스~ 오늘 오전에 회의한 내용을 굉장히 빠르게 반영해주셨군요? (그저 ✨..)
제가 작업한 내용과 살짝 다른 부분이 있어 코멘트 남겼어요! 
내일 이야기해보아요~~~

2023-10-16 12:26 UTC, inyeong-kang commented on frontend/__test__/api/user.test.ts
> +  test('클라이언트에서 사용하는 유저 정보 API 명세가 [nickname, gender, birthYear, postCount, voteCount, role]으로 존재해야한다', async () => {
혹시 hasLatestAlarm 도 추가해주실 수 있나요? (test fail 이 두려워져서..😅)

2023-10-16 12:26 UTC, inyeong-kang commented on frontend/src/components/common/Dashboard/GuestProfile/index.tsx
> +  isLargeKaKao?: boolean;
👍

2023-10-16 12:26 UTC, inyeong-kang commented on frontend/src/constants/path.ts
> +  ADMIN_CATEGORY_LIST: `${BASE_PATH.ADMIN}/categories`,
오 path 명을 이렇게 지으셨군요..🤔 
혹시 카테고리 목록 관련된 라우터는 미리 만들어놓으신건가요??

2023-10-16 12:26 UTC, inyeong-kang commented on frontend/src/mocks/mockData/user.ts
> +  role: 'ADMIN',
hasLatestAlarm 값도 미리 추가해주시면 감사하겠습니다..!!!!

2023-10-16 12:26 UTC, inyeong-kang commented on frontend/src/constants/path.ts
> +  ADMIN_CATEGORY_LIST: `${BASE_PATH.ADMIN}/categories`,
저는 요런식으로 지었는데 한번 논의가 필요할거 같네요!!
![image](https://github.com/woowacourse-teams/2023-votogether/assets/81199414/e5ce4ebb-1ab3-4f46-8317-39c24aaca54a)

2023-10-16 12:26 UTC, inyeong-kang commented on frontend/src/routes/PrivateRoute.tsx
> +  if (isAdminAllowed && userInfo?.role !== 'ADMIN') {
context-api 로 role 값을 저장하는 경우, 관리자 페이지에 진입하면서 role을 useContext로 꺼내오기 때문에, 의도대로 페이지 진입을 막기 어려워지지 않을까요?🤔

`개인정보 등록 페이지`도 같은 이슈가 있어서, hasEssentialInfo 라는 값을 userInfo (유저 정보 API response)가 아닌 로그인 API response에서 받아오도록 했어서.. 우스의 생각이 궁금합니다!!

2023-10-17 05:19 UTC, inyeong-kang approved these changes
오늘 2시 페어프로그래밍을 통해 충돌이 예상되는 부분을 해결하였습니다~~

2023-10-18 01:41 UTC, chsua requested changes
우스 최강입니다!!

혹시 그 프라이빗 라우터에 ``` isGuestAllowed={true}>```이던데, 
게시글 상세페이지와 랭킹페이지는 true처리가 안된 것 같아요!
필요할 것 같습니다! 

그리고 pr에도 admin/category 로 되어있는데 해당 부분 나중에 다시 보면 헷갈릴 것 같아서 수정 가능할까요??
고생하셨습니다!

2023-10-18 01:41 UTC, chsua commented on frontend/src/constants/path.ts
> +  ADMIN_PENDING_REPORT: `${BASE_PATH.ADMIN}${BASE_PATH.REPORTS}/pending`,
pending이 되었군요 😆

2023-10-18 01:41 UTC, chsua commented on frontend/src/routes/router.tsx
> +            <div>어드민 카테고리 목록 페이지</div>
여기 수정 안되었습니다!

2023-10-18 01:42 UTC, chsua commented
fe-리뷰완

2023-10-18 05:55 UTC, Gilpop8663 commented
<img width="1440" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/80146176/5ba8a1fc-a6ae-4468-af54-b29f615d6484">

대시보드에서 접근 가능하도록 했습니다

fe-리뷰요청

2023-10-18 06:06 UTC, chsua approved these changes
고생하셨습니다!!

작성하신 코드 롤백되어서 아쉽네요!
빠른 피드백, 수정 최고에요!

2023-10-18 06:07 UTC, merged