관리자 신고 목록 페이지 구현
woowacourse-teams/2023-votogether pull request #755
Opened 2023-10-16 12:40 UTC by inyeong-kang

## 🔥 연관 이슈

close: #730 

## 📝 작업 요약
* 관리자 신고 목록 페이지 UI 구현
* 관리자 신고 목록 및 신고 조치 API fetch 함수 및 커스텀 쿼리 구현

## ⏰ 소요 시간
2일 (Table 컴포넌트를 디자인 시스템으로 배포하는 시간까지 포함)

## 🔎 작업 상세 설명
* 디자인 시스템의 [Table 컴포넌트](https://github.com/VoTogether-Design-System/design-system/tree/main/src/lib/Table) 구현 및 배포 
* 관리자 신고 목록 페이지 UI 구현 (src/pages/admin/PendingReportPage)
* 관리자 신고 목록 및 신고 조치 API fetch 함수 및 커스텀 쿼리 구현
  * query/report/usePendingReportActionList (신고 목록 조회)
  * query/reportuseReportAction (신고 조치) 
  * api/report -> getPendingReportActionList, reportAction
* 관리자만 접근 가능하도록 라우팅 제한

## 🌟 논의 사항
현재 Table 컴포넌트에서 각 열의 비율(? 너비?)을 지정해주려면 `1fr 2fr 3fr` 이런 식으로 props 값을 넘겨줘야 하는데요, 이 방식 외에 뾰족한 수가 떠오르지 않아 일단 이렇게 했습니다,, 혹시 더 괜찮은 방식이 떠오르신다면 마음껏 제안 부탁드려요🥺

2023-10-17 03:24 UTC, Gilpop8663 requested changes
몇개 코멘트 남겼습니당

빠르시네요!

> 현재 Table 컴포넌트에서 각 열의 비율(? 너비?)을 지정해주려면 1fr 2fr 3fr 이런 식으로 props 값을 넘겨줘야 하는데요, 이 방식 외에 뾰족한 수가 떠오르지 않아 일단 이렇게 했습니다,, 혹시 더 괜찮은 방식이 떠오르신다면 마음껏 제안 부탁드려요🥺

저도 1fr 2fr 3fr과 같이 사용하는 방법 이외에 마땅히 생각나는 것이 없네용

겹치는 코드가 몇개 있어서 같이 이야기 나눠보아요

2023-10-17 03:24 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-17 03:26 UTC, inyeong-kang commented on frontend/src/pages/admin/PendingReportPage/index.tsx
> +        {isLoading && <LoadingSpinner size="md" />}
앗 그러네요........ ㅎㅎㅎ 알려주셔서 감사합니다! Suspense 로 Fallback UI 그리는 방식으로 수정할게요~~

2023-10-17 03:27 UTC, inyeong-kang commented on frontend/src/hooks/query/report/useReportAction.ts
> +      queryClient.invalidateQueries({ queryKey: [QUERY_KEY.REPORT, LOGGED_IN] });
흠 굳이 로그인 여부가 필요하진 않겠네요,, LOGGED_IN 은 삭제하겠습니다!

2023-10-17 05:33 UTC, inyeong-kang commented on frontend/src/types/report.ts
> +export interface PendingReportActionListResponse {
원래 저희가 Response 관련 type은 api 파일에 두기로 했었는데, 이렇게 타입을 Omit 하고 추가해주는 과정이 복잡하다보니,, 
이런 경우에는 빠른 이해를 돕기 위해 Response prefix의 type도 여기에 두는게 낫겠다고 판단했습니다!!
혹시 다른 분들은 어떻게 생각하시는지 궁금해요~!

2023-10-17 06:07 UTC, Gilpop8663 approved these changes
코드 변경된 부분 확인 후 어프로브 했습니다~~ 👍👍👍

2023-10-17 06:15 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-17 16:00 UTC, Gilpop8663 commented on frontend/src/types/report.ts
> +export interface PendingReportActionListResponse {
Omit을 사용하는 경우 같이 두는 것이 코드 가독성 측면에서 더 좋아보여요

Omit을 사용하지 않는 경우에는 타입과 타입 Response까지 함께 볼 상황이 많지 않기 때문에 api로 분리했다라고 생각이 들어요

2023-10-18 02:37 UTC, chsua approved these changes
깔끔한 페이지 너무 좋아요.
빠른 시간 안에 UI까지 챙긴 페이지라니 bb

몇몇가지 코멘트 달았습니다.
고칠 부분이 없어서 코멘트가 많지는 않습니다!
고생하셨습니다

fe-리뷰완

2023-10-18 02:37 UTC, chsua commented on frontend/src/hooks/query/report/usePendingReportActionList.ts
> +  const { data, error, isLoading, isError } = useQuery<PendingReportActionList>(
isLoading, isError가 현재는 사용되지 않는데, 사용할 때 작성해도 좋을 것 같아요.

2023-10-18 02:37 UTC, chsua commented on frontend/src/pages/admin/PendingReportPage/index.tsx
> +  const columnList = ['Id', '사유', '내용', '일시', '종류', '수정/삭제', '신고 해제'];
UI를 보았을때 내용과 일시의 열 제목이 바뀐것같아요.

2023-10-18 02:37 UTC, chsua commented on frontend/src/pages/admin/PendingReportPage/index.tsx
> +    const editOrDelete = isEdit ? '수정' : '삭제';
```
export const REPORT_TYPE = {
  POST: '게시글',
  COMMENT: '댓글',
  NICKNAME: '닉네임',
} as const;

export const REPORT_ACTION_TYPE = {
  [REPORT_TYPE.POST]: '삭제',
  [REPORT_TYPE.COMMENT]: '삭제',
  [REPORT_TYPE.NICKNAME]: '수정',
} as const;
```

위에 이런 코드가 있는데 이를 사용하면 좋을 것 같아요.

```
// 수정전 
 isEdit: report.typeName === REPORT_TYPE.NICKNAME, 

action: REPORT_ACTION_TYPE[report.typeName]

```

2023-10-18 02:37 UTC, chsua commented on frontend/src/types/report.ts
> +export interface PendingReportActionListResponse {
기존 a-Response와 a와도 크게 차이가 없는데 따로 분리해두었다고 생각합니다.
(간혹 헷갈리기도..ㅎ 두개가 연관되어 있지 않아서 생각보다 어렵더라구요)

그래서 기존에 있던 것들을 기존 방식대로 한다면 따로 두고, 
만약 omit으로 인해 같이 둔다면 다른 타입도 위치하는 곳을 다시 고려해봤으면 좋겠습니다.
결국, 통일성이 제일 중요하다고 생각합니다.

2023-10-18 02:47 UTC, inyeong-kang commented on frontend/src/types/report.ts
> +export interface PendingReportActionListResponse {
오 저는 사실 팀원 분들만 안 헷갈리면 크게 상관은 없어요😀
파일 왔다갔다 하는 수고가 고려해서 같은 파일에 뒀는데, 수아 말대로 통일성 있게 컨벤션대로 하는 것도 좋겠네요~

2023-10-18 02:57 UTC, inyeong-kang commented on frontend/src/pages/admin/PendingReportPage/index.tsx
> +  const columnList = ['Id', '사유', '내용', '일시', '종류', '수정/삭제', '신고 해제'];
앗 수정했습니다~!😀😄

2023-10-18 03:01 UTC, inyeong-kang commented on frontend/src/hooks/query/report/usePendingReportActionList.ts
> +  const { data, error, isLoading, isError } = useQuery<PendingReportActionList>(
오 이런 쿼리함수들(useUserRanking)이 몇 개 더 있는거 같네요! 일단 error, isLoading, isError는 삭제해둘게요~

2023-10-18 03:17 UTC, inyeong-kang commented on frontend/src/pages/admin/PendingReportPage/index.tsx
> +    const editOrDelete = isEdit ? '수정' : '삭제';
와우~ 타입 재사용하고 너무 좋은데요? 수정했습니다!

2023-10-18 03:26 UTC, merged