Feat/#744
woowacourse-teams/2023-votogether pull request #756
Opened 2023-10-16 13:05 UTC by aiaiaiai1

## 🔥 연관 이슈

close: #

## 📝 작업 요약

수행할 작업을 1~2줄 사이로 요약해주세요.

## ⏰ 소요 시간

기능 구현에 소요된 시간을 적어주세요. (추정했던 시간과 다르다면 이유도 함께)

## 🔎 작업 상세 설명

주요 기능 및 로직에 관해 설명해주세요.

## 🌟 논의 사항

크루들과 이야기 해보고 싶은 부분을 적어주세요.

2023-10-16 17:00 UTC, woo-chang requested changes
안녕하세요 루쿠 ㅎㅎ 다즐입니다

빠르고 깔끔하게 구현 잘 해주셨네요 👍
몇 가지 소소한 커멘트 남겨두었으니 확인해주시면 감사합니다 :)

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/entity/ReportActionAlarm.java
> +    @ManyToOne
`fetch` 타입 설정이 필요해 보여요 !

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/entity/ReportToAction.java
> +public class ReportToAction extends BaseEntity {
`ERD`에서 해당 도메인이 삭제된 것으로 이해했는데 맞을까요?

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +@RequestMapping("/alarms")
```java
@Validated
@RequiredArgsConstructor
@RequestMapping("/alarms")
@RestController
```
다른 컨트롤러와 일관성있게 순서를 맞춰주면 감사합니다 :)

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionAlarmResponse.java
> +        @Schema(description = "알림 ID", example = "1")
불필요한 공백 발견 👀

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionAlarmResponse.java
> +
여기도 공백 발견 👀

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +    }
`@Transactional` 어노테이션이 빠져있어요 !

2023-10-16 17:00 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/alarm/controller/AlarmControllerTest.java
> +        given(alarmService.getReportActionAlarms(any(Member.class), anyInt()))
개행없이 붙이는 것에 대해서 어떻게 생각하시나요? 😃

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionResponse.java
> +
개행 정리해주시면 감사합니다 😚

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionResponse.java
> +public record ReportActionResponse(
어떤 응답인지에 대한 설명도 추가해주면 좋을 것 같아요 :)

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +        return ResponseEntity.ok().body(reportActionAlarms);
```java
return ResponseEntity.ok(reportActionAlarms);
```
요런 방법은 어떤가요?!

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +        return ResponseEntity.ok().body(response);
`ditto`

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByIdAndMember(reportActionAlarmId, member)
`id`로 찾게되면 `member`없이도 항상 `id`를 통해서만 조회되지 않을까요?

`member`를 추가적으로 찾는 조건으로 넣은 이유가 궁금해요 🤓

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/exception/ReportActionAlarmExceptionType.java
> +}
개행 발견 👀

2023-10-16 17:00 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmControllerDocs.java
> +
이상한 개행이 있어요 🥲

2023-10-17 05:38 UTC, tjdtls690 requested changes
루쿠 고생하셨어요!
몇 가지 리뷰 남겼습니다 :)

2023-10-17 05:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +            @RequestParam @PositiveOrZero(message = "페이지는 0이상 정수만 가능합니다.") final int page,
@RequestParam 는 생략해도 될 것 같아요 :)

2023-10-17 05:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +public class AlarmController implements AlarmControllerDocs {
조회에 관한 API만 존재하니 AlarmController -> AlarmCommandController 로 바꿔야 할 것 같아요.

2023-10-17 05:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +        final PageRequest pageRequest = PageRequest.of(page, 10, Sort.by(Sort.Direction.DESC, "createdAt"));
일관성과 가독성을 위해서 10을

```java 
private static final int BASIC_PAGE_SIZE = 10;
```

이렇게 상수화 해주는 것은 어떨까요.

2023-10-17 05:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionAlarmResponse.java
> +
위에 다즐도 적어주셨지만, record의 파라미터 적는 곳에선 앞 뒤 공백이 없어야 하는 것으로 알고 있습니다 :)

2023-10-17 05:38 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostQueryService.java
>                  post,
```java
return PostResponse.ofUser(
                    loginMember,
                    post,
                    postCategoryRepository.findAllByPost(post),
                    post.getFirstContentImage(),
                    post.getPostOptions(),
                    voteRepository.findByMemberAndPostOptionPost(loginMember, post)
            );
```

이 부분이 완전히 바로 밑에 return문과 중복되는 것으로 보여서 따로 메서드로 빼는 것은 어떨까요?? 

보니까 PostQueryService의 가장 밑에 있는 메서드인 convertToResponses 에서도 위의 return문과 완전 똑같은 로직이 존재하는데, 그거까지 같이 처리할 겸, 위 return문을 메서드로 분리해 보는 것이 좋을 것 같아요 :)

2023-10-17 05:44 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/entity/ReportActionAlarm.java
> +    @ManyToOne
빼먹었네요! 감사합니다~

2023-10-17 05:44 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/entity/ReportActionAlarm.java
> +    public ReportActionAlarm(
수정했습니다!

2023-10-17 05:45 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/entity/ReportToAction.java
> +public class ReportToAction extends BaseEntity {
네 맞아요 삭제해두었씁니다

2023-10-17 05:55 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmControllerDocs.java
> +
개행 빌런이네요 ㅋㅋ

2023-10-17 05:56 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/dto/ReportActionResponse.java
> +public record ReportActionResponse(
추가하였습니다~!

2023-10-17 06:02 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByIdAndMember(reportActionAlarmId, member)
api요청으로 사용자가 다른 사용자의 알림을 조회 하는 경우를 막기위해 member조건을 추가해주었습니다!

2023-10-17 06:02 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +            @RequestParam @PositiveOrZero(message = "페이지는 0이상 정수만 가능합니다.") final int page,
다른 컨트롤러에서 @RequestParam 을 명시해두어서 여기서도 따로 생략하지는 않았습니다!

2023-10-17 06:14 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostQueryService.java
>                  post,
메서드 추출해서 중복 제거해보았습니다 훨씬 깔끔해졌네요 ㅎㅎ

2023-10-17 06:20 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByIdAndMember(reportActionAlarmId, member)
와 전혀 생각지도 못한 부분인데 꼼꼼하게 구현해주셨네요 대박 배워갑니다 👍👍

2023-10-17 06:21 UTC, woo-chang approved these changes
생각지도 못한 부분에서 예외가 발생할 수 있다는 점을 배워갈 수 있었습니다 👍

잘 구현해주셔서 approve 하도록 할께요 ㅎㅎ 수고하셨습니다 :)

2023-10-17 06:54 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmController.java
> +            @RequestParam @PositiveOrZero(message = "페이지는 0이상 정수만 가능합니다.") final int page,
생각해보니 다 붙이고 있었네요...ㅋㅋ

2023-10-17 07:00 UTC, tjdtls690 approved these changes
역시 ㅡ 쿠 ㅡ
꼼꼼한 테스트 코드와 유효성 검증이 좋았습니다 ㅎ

2023-10-17 07:09 UTC, merged

2023-10-17 07:32 UTC, jeomxon reviewed
멋지게 구현해주셨네요!
사소한 궁금증 코멘트로 남겨보았습니다 :)

2023-10-17 07:32 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/alarm/controller/AlarmCommandController.java
> +            @Auth final Member member
`P2`
일관성 있게 loginMember로 변경하는 것이 좋아보입니다.

2023-10-17 07:32 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByMember(member, pageRequest);
`Q`
Repository에 메서드명에 orderBy로 날짜 정렬을 하는 것과 Pageable을 통해서 정렬하는 방식의 차이는 무엇인가요?

2023-10-17 07:32 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByIdAndMember(reportActionAlarmId, member)
이 코멘트를 보고 궁금한 점이 생겼는데 다른 사용자의 알림이 의도적으로 조회가 가능한가요?

2023-10-17 07:32 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
> +                .when().get("/alarms/report?page=0")
`P2`
`queryParam()`을 사용해볼 수 있을 것 같아요.

2023-10-17 07:32 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
> +                .as(new ParameterizedTypeReference<List<ReportActionAlarmResponse>>() {
`Q`
`TypeRef`를 사용할 수도 있지 않나요? 어떤 차이가 있나요?

2023-10-18 03:34 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByMember(member, pageRequest);
이런방법이...! JPA 학습 부족입니다 ㅎㅎ

2023-10-18 04:43 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/alarm/service/AlarmService.java
> +                .findByIdAndMember(reportActionAlarmId, member)
백엔드서버로 직접 api를 알림id만 바꾸어 쏘면 조회가 가능할거같아요

2023-10-18 04:44 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
> +                .when().get("/alarms/report?page=0")
감사합니다~

2023-10-18 04:53 UTC, aiaiaiai1 commented on backend/src/test/java/com/votogether/domain/alarm/controller/AlarmCommandControllerTest.java
> +                .as(new ParameterizedTypeReference<List<ReportActionAlarmResponse>>() {
간단한 방식이 있었네요!
저도 궁금해서 지피티에 물어보니 TypeRef는  RestAssured 라이브러리에서 제공되고
ParameterizedTypeReference는 Spring Framework에서 제공된다고 하네요