디자인 시스템의 ResponsiveFlex 컴포넌트를 PostForm 페이지에 적용
woowacourse-teams/2023-votogether pull request #765
Opened 2023-10-17 07:56 UTC by inyeong-kang

## 🔥 연관 이슈

close: #742 

## 📝 작업 요약

디자인 시스템의 ResponsiveFlex 컴포넌트를 PostForm 페이지에 적용하였습니다.

## ⏰ 소요 시간
1시간

## 🔎 작업 상세 설명
ResponsiveFlex 컴포넌트 props는 아래와 같습니다. [자세한 코드는 여기에](https://github.com/VoTogether-Design-System/design-system/tree/feat/%2313/src/lib/ResponsiveFlex)
```tsx
interface ResponsiveFlexProps extends PropsWithChildren {
    /**
     * breakpoint that arranges children from horizontal to vertical (min-width: breakpoint)
     */
    breakpoint: StringPixel;
    /**
     * gap between two children when width is less than breakpoint
     */
    $smGap?: StringPixel;
    /**
     * gap between two children when width is no less than breakpoint
     */
    $lgGap?: StringPixel;
    /**
     * ratio of left-sided child(first index of children)
     * unit is percent (ex. 40%)
     * (if 70%, right-sided is automatically 30%)
     */
    ratio?: number;
    /**
     * margin of Flex when width is less than breakpoint
     */
    $smMargin?: MarginPadding;
    /**
     * padding of Flex when width is less than breakpoint
     */
    $smPadding?: MarginPadding;
    /**
     * margin of Flex when width is no less than breakpoint
     */
    $lgMargin?: MarginPadding;
    /**
     * padding of Flex when width is no less than breakpoint
     */
    $lgPadding?: MarginPadding;
    /**
     * justify-content of Flex
     */
    $justifyContent?: string;
    /**
     * align-items of Flex
     */
    $alignItems?: string;
    /**
     * children of Flex, The number of children should be 2
     */
    children: [ReactNode, ReactNode];
}
```
## 🌟 논의 사항
* gap 을 너비가 작을 때와 너비가 클 때를 구분해서 받는 것이 좋아보여서 (padding 이나 margin 처럼 통일성을 주기 위해..?), $smGap, $lgGap 으로 따로 받는 방식으로 변경하였습니다!
* $smGap 에 `gap`과 같이 DOM attribute 와 동일한 값이 있으면 노란색 경고 메시지가 사용처에 뜨더라구요.. 네이밍을 어떻게 해야할지 좋은 아이디어 생각나면 알려주시면 매우 감사하겠습니다!!

2023-10-17 14:33 UTC, Gilpop8663 requested changes
fe-리뷰완

2023-10-17 14:33 UTC, Gilpop8663 commented on frontend/src/components/PostForm/index.tsx
> +          breakpoint={theme.breakpoint.sm}
![image](https://github.com/woowacourse-teams/2023-votogether/assets/80146176/9f9faf71-540c-4687-952e-959e19d44353)

theme.breakpoint.sm이 number가 아니래요

아래의 ResponsiveFlexProps 타입에서 breakpoint를 옵셔널로 받아서 보투게더 프로젝트에서 사용할 때는 주지 않는 것은 어떠세요? 아니면 string 값을 받아도 좋을 것 같아요
```tsx
import { StringPixel } from '../types';
interface ResponsiveFlexProps extends PropsWithChildren {
    /**
     * breakpoint that arranges children from horizontal to vertical (min-width: breakpoint)
     */
    breakpoint: number;
```

2023-10-17 14:43 UTC, Gilpop8663 approved these changes

2023-10-17 14:44 UTC, Gilpop8663 commented
fe-리뷰완

2023-10-18 01:57 UTC, inyeong-kang commented on frontend/package.json
> +    "votogether-design-system": "^0.0.14"
반영했습니다~~~

2023-10-18 02:43 UTC, chsua approved these changes
앞으로 디자인 시스템에 더 많은 것들을 옮기면 너무 좋을 것 같아요! 
기대가 됩니다 bb
고생하셨습니다!

2023-10-18 02:43 UTC, chsua commented on frontend/package.json
> +    "votogether-design-system": "^0.0.14",
👍👍👍👍

2023-10-18 02:43 UTC, merged