회원가입 및 로그인 & 인가 기능 구현
woowacourse-teams/2023-votogether pull request #82
Opened 2023-07-19 02:29 UTC by jeomxon

## 🔥 연관 이슈

close: #29 

## 📝 작업 요약

멤버 인증 인가 구현했습니다.

## 🔎 작업 상세 설명

OAuth로 정보를 가져와서 저장하는 기능
Member의 닉네임을 랜덤으로 생성하는 기능
JWTProcessor를 통해 토큰을 생성하는 기능
JwtFilter 구현
JwtArgumentResolver 구현

test 환경분리

## 🌟 논의 사항

accessToken에 들어가야할 정보에 대해서 논의하고 싶습니다.
JwtAuthenticationFilter에서 허용 시킬 URI를 어떤 방식으로 관리하면 좋을지 논의하고 싶습니다.

2023-07-19 06:05 UTC, woo-chang reviewed
수고하셨습니다 저문 🙇🏻‍♂️
전체적으로 코드가 깔끔하고 가독성이 좋아서
어떤 동작을 하는지 이해하기 쉬워서 긴 코드임에도 쉽게 리뷰할 수 있었습니다~
몇 가지(적다보니 30개나 되네요..) 코멘트와 질문 남겨두었으니 확인 부탁드립니다 :)

2023-07-19 06:05 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +        }
`P2` : 혹시 확인하지 못한 예외를 위해 `Exception` 상황도 추가하는건 어떤가요?

2023-07-19 06:05 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +    public TokenPayload parseToken(final String token) throws JsonProcessingException {
`P1` : 토큰을 파싱하는 상황에서 토큰의 유효성 검사가 선행되어야 하지 않을까요?

2023-07-19 06:05 UTC, woo-chang commented on backend/src/main/resources/application.yml
> +    expiration-time: ${EXPIRATION_TIME}
`P1` : 중요한 정보는 환경 변수 좋아요 👍🏻

2023-07-19 06:05 UTC, woo-chang commented on backend/src/test/resources/application.yml
> +    prod-url: http://votogether.com
`Q` : 위의 정보는 없어도 `src`파일의 `application.yml`로 동작하지 않나요? (진짜 궁금)

2023-07-19 06:05 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +}
`P1` : `jwt` 디렉토리에 있는 기능들도 테스트 작성해보면 좋을 것 같습니다 :)

2023-07-19 06:07 UTC, tjdtls690 reviewed
OAuth의 권위자 저문

2023-07-19 06:07 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +    MockMvc mockMvc;
P1 : RestAssuredMockMvc 쓸 때, MockMvc는 Autowired 안해줘도 됩니다!

2023-07-19 06:07 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +                .asString();
extract로 꺼내서 given, when, then을 명확히 구분하는게 인상적이네요 👍

2023-07-19 06:07 UTC, jeomxon commented on backend/build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
jjwt 최신 버전으로 가져왔습니다!
최신버전이 배포된 지 1년이 지난 시점이라 안정적이게 사용할 수 있을 것이라 판단한 것도 있습니다.

2023-07-19 06:08 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +@Tag(name = "회원가입", description = "회원가입 및 로그인 API")
동의합니다.
수정해보겠습니다~

2023-07-19 06:09 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    @ApiResponse(responseCode = "200", description = "로그인 성공")
진짜 믿을지 모르겠지만 이거 지적 안나오면 리뷰 재요청하려고 했습니다.
추가하겠습니다 ㅎㅎ

2023-07-19 06:11 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/dto/KakaoMemberResponse.java
> +    }
해당 record내부에서만 사용할 것이고, 추가적인 확장성이 없다고 판단해서 내부에 선언했습니다.

2023-07-19 06:11 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +        this.objectMapper = new ObjectMapper();
정말 좋은 생각이라 생각합니다 👍👍

2023-07-19 06:14 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/AuthService.java
> +    public String register(final String code) {
엄청난 문제가 발생할 것 같네요...
lock에 관련된 문제라든가...
큰 걸 깜빡했습니다... 수정할게요!

2023-07-19 06:16 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
> +    private static final RestTemplate restTemplate = new RestTemplate();
빈으로 등록하면 추가적인 작업을 커스텀하여 할 수 있을 것 같은데,
더 이상의 작업이 이루어지지  않을 것 같다고 판단하여서 빈으로 등록하지 않았습니다.

2023-07-19 06:18 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
> +                info,
`x-www-form-urlencoded`의 형식으로 지정되어
key, value형태의 응답이 나가게 됩니다!

2023-07-19 06:21 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
> +                request,
사실 메서드를 여러가지 활용해보기 위함도 있었는데요, 직접 사용해보면서 장단점을 알게되었습니다.
getForObject는 header를 따로 지정할 수 없더라구요.
따라서 token을 포함한 header를 지정하기 위해서 이 클래스에 존재하는 두개의 역할에 RestTemplate에서 제공하는 다른 메서드를 사용했습니다.

2023-07-19 06:22 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/Member.java
> +        final NicknameNumberGenerator nicknameNumberGenerator = new NicknameNumberGenerator();
레전드 오류를 발견하셨네요...
바로 수정 작업 들어가겠습니다. 그리고 좀 더 효과적인 랜덤 닉네임 방법에 대해서 같이 고민해보면 좋을 것 같아요~

2023-07-19 06:25 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/service/MemberService.java
> +@Transactional(readOnly = true)
어떤 방식이든 통일성있게 간다면 좋을 것 같다는 생각이었습니다.
메서드 개수가 작은 지금 시점에서는 각 메서드마다 붙여주는 것이 더 직관적이라는 생각이 드네요.
수정하겠습니다~

2023-07-19 06:29 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
> +@RequiredArgsConstructor
통일성있게 수정해보겠습니다~

2023-07-19 06:32 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +@Slf4j
validateToken메서드에 try catch부분에 로그를 남기는 곳이 있습니다!

2023-07-19 06:36 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthorizationArgumentResolver.java
> +        return memberService.findById(tokenPayload.memberId());
여기서 사실 공백 줄까말까 고민을 좀 하긴 했었는데, 어떻게 봐도 이상하지 않다는 생각이 들긴하네요.
다즐이 좋다고 하니 반영하겠습니다~^^

2023-07-19 07:47 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +        return ResponseEntity.ok(new LoginResponse(token));
소셜타입별로 추상화를 해보고자 처음에 이렇게 설계했는데,
지금으로써는 response를 반환하는 것이 통일성을 좀 더 가져갈 수 있을 것 같네요.
그리고 확실하게 추상화를 시킬 수 있다는 보장이 없기도 해서 response를 반환하도록 변경해볼게요!

2023-07-19 08:27 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthorizationArgumentResolver.java
> +        return parameter.hasParameterAnnotation(Auth.class);
`withContainingClass`를 이용해서 Member로 제한을 두었습니다!

2023-07-19 08:27 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenPayload.java
> +        Long exp
수정했습니다~

2023-07-19 08:29 UTC, aiaiaiai1 requested changes
저문 새로운개념 공부하면서 기능 구현하느라 고생하셨습니다 🙇
저는 머리가 어지럽네요 간단한 코멘트 남겨드렸습니다
고생하셨어요~

2023-07-19 08:29 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
> +    private final MultiValueMap<String, String> info = new LinkedMultiValueMap<>();
`Q` :  `@ConfigurationProperties(prefix = "oauth.kakao")`이 어떤 역할인가요??
xml 에 파일에 있는 info정보가 `MultiValueMap<String, String> info = new LinkedMultiValueMap<>();`와 매핑되어 들어가지는 건가요??

2023-07-19 08:29 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/member/entity/NicknameNumberGenerator.java
> +    private int number = 0;
`Q` 만약 서버를 껐다가 다시 키게되면 랜덤값이 다시 0부터 초기화 되지 않나요??

2023-07-19 08:31 UTC, jeomxon commented on backend/src/test/resources/application.yml
> +    prod-url: http://votogether.com
맞습니다. 동작해요...
오히려 적는 것이 기존에 있던 테스트 환경을 변화시키더라구요.
환경변수 부분을 제외하고는 삭제했습니다!

2023-07-19 08:33 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +    public TokenPayload parseToken(final String token) throws JsonProcessingException {
filter에서 토큰 유효성을 검사하고 들어오는데, 여기서도 중복하여 검증한다고 생각해서 진행하지 않았습니다.
혹시 진행해야할 다른 이유가 있을까요?

2023-07-19 08:44 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +        this.objectMapper = new ObjectMapper();
빈으로 등록했습니다!
사용 빈도가 높아서 등록하면 좋을 것 같네요ㅎㅎ

2023-07-19 08:56 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +        }
`parseClaimJws()`에서 발생할 수 있는 5가지 에러에 대해서 현재 예외처리를 한 상태였습니다.
확인하지 못한 예외가 어디서 발생할지 짐작이 안가긴하지만,
혹시 어디서 발생할지 모르는 예외에 대한 대비를 위해 `Exception`상황도 추가해보겠습니다.

2023-07-19 08:58 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    public ResponseEntity<LoginResponse> loginByKakao(@RequestParam("code") final String code) {
명시적 표현을 위해서 지정해줬는데 제거하는 것도 깔끔하고 좋아보이네요!

2023-07-19 09:01 UTC, jeomxon commented on backend/src/test/java/com/votogether/domain/auth/controller/AuthControllerTest.java
> +    MockMvc mockMvc;
마이그레이션 과정에서 지워야하는데 그러지 못했네요.
꼼꼼하게 확인하도록 하겠습니다!

2023-07-19 10:12 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
> +    private final MultiValueMap<String, String> info = new LinkedMultiValueMap<>();
그런 이유는 아니예요. 보편적으로 MultiValueMap이 사용되는 것입니다.
MultiValueMap은 하나의 key에 여러 개의 value가 들어갈 수 있는 구조입니다.
예를들어 파라미터로 하나의 키에 다중 값이 들어오는 경우를 생각해볼 수 있습니다.
해당 경우에는 단순 HashMap과 같은 자료구조로는 값을 전부 담기 힘듭니다.
따라서 이와 같은 경우를 대비해서 MultiValueMap을 사용한다고 볼 수 있습니다.

2023-07-19 11:57 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    public ResponseEntity<LoginResponse> loginByKakao(@RequestParam("code") final String code) {
좋은 지적 감사합니다 ㅎㅎ
테스트코드에서 loginByKakao로 바꾸는 것이 더 좋을 것 같아서 그렇게 변경해볼게요~

2023-07-19 11:57 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/KakaoOAuthClient.java
> +    private final MultiValueMap<String, String> info = new LinkedMultiValueMap<>();
맞습니다 yml파일에 있는 환경변수들을 매핑해주기 위해서 사용하고 있습니다.
oauth.kakao.info에 있는 key value가 매핑이 됩니다!

2023-07-19 12:08 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/member/entity/NicknameNumberGenerator.java
> +    private int number = 0;
정확합니다...
긴급 조치 시행했습니다..!

2023-07-19 12:09 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
> +    }
어떤식으로 메서드를 분리해야할지 감이 잘 안잡히는데 혹시 예시를 보여주실 수 있나요?

2023-07-19 12:19 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
> +        tokenProcessor.validateToken(tokenWithoutType);
validateToken을 다른 부분에서도 검증용도로 사용할 수 있을 것 같아서 public으로 사용했습니다.
parseToken에서도 검증이 필요하다는 다즐의 의견도 있어서 한번 다 같이 모여서 의견을 들어보고 싶네요.
어떤 방향으로 token을 검증할지 이야기해보면 좋을 것 같아요 :)

2023-07-19 12:44 UTC, woo-chang commented on backend/build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'
배포된지 오래되어야 안정적일까요 아니면 배포가 자주 일어나야 안정적일까요 🤔

2023-07-19 12:45 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/dto/KakaoMemberResponse.java
> +        @JsonProperty("kakao_account") KakaoAccount kakaoAccount
꼼꼼한 학습까지 너무 좋습니다 :)

2023-07-19 12:49 UTC, woo-chang commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +    public TokenPayload parseToken(final String token) throws JsonProcessingException {
항상 유효성 검사가 선행되면 문제없지만 메서드가 분리되어있는만큼 안전하지 않은 토큰을 호출할 수 있는 상황에 대해서도 고려해 보았습니다 😄

2023-07-19 14:49 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
> +public class JwtAuthenticationFilter extends OncePerRequestFilter {
사실 선택하는 과정에서 고민이 조금 있었는데요.
실제로 OncePerRequestFilter는 GenericFilterBean을 상속받는 구조였습니다.
동작방식에서는 약간의 차이가 있었는데요.
OncePerRequestFilter는 이름 그대로 요청이 왔을 때 단 한번만 필터를 거치도록 설계되어있습니다.
GenericFilterBean은 그에 비해 내부적으로 여러번 필터를 거치는 과정이 생길 수도 있습니다.

SpringSecurity를 적용할 때는 OncePerRequestFilter를 인증, 인가과정에서 주로 사용하는 것으로 보였습니다.
SpringBoot의 Filter와 Security의 FilterChain사이에서 Filter가 두번 등록되어서 그렇다고 하는데...
Security를 직접 사용해본 적이 없어서 잘 와닿지가 않았습니다.

내부적으로 redirect하는 경우도 현재는 없기 때문에 어떤 것을 사용해도 문제가 되지 않을 것 같다는 생각은 듭니다.
그래서 단순히 인증, 인가에 대해서는 여러번 호출될 필요없이 한번만 호출되면 된다는 관점에서 OncePerRequestFilter를 사용했습니다.
추가적으로 학습을 하면 좋을 것 같은 부분이지만, 시간이 좀 걸릴 것 같다는 생각이 드네요..!
다즐도 아는 부분이 있으시면 공유해주시면 좋을 것 같아요 :)

2023-07-19 14:59 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenProcessor.java
> +    public TokenPayload parseToken(final String token) throws JsonProcessingException {
고민끝에 validation을 각 메서드에 추가해주는 대신에
혹여나 사용할 수 있는 토큰 유효성 검증을 위해서 
validation을 하는 메서드의 접근 제어자를 public으로 열어두면 좋을 것 같다는 생각입니다.

2023-07-20 01:58 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/TokenPayload.java
> +        Long exp
수정을 하니깐 안돼서 이유를 찾아보니 Jwts에서 setIssuedAt과 setExpiration을 통해서 설정해주는 값은 자동으로 iat, exp로 설정이 되네요.
claim만 변수명을 설정해서 넣을 수 있다는 것을 알게 되었네요. 새롭게 배워갑니다~

2023-07-20 04:40 UTC, woo-chang reviewed
아주아주 사소한 커멘트 몇 가지만 남겼습니다 :)
수고하셨어요 저문 🙇🏻‍♂️👏🏻

2023-07-20 04:40 UTC, woo-chang commented on backend/src/test/resources/application.yml
> +    prod-url: http://aaaaaaaa.com
아아아아아아아아

2023-07-20 04:40 UTC, woo-chang commented on backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
> +    private ObjectMapper objectMapper;
`P2` : `@RepositoryTest`는 JpaConfig를 import하고 있으므로 빈으로 등록된 ObjectMapper를 사용해도 괜찮지 않을까요?

2023-07-20 04:40 UTC, woo-chang commented on backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
> +        tokenProcessor = new TokenProcessor(
`P3` : 동일한 TokenProcessor를 생성하는 동작으로 이해했습니다! 테스트마다 초기화해주는 이유가 있을까요 🤔

2023-07-20 04:48 UTC, jeomxon commented on backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
> +    private ObjectMapper objectMapper;
제가 등록해놓고도 인지를 못하고 있었네요...ㅎㅎ
수정하겠습니다!

2023-07-20 04:49 UTC, jeomxon commented on backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
> +        tokenProcessor = new TokenProcessor(
static하게 가져가면 좋을 것 같네요!
미처 생각하지 못했던 것 같아요. 수정하겠습니다~

2023-07-20 05:03 UTC, tjdtls690 approved these changes
👍👍👍👍👍

2023-07-20 05:08 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/dto/KakaoMemberResponse.java
> +    @JsonNaming(value = PropertyNamingStrategies.SnakeCaseStrategy.class)
원래는 @JsonProperty를 이용해서 각 필드를 snake case로 변경해주었는데요.
@JsonNaming을 사용하여 해당 클래스에 일괄적으로 직렬화, 역직렬화 시에 snake case로 적용할 수 있습니다.
카카오에서 제공하는 문서에 따르면 필드들이  snake case로 지정되어있어서 적용해주었습니다!

2023-07-20 05:08 UTC, jeomxon commented on backend/src/test/resources/application.yml
> +    prod-url: http://aaaaaaaa.com
으어어어어~

2023-07-20 05:16 UTC, aiaiaiai1 approved these changes
저문 확인 완료했습니다
피드백 반영하시느라 고생하셨어요~

2023-07-20 05:18 UTC, jeomxon commented on backend/src/test/java/com/votogether/global/jwt/TokenProcessorTest.java
> +        void resolveTokenFail(String prefix) {
올리자마자 확인해서 수정했습니다! ㅎㅎ

2023-07-20 05:21 UTC, jeomxon commented on backend/src/main/java/com/votogether/global/jwt/JwtAuthenticationFilter.java
> +    }
한 단계 추상화하는 방법도 좋다는 생각같아요 ㅎㅎ
다만 조금 더 로직이 커지게 된다면 분리하는 것이 어떨까?라는 생각입니다.
토큰을 resolve하고 parsing하는 과정이 잘 드러나서 아직까지는 분리 시점이라고 느끼지 않았습니다.
이 부분은 그대로 가져가보겠습니다!
생각하지 못했던 부분이었는데 언급해주셔서 감사합니다 :)

2023-07-20 05:21 UTC, merged