카카오 로그인 시 동시 로그인하는 상황이 발생하는 경우 같은 인가코드가 사용되는 문제
woowacourse-teams/2023-votogether pull request #828
Opened 2023-10-31 10:37 UTC by jeomxon

## 🔥 연관 이슈

close: #827 

## 📝 작업 요약

빈으로 등록된 클래스에서 상태로 가지고 있던 MultiValueMap을 메서드 내부로 이동시켰습니다.

## ⏰ 소요 시간

객체지향적으로 코드를 작성하기 위해 학습한 시간까지 포함하여 1시간!

## 🔎 작업 상세 설명

build.gradle의 환경변수 계층을 수정했습니다. (실제 환경변수와는 연관이 없어 실행하는데 문제 없음)
상태로 가지고 있던 MultiValueMap을 메서드 내부로 이동

## 🌟 논의 사항

없음.

2023-11-05 16:47 UTC, aiaiaiai1 requested changes
안녕하세요 저문 오랜만이네여
간단한 질문과 커멘트 남겨보았습니다!
보투게더 화이팅!!!!!

2023-11-05 16:47 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +        headers.set(HttpHeaders.AUTHORIZATION, "KakaoAK " + appAdminKey);
Q.
카카오 어드민키는 먼가요??  어디에 쓰이는거에요??

2023-11-05 16:47 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> -    private final MultiValueMap<String, String> info = new LinkedMultiValueMap<>();
Q.
같은 인가코드에 대한 로그인 에러가 발생한 원인이 이 필드로 상태를 가지고 있어서 라는 이유가 맞았나요??

2023-11-05 16:47 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +
P3
login 이라는 단어를 추가하신거같은데 메서드에도 login이라는 단어를 포함하는건 어떤가요??

2023-11-06 04:49 UTC, tjdtls690 requested changes
고생하셨습니다 ㅡ 문 ㅡ
몇 가지 질문 남겼습니다!

2023-11-06 04:49 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +        final MultiValueMap<String, String> info = makeKakaoInfo(code);
```Q```
MultivalueMap을 로컬 변수로서 일회성으로 사용하는 형태인데, 그러면 MultivalueMap 말고 그냥 HashMap을 써서 해도 되는 건 아닌지 궁금합니다!

2023-11-06 04:49 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +        headers.set(HttpHeaders.AUTHORIZATION, "KakaoAK " + appAdminKey);
저도 이 부분 궁금하네요. 카카오에 탈퇴 요청할 때 쓰이는 것 같긴 한데

2023-11-06 05:35 UTC, woo-chang requested changes
지속적으로 유지보수 가능한 서비스는 정말 중요한 것 같아요 👍

몇 가지 작은 코멘트 남겨두었으니 확인해주시면 감사합니다 ㅎㅎ

2023-11-06 05:35 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    public ResponseEntity<Void> disconnectFromKakao(@Auth final Member loginMember) {
회원 탈퇴 메서드인만큼 여기서도 회원 탈퇴에 대한 메서드명으로 수정해보는건 어떨까요?!

2023-11-06 05:35 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
> +    @ApiResponse(responseCode = "200", description = "회원 탈퇴 성공")
```suggestion
    @ApiResponse(responseCode = "204", description = "회원 탈퇴 성공")
```
실제 반환되는 상태 코드랑 다른 것 같아요 !

2023-11-06 05:35 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/dto/response/OAuthDisconnectResponse.java
> +}
```suggestion
public record OAuthDisconnectResponse(Long id) {
}
```
매개변수가 1개일 때도 내리는 편이신가요? 😀

2023-11-06 05:35 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +            @Value("${oauth.kakao.disconnect.admin-key}") final String appAdminKey
해당 `admin-key` 정보는 어디서 확인할 수 있는 정보인지 궁금합니다 !

2023-11-06 05:35 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +    public OAuthDisconnectResponse disconnectFromKakao(final Member member) {
`disconnect`시 어떤 흐름으로 동작이 실행되는지 한번 설명해주시면 감사합니다 🙇🏻‍♂️

2023-11-06 11:14 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +        headers.set(HttpHeaders.AUTHORIZATION, "KakaoAK " + appAdminKey);
[카카오 연결끊기 API](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#unlink)
위 링크를 확인하시면 보다 자세히 설명되어 있습니다!

카카오에 연결끊기 API를 요청하는 방법에는 2가지 방식이 존재합니다.
1. 헤더에 카카오에서 받은 액세스 토큰으로 API요청
2. 헤더에 서비스 앱 어드민 키 + 카카오에서 받은 user_id

1번 방법을 사용한 경우 서버에서는 카카오 로그인 시 카카오 서버로부터 발급받았던 액세스 토큰을 가지고 있어야합니다.
2번 방법을 사용하는 경우 현재 Member에 target_id라는 필드로부터의 값과 환경변수로 서비스 어드민 키를 등록하여 바로 구현할 수 있습니다.
따라서 변경점이 적고 현재의 방식으로도 쉽게 구현할 수 있도록 하다보니 2번 방식을 선택해서 구현했습니다.

2023-11-06 11:18 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> -    private final MultiValueMap<String, String> info = new LinkedMultiValueMap<>();
그렇게 추측하고 있습니다.
일단 확실히 문제가 있다는 것을 알 수 있었어요.

빈으로 등록되는 클래스는 스프링에서 싱글톤으로 관리되기 때문에 변경되는 상태를 가지고 있으면 위험한데,
현재 구조는 충분히 그런 위험성을 갖고 있습니다.
코드 라인을 조금 줄여서 깔끔하게 작성하고자 그런 시도를 했던 것 같은데 근본적인 원리에 대해서 잊고 개발을 했던 자신을 반성합니다🥲

2023-11-06 11:18 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +
좋아요 변경하겠습니다!

2023-11-06 11:34 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthController.java
> +    public ResponseEntity<Void> disconnectFromKakao(@Auth final Member loginMember) {
수정하겠습니다!

2023-11-06 11:34 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/controller/AuthControllerDocs.java
> +    @ApiResponse(responseCode = "200", description = "회원 탈퇴 성공")
확인하지 못했네요..! 역시 다즐 ^^

2023-11-06 11:35 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/dto/response/OAuthDisconnectResponse.java
> +}
record는 하나일 때도 내려서 사용하는 것이 더 가독성이 좋은 것 같더라구요.
아마 기존의 클래스의 형태가 익숙해서 그런 것 같아요.

2023-11-06 11:38 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +            @Value("${oauth.kakao.disconnect.admin-key}") final String appAdminKey
KakaoDevelopers페이지에서
내 애플리케이션 -> 앱 키에서 확인이 가능합니다!

2023-11-06 12:09 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +        final MultiValueMap<String, String> info = makeKakaoInfo(code);
<img width="750" alt="image" src="https://github.com/woowacourse-teams/2023-votogether/assets/51906604/f66cdaaf-4fe4-4445-9c6a-e520c4a6e562">
스프링에서 제공하는 HttpEntity클래스를 사용하기 위해서는 요청을 위한 데이터가 `MultiValueMap`으로만 가능하도록 구현되어 있습니다.
따라서 `MultiValueMap`을 사용했습니다!

2023-11-06 12:42 UTC, jeomxon commented on backend/src/main/java/com/votogether/domain/auth/service/oauth/KakaoOAuthClient.java
> +    public OAuthDisconnectResponse disconnectFromKakao(final Member member) {
[카카오 연결끊기 과정](https://developers.kakao.com/docs/latest/ko/kakaologin/common#unlink-and-deregister)
이 링크를 참고하시는게 더 이해하기 수월하실 것 같아요!

앱 어드민 키 + 카카오 유저 ID로 카카오 연결끊기 API에 요청을 보낸 후 응답을 정상적으로 받으면 disconnect가 됩니다!

2023-11-10 16:03 UTC, aiaiaiai1 approved these changes
답변 감사합니다 ㅎㅎ 고생하셨어요~

2023-11-13 08:18 UTC, tjdtls690 approved these changes
고생하셨습니다!

2023-11-13 08:23 UTC, woo-chang approved these changes
수고하셨습니다 👍

2023-11-14 12:19 UTC, merged