선택지 통계 조회 기능 구현
woowacourse-teams/2023-votogether pull request #83
Opened 2023-07-19 04:51 UTC by woo-chang

## 🔥 연관 이슈

close: #77

## 📝 작업 요약

선택지 통계 조회 기능을 구현하였습니다.

## 🔎 작업 상세 설명

- 선택지 통계 조회 기능을 구현하였습니다.
- 공통 예외 처리 방식을 사용해 보았습니다.
- 동적 쿼리 사용을 위해 querydsl을 적용해 보았습니다.

## 🌟 논의 사항

1. 각 도메인마다 예외 코드 설정
2. @Transactional은 메서드마다 붙이는게 가독성에 더 좋은가
3. Post에서 PostOption이 존재하는지 확인할지, PostOption의 Post가 맞는지 확인할지

2023-07-19 11:39 UTC, aiaiaiai1 requested changes
다즐 기능 구현하느라 고생하셨습니다~ 🙇 
몇가지 코멘트 남겨드렸는데 확인 부탁드려요!

2023-07-19 11:39 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
> +    }
이렇게 확인하면 Post에서 postOption을 확인하는 방법과 달리 조회 쿼리가 안나가도 되니까 더 좋은거같아요

2023-07-19 11:39 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`P1`: 작성자 본인만 투표 통계를 확인할 수 있어서 게시글을 자기가 썼는지에 대한 검증이 필요한거같아요

2023-07-19 11:39 UTC, aiaiaiai1 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
`P3` : `List<VoteStatus>` 의 일급컬렉션을 만들어서 서비스의 private 메서드를 일급 컬렉션 객체로 옮길 수 있을거같아요

2023-07-19 12:59 UTC, woo-chang commented on backend/src/main/java/com/votogether/exception/ExceptionType.java
> +    int getCode();
추후에 에러를 로그로 남기게 되었을 때, 여러 로그 중 에러 메시지로 에러를 찾기보다는 특정 에러 코드값으로 에러를 찾는 것이 더 용이하다고 판단되어 에러 코드도 추가해 보았습니다!
에러 코드를 지정하는 기준은 아직 정하지 않아서 다 같이 얘기해보면 좋을 것 같아요 :)

2023-07-19 13:45 UTC, woo-chang commented on backend/src/main/java/com/votogether/exception/NotFoundException.java
> +    }
`HttpStatus`는 Presentation 계층에 속한다고 생각합니다! 예외는 Business 계층에서 사용되어지는데 상태코드를 가지고 있으면 상위 계층의 정보가 하위 계층에 노출된다고 생각합니다. 따라서 상태코드는 Presentation 계층에 속하는 ExceptionHandler에서 지정하도록 개발을 진행하였습니다 😀

2023-07-19 13:46 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/vote/repository/VoteCustomRepositoryImplTest.java
> +        );
![image](https://github.com/woowacourse-teams/2023-votogether/assets/78212016/60403c95-eb02-45af-bfb6-61203a5477f4)
카카오 로그인을 통해 전달받은 정보로 다음과 같이 데이터베이스에 저장되기에 10대만 세부적으로 나누어 저장하도록 하였습니다 :)

2023-07-19 13:47 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/entity/PostOption.java
> +    }
그 부분을 고려하고 개발을 진행했는데 알아봐주시는군요 👍🏻

2023-07-19 13:48 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
회원가입 관련 기능이랑 합쳐지고 리팩토링 진행 예정입니다 :)

2023-07-19 13:52 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +
그런 방법도 고려해볼 수 있을 것 같습니다! 그럼 해당 일급 컬렉션은 어떤 패키지에 속하게 되는걸까요? 🤔

2023-07-20 01:44 UTC, aiaiaiai1 approved these changes
다즐 답변 감사합니다~ 고생하셨어요!

2023-07-20 01:54 UTC, tjdtls690 reviewed
명불허전 다즐신 👍👍

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
> +    List<VoteStatus> findVoteCountByPostOptionIdGroupByAgeRangeAndGender(@Param("postOptionId") Long postOptionId);
Q

@Param의 name 속성은 파라미터 명이 일치하면 생략할 수 있는 것으로 알고 있는데, 속성을 넣어준 이유가 있나요?

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +                .body(new ExceptionResponse(-9999, "알 수 없는 서버 에러가 발생했습니다."));
Q : 전 알 수 없는 에러의 경우 500 을 보내주었었는데, -9999로 하신 이유가 있나요?

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +    @Transactional
Q : 혹시 메서드가 아직 2개 뿐이어서 아직은 굳이 클래스에 붙일 필요가 없다고 생각하신건지 궁금합니다!

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/RepositoryTest.java
>  }
Repository, Service 별로 테스트 어노테이션을 묶어서 나누는 부분 굉장히 좋아보이네요. 많이 배웁니다 👍👍

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> -        final String filePath2 = "src/test/resources/images/" + fileName2;
오늘 제가 제거하는 작업 하려고 했는데 벌써 하셨군요...ㅋㅋ

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +                )
저는 보통 이런 경우 리스트는 따로 변수로빼서 하는 편인데, 이렇게 해놓으니 오히려 직관적이어서 더 괜찮은 부분도 있네요.

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> +        assertThat(result).usingRecursiveComparison().isEqualTo(response);
전 보통 .body() 를 써서 바로 테스트를 완료하는 형식을 선호해왔는데,

저번 저문 코드에서도 봤었지만, extract() 를 통해 객체를 직접 가져와서 when, then을 명확히 나누는 부분이 좋아보이네요.

2023-07-20 01:54 UTC, tjdtls690 commented on backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
> +public class MemberFixtures {
fixture 굳... ㄷ
저도 사용해도 될까요 ㅋㅋㅋ..

2023-07-20 02:01 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/vote/repository/VoteRepository.java
> +    List<VoteStatus> findVoteCountByPostOptionIdGroupByAgeRangeAndGender(@Param("postOptionId") Long postOptionId);
아벨이 말씀하신대로 JPQL에 사용하는 값이 변수명과 동일한 경우 생략할 수 있습니다 :)
변수명으로 정보를 전달하고 있기에 생략하는게 좋은 것 같습니다. `@Param` 어노테이션 자체가 필요없어져 삭제했습니다!

2023-07-20 02:05 UTC, tjdtls690 approved these changes

2023-07-20 02:07 UTC, woo-chang commented on backend/src/main/java/com/votogether/domain/post/service/PostService.java
> +    @Transactional
저도 처음에는 클래스 상단에 `@Transactional(readOnly = true)`를 붙이고 트랜잭션이 사용되는 메서드에 별도로 트랜잭션 어노테이션을 붙이는 방법을 사용했었습니다 ㅎㅎ

하지만 해당 방법을 사용하면서 어떤 메서드는 붙이고 어떤 메서드는 붙이지 않아 정작 필요한 경우에도 어노테이션을 붙이지 않는 실수가 많이 나오게 되었습니다. 실제로 붙이지 않아서 문제 상황을 겪은 경험도 있었습니다 🥲 따라서 조금 더 주의깊게 어노테이션을 붙이고자 각 메서드를 붙이는 방법을 고려해보게 되었고, 각 메서드가 어떤 트랜잭션 설정에서 동작하는지도 명시적으로 보여줄 수 있어서 각 메서드에 붙이는 방법으로 변경해서 적용 중에 있습니다.

이 부분도 팀 프로젝트에서 맞추면 되는 컨벤션이라 생각하기에 함께 얘기해보면 좋을 것 같아요 :)

2023-07-20 02:08 UTC, woo-chang commented on backend/src/test/java/com/votogether/domain/post/controller/PostControllerTest.java
> -        final String filePath2 = "src/test/resources/images/" + fileName2;
제가 작업하는 파일에 있어서 함께 진행했습니다 ㅎㅎ

2023-07-20 02:10 UTC, woo-chang commented on backend/src/test/java/com/votogether/fixtures/MemberFixtures.java
> +public class MemberFixtures {
언제든 편하게 사용하셔도 좋습니다 ~ 🌊

2023-07-20 03:54 UTC, merged

2023-07-20 06:07 UTC, tjdtls690 commented on backend/src/main/java/com/votogether/exception/GlobalExceptionHandler.java
> +                .body(new ExceptionResponse(-9999, "알 수 없는 서버 에러가 발생했습니다."));
이건 제가 잘못 파악했었네요--ㅋ